### ISSUE TITLE
Cannot use time anymore with the date/time picker

### ISSUE THREAD

**Issue by graphem** [wpmetabox/meta-box#1012]
Using the following value:

```php
array(
                'name' => 'Date',
                'id'   => "{$prefix}date",
                'type' => 'datetime',
                'js_options' => array(
                    'showTimepicker' => true,
                    'dateFormat'      => 'yy/mm/dd',
                    'timeFormat'      => 'hh:mm tt',
                    'showSecond' => false,  
                    'ampm' => true         
                ),
                'desc' => 'Desc'   
            ),
```

The time picker doesn't show a time anymore.

**Comment by funkedgeek** [comment]
Can you check the JS Console to see if there are any errors?  I'm not seeing this issue on my end

**Comment by DelhiKTaisse** [comment]
Hi,
I have the very same problem, with no issue in script loading.
The datepicker works fine, but without the timepicker.

For the record, here is what I return at the end of the rwmb_meta_boxes filter : 
`array(1) {
  [0]=>
  array(6) {
    ["id"]=>
    string(15) "my_dates"
    ["title"]=>
    string(22) "Dates de l'événement"
    ["post_types"]=>
    array(1) {
      [0]=>
      string(4) "post"
    }
    ["context"]=>
    string(6) "normal"
    ["priority"]=>
    string(4) "high"
    ["fields"]=>
    array(1) {
      [0]=>
      array(6) {
        ["clone"]=>
        bool(false)
        ["multiple"]=>
        bool(false)
        ["name"]=>
        string(23) "Début de l'événement"
        ["id"]=>
        string(20) "my_begin_date"
        ["type"]=>
        string(8) "datetime"
        ["js_options"]=>
        array(5) {
          ["showTimepicker"]=>
          bool(true)
          ["stepMinute"]=>
          int(1)
          ["showButtonPanel"]=>
          bool(false)
          ["dateFormat"]=>
          string(8) "dd/mm/yy"
          ["timeFormat"]=>
          string(5) "HH:mm"
        }
      }
    }
  }
}`

**Comment by DelhiKTaisse** [comment]
looks like I found what created troubles !
I found out that my theme (https://www.elegantthemes.com/gallery/extra/) also uses jquery UI date and time pickers. Though, it looks like it isn't the same version. Here are your version and elegant theme's : 
[timepickers.zip](https://github.com/rilwis/meta-box/files/575371/timepickers.zip)

I don't really know what would be the best way to get this to work together though ...

**Comment by rilwis** [comment]
I'll close this issue as it's the different version of the script in the theme. We're using the latest version. So, it's better to ask the theme author to update it.
