### ISSUE TITLE
Google Maps should have Places lib

### ISSUE THREAD

**Issue by Johnnychaos** [wpmetabox/meta-box#1037]
I think Google Map search address should also allow to search places and for this is should call libraries=Places in the API initialization. Here's docs:
https://developers.google.com/maps/documentation/javascript/examples/places-searchbox

Now if you search for example for Town Square Dubai you won't see any results.

**Comment by rilwis** [comment]
Hi Johnny,

When using the `map` field, we need to implement an address field and that address field already has the auto suggest feature (using geocode library).

If you want to add Places library to the field, you can use [this filter](https://github.com/rilwis/meta-box/blob/master/inc/fields/map.php#L22).

**Comment by Johnnychaos** [comment]
Hi rilwis, thank you for your answer. I use address field and it works fine for addresses. 
Can you help me with this filter? How should I call it?

**Comment by rilwis** [comment]
Hi @Johnnychaos ,

I looked at the code again and looks like the Places library requires some coding to make it work with the current implement (which uses Geocode to find a location).

I've just made a new change in the `map` field which now supports `region` parameter, which tells Google Maps to find a location in a specific region (country). You can try it with your case and you will get a better result.

**Comment by Johnnychaos** [comment]
Thank you @rilwis, I will check this out.
