### ISSUE TITLE
Warning: Invalid argument supplied

### ISSUE THREAD

**Issue by CronjeDesignCo** [wpmetabox/meta-box#1114]
Hi there,

Updated the plugin recently and now get this error:

Warning: Invalid argument supplied for foreach() in /home/holaawmp/public_html/wp-content/plugins/meta-box/inc/core.php on line 48

Anyone have any ideas on how to fix this?

Regards,
Terry

**Comment by rilwis** [comment]
Hi, probably the callback function that defines meta boxes has problems. Can you paste your code?

**Comment by CronjeDesignCo** [comment]
Hi, I got the plugin with a theme, and just updated to the latest version when this happened.

**Comment by rilwis** [comment]
Can you ask the theme author to update his theme and probably the included Meta Box to the latest version?

**Comment by danieldekay** [comment]
Hello, I just installed meta-box, and get the same error. 
Wordpress version: 4.7.3
Metabox Version: 4.11.3

**Comment by danieldekay** [comment]
When I activate the Meta Box Builder, the error disappears. But then I cannot use my php-based metaboxes.

**Comment by truongwp** [comment]
Please tell me which theme you are using and list your plugins for me to test. I guest that the return statement in register meta boxes code is missing.

**Comment by rilwis** [comment]
Please update Meta Box and all extensions. Feel free to reopen this issue if you still see the bug.
