### ISSUE TITLE
Cloneable groups - standard values

### ISSUE THREAD

**Issue by wgstjf** [wpmetabox/meta-box#1126]
Hi guys,

Just installed the latest MB and Group updates and crossed my fingers that they would bring the ability for cloned fields to retain the 'std' values but no joy :-(

Are you still planning on adding this feature?  If so, any idea when?

Cheers,

Will

**Comment by rilwis** [comment]
Hi Will, we haven’t done this feature yet. But it’s in the plan, absolutely. Hopefully will finish this month.

Thanks

**Comment by wgstjf** [comment]
That sounds great, thanks :-)

**Comment by wgstjf** [comment]
Did you get round to sorting this? :-)

**Comment by rilwis** [comment]
Oops, I did that in 8affdcb0735eb1e7c6c8cc98dd6e18824367ec06. Sorry to not notify you.

**Comment by wgstjf** [comment]
No worries and thanks for getting back to me on this. 

Quick question though.  How should one configure it so that all fields within a cloneable group have their std value when cloning the whole group?

Cheers,

Will

**Comment by rilwis** [comment]
Hi Will,

The `clone_default` is applied to each sub-field. So you need to specify which fields will clone the `std` value, which field won't. If you want to apply to all sub-fields of a group, please add the param to all field.

**Comment by wgstjf** [comment]
That's great, thanks for clarifying :-)
