### ISSUE TITLE
[REQ] Modular Approach 

### ISSUE THREAD

**Issue by ahmadawais** [wpmetabox/meta-box#1128]
This is a very nice plugin. I use and recommend it all the time. Could it be possible to make a modular version of it? Include the code for only the type of metaboxes being included?

**Comment by rilwis** [comment]
Thanks @ahmadawais for your suggestion. We're on the road of re-structuring the plugin to make it better. The hard part is keeping backward compatibility. So we do it slowly step-by-step, making sure it works all the time.

I'm not very clear about the "modular version" that you mean? Is that what we're doing now: separating other codes into extensions and keep only the core code for the Meta Box?

**Comment by ahmadawais** [comment]
Let's say I want to build a simple plugin that has only 3 meta boxes. Using your plugin (since I always embed the plugin) is an overkill. If it had been modular and I could only include the files for the meta boxes I use, just like you do in Node — that'd be great!

**Comment by rilwis** [comment]
I got it. Currently, if you use PHP >= 5.3, then the autoload is used and only required files are loaded. That's not 100% modular as you expect, but at some points. We'll work more on that to make all features modular.

**Comment by rilwis** [comment]
Yes, that’s what we have now. I also think it’s ok at the moment. Most PHP apps do the same.

Let me close this issue. If you have any idea, please leave a comment. Thanks.
