### ISSUE TITLE
Call to a member function get_source_lang_code() on null

### ISSUE THREAD

**Issue by ahmadazimi** [wpmetabox/meta-box#1138]
I've just updated metbox to the latest version, but after updating a php fatal error fired:
**Call to a member function get_source_lang_code() on null**

How can I handle it?

BTW: before updating everything was okay with my WPML!

**Comment by ahmadazimi** [comment]
Full error:
PHP Fatal error:  Call to a member function get_source_lang_code() on null in /private/var/www/webia/content/plugins/meta-box/inc/wpml.php on line 106

**Comment by truongwp** [comment]
Can you list all plugins are you using?

**Comment by ahmadazimi** [comment]
```
MetaBox 4.11.3
WPML Multilingual CMS 3.1.9.3
WPML String Translation 2.1.1
```

I think the name of the `$wpml_post_translations` variable may changed in the latest version of WPML.

**Comment by truongwp** [comment]
Can you update those plugins to latest version? They are too old so I can't find them to test.

**Comment by ahmadazimi** [comment]
Unfortunately I've purchased them last year and can not update them until I pay 100$ :D

Let me check if I can find a solution and report it to you.

**Comment by rilwis** [comment]
We already added a check for method_exists. Feel free if you still see this bug.
