### ISSUE TITLE
Uncaught TypeError: Cannot read property 'limitExceeded' of undefined

### ISSUE THREAD

**Issue by davidperezgar** [wpmetabox/meta-box#1139]
Hello, I'm having problems with Metabox in the admin. I get this error from the console:
Uncaught TypeError: Cannot read property 'limitExceeded' of undefined

and with the date input, the calendar icon does not appear and not working the calendar inside.

**Comment by funkedgeek** [comment]
What file and code line is being reported?  What is the code you are using for the meta box?  What plugins do you have installed?

**Comment by davidperezgar** [comment]
I've checked all plugins, and It get's conflict with Yoast SEO. I don't know why....

**Comment by rilwis** [comment]
Are you using [Meta Box for Yoast SEO](https://metabox.io/plugins/meta-box-yoast-seo/) extension? Can you post your code here?

**Comment by jurjens** [comment]
I had the exact same problem, but also an error that was casued by `media-audiovideo.js`. Both of them where fixed by calling `wp_enqueue_media()` explicitly in the `admin_enqueue_scripts` hook;

In `functions.php`
```
add_action('admin_enqueue_scripts', function() {
    wp_enqueue_media();
});
```

This just might be the solution for your problem as well.

**Comment by whitesnow9291** [comment]
Thanks jurjens, this worked for me, this happened when I install menu image plugin

**Comment by mschilder** [comment]
Had exact same issue, solution from jurjens works! Looks like Yoast SEO (in combination with some other plugin) seems to be causing this...

**Comment by rilwis** [comment]
Hi @mschilder , can you provide the code that registers meta boxes? If that's a bug in the plugin, I'd be happy to include the fix.

**Comment by mschilder** [comment]
Hi @rilwis. I'm sorry I don't fully understand your question. All I see that on my WordPress install, when activating either the Yoast SEO plugin OR the plugin Typeform the error of this issue appears.

The error can be solved by:
- Deactivating these plugins
- Adding the code from jurjens above to functions.php

If you need more info, please let me know!

**Comment by rilwis** [comment]
Hi @mschilder : Here is the repo for [Meta Box](https://metabox.io) plugin, so I assume you're using Meta Box. In case you use other plugins that cause the similar bug, please report to the plugins' authors. The question I asked above is for Meta Box only.

**Comment by FARAZFRANK** [comment]
@jurjens  That's the exact solution. Thanks so much.
