### ISSUE TITLE
How to add repeatable image + Title using text-list?

### ISSUE THREAD

**Issue by rvpatel** [wpmetabox/meta-box#1151]
https://github.com/rilwis/meta-box/blob/master/demo/text-list.php
How to add repeatable image + Title using text-list?

**Comment by truongwp** [comment]
Can you describe more detail about what you want?

**Comment by rvpatel** [comment]
Same like text-list but with option image, title,Link. This one usefully for brand related, Logo related options.

**Comment by rilwis** [comment]
`text_list` is not created for this purpose. It's just a list of text field.

To add image + title, the best option is using [Meta Box Group](https://metabox.io/plugins/meta-box-group/).
