### ISSUE TITLE
Google Map Field Saves on Scroll

### ISSUE THREAD

**Issue by ria-stamopoulou** [wpmetabox/meta-box#1155]
The google map fields saves the default (std) value in the database even if the user accidentally scrolls on the map (while scrolling to the bottom of the page).

**Comment by truongwp** [comment]
Do you mean map field saves value when scroll which not click Update button?

**Comment by ria-stamopoulou** [comment]
I mean the map field is saved (after the Update button is hit) even if a user just scrolls (zooms) in the map, which can obviously be done by accident while the user scrolls in the page.

**Comment by rilwis** [comment]
Google Maps already fixed this issue by themselves. So let me close this issue.
