### ISSUE TITLE
PHP Error: Object ... could not be converted to string

### ISSUE THREAD

**Issue by lolametro** [wpmetabox/meta-box#1158]
Hi,

My theme is Positivus which is a bit specific, but it produces an error with your plugin.
The error is `Catchable fatal error: Object of class WP_Post could not be converted to string in /xxx/wp-content/plugins/meta-box/inc/fields/choice.php on line 80`
It happens when the theme tries to show special theme "Page Header Options".

I had this issue before (https://github.com/rilwis/meta-box/issues/817), and now it's back. I can't tell you when it started to appear again, I only noticed it now.

If you need more information, please ask.
Many greetings

**Comment by funkedgeek** [comment]
Please post the code you are using to create the meta box.

**Comment by lolametro** [comment]
The issue was somewhere in an old part of the theme code.
In the meantime, I got this fixed. Thanks for your help.

**Comment by dixittejas** [comment]
Similar issue. @lolametro what you have changed to fix it? Please provide the filename and code to fix it. Thanks

**Comment by dixittejas** [comment]
@lolametro Can you help me? It's little bit urgent.
