### ISSUE TITLE
Catchable fatal error: showing while trying to create a new page.

### ISSUE THREAD

**Issue by anopn001** [wpmetabox/meta-box#1164]
Hi,

for the last few days while trying to create a new page i am getting 2 specific errors & redirecting to editing the main page. below are the 2 errors  i am getting.

Catchable fatal error: Argument 1 passed to RWMB_Core::fix_page_template() must be an instance of WP_Post, instance of stdClass given in /home/onetea7/public_html/wp-content/plugins/meta-box/inc/core.php

Warning: Invalid argument supplied for foreach() in /home/onetea7/public_html/wp-content/plugins/wordpress-seo/admin/metabox/class-metabox.php on line 1062

In the development server i am not having this issue. I tried replacing the live website files with the ones in the development server & even using the older versions of the meta box plugins. 

i am curently using zen 7 theam for website 
wordpress version is 4.8.1
meta box version is 4.11.2

Please do let me know what should i do to fix this. currently we are not able to add new pages or blog posts in the website. Hope top hear from u soon. 

Thanks & Regards

**Comment by funkedgeek** [comment]
Sounds like WordPress SEO and our plugin aren't working together.  Lets see if we can replicate this

**Comment by rilwis** [comment]
Looks like Yoast SEO plugin has fixed this issue. If you still see that, feel free to reopen this issue.
