### ISSUE TITLE
use and show text list in wp theme

### ISSUE THREAD

**Issue by wptricks** [wpmetabox/meta-box#1165]
hy my friend 
how i can use the text list for show the downloads link in my wordpress theme
`<a href="dl link"> description link</a>`
please help me

**Comment by funkedgeek** [comment]
Can you please describe what you need further?

**Comment by wptricks** [comment]
hi my friend 
i want to make unlimited download link like this
 `<a href="dl link"> description link</a>`
with the text list meta box 
but i cant use it and show it in my wp theme
please help me

**Comment by funkedgeek** [comment]
Can you provide the code you are using to create the meta box?

**Comment by funkedgeek** [comment]
if you set the field like so:

```
'fields' => array(
	array(
		'id'      => 'links',
		'name'    => __( 'Links', 'your-prefix' ),
		'type'    => 'text_list',
		'clone' => true,
		// Options: array of Placeholder => Label for text boxes
		// Number of options are not limited
		'options' => array(
			'Type in a description'      => __( 'Description', 'your-prefix' ),
			'domain.com' => __( 'Email', 'your-prefix' ),
		),
	),
```

Then you use the following to call the meta data:
`$links = rwmb_meta( 'links' );`

which will return an array of links.  Each entry in the array will be it's own array, index 0 being the description and index 1 being the link itself.  So, you would use a foreach loop:

```
foreach( $links as $link ) {
    echo sprintf( '<a href="%s"> %s</a>', $link[1], $link[0] );
}
```

Let me know if you need more help
