### ISSUE TITLE
RWMB_Text_Field not found ERROR

### ISSUE THREAD

**Issue by startrek1456** [wpmetabox/meta-box#1170]
Previously everything was working fine.My website crashed today with the error message RWMB_Text_Field not found in directory wp-content/metabox line 11 and so on..I deactivated all the plugins and one by one installed them.After the last meta box plugin was left everything worked fine..As soon as I activated metabox plugin the website crashed again.
I have deactivated METABOX plugin.But my website home page is working fine but the effects such as full banner on home page + no pages other than homepage is working..
![error](https://user-images.githubusercontent.com/32241057/30782945-7fb58490-a158-11e7-965f-e53c3a1a95f8.jpg)

**Comment by funkedgeek** [comment]
Please redownload the plugin.  Sounds like one of the files maybe corrupted
