### ISSUE TITLE
500 server error when updating to new version

### ISSUE THREAD

**Issue by joanngotts** [wpmetabox/meta-box#1172]
When I attempt to update from v4.8.1  to v4.12.3, I get locked out of my wp-admin and have to deactivate metabox via FTP to get back in to the WP admin dashboard.  Then I have to restore my previous version to get the metabox objects functioning back on my website.  Please advise.  Thanks.

**Comment by truongwp** [comment]
Hi @joanngotts,

Can you list plugins are you using? And will be great if you can share me the error log of server.

**Comment by joanngotts** [comment]
Thanks for responding to my post.  Here is a list of all the plugins we are using:

Akismet Anti-Spam
Contact Form 7
Count-N
Duplicate Post
Insert Headers and Footers
JEKAS EXTENSIONS
ManageWP - Worker
Meta Box
Ninja Forms
Redux Framework
Search Engine Visibilty
Slider REvolution
WP Google Maps
WP-Mail-SMTP
WP101 Video Tutorials
WPBakery Visual Composer
Yoast SEO

I'm attaching debug file.
[debug.log](https://github.com/rilwis/meta-box/files/1346523/debug.log)

Thanks in advance for your help.

**Comment by rilwis** [comment]
Hello, I've checked the `debug.log` file and found that your theme `jekas` creates a [custom field type](https://docs.metabox.io/custom-field-type/) for Meta Box. We have updated some method's parameter, so the custom field type need to be updated as well. Please ask the theme author to do that.
