### ISSUE TITLE
How to retrieve width and height of full_url version?

### ISSUE THREAD

**Issue by Lippiun** [wpmetabox/meta-box#1186]
Hi,

How can i retrieve the width and height for the full url rather than the url i specified? 

If i use, $ImgFtLeft['width'] it only returns the width of the image i'm using.

**Comment by rilwis** [comment]
Hi,

You can do this 2 ways:

1. Call the helper function again with `'size' => 'full'`:

```php
$image_full = rwmb_meta( 'field_id', array( 'size' => 'full' ) );
echo $image_full['width'];
echo $image_full['height'];
```

2. Retrieve width and height via image path:

```php
$image = rwmb_meta( 'field_id', array( 'size' => 'your_size' ) );
list( $width, $height ) = getimagesize( $image['path'] );
echo $width;
echo $height;
```
