### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by ndejong5** [wpmetabox/meta-box#1189]
Fatal error: Cannot assign by reference to overloaded object in /home/timoth52/public_html/wp-content/plugins/mb-customizer/inc/panel.php on line 20

**Comment by ndejong5** [comment]
Can anyone help me resolve this issue?

**Comment by rilwis** [comment]
Hi, are you using TheM or TheJ theme from fitwp.com? Please update the theme from ThemeForest. We have fixed these issues for those themes.

Thanks

**Comment by Shlalalamira** [comment]
I don't notice the fix, when reinstalling the theme.

	This theme requires the following plugin: MB Customizer.
and there is a fatal error in the plugin on line 20, causing my entire wordpress site to be disabled, including my admin page. Is there an updated version of this plugin or software? 

Please reach out to me asap so i can have it thanks

**Comment by rilwis** [comment]
The MB Customizer was updated some months ago. Please try remove the `mb-customizer` folder in `wp-content/plugins` then re-install it from the theme's `plugins` folder.
