### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by rafasegat** [wpmetabox/meta-box#1194]
WMB_Image_Advanced_MK2_Field::html($html, $meta, $field) should be compatible with RWMB_File_Field::html($meta, $field) in /www/htdocs/w0178823/flunkyoucrew.de/wp-content/themes/dt-the7/inc/extensions/custom-meta-boxes/metabox-fields.php on line 112

Warning: Declaration of RWMB_Image_Advanced_MK2_Field::meta($meta, $post_id, $saved, $field) should be compatible with RWMB_Field::meta($post_id, $saved, $field) in /www/htdocs/w0178823/flunkyoucrew.de/wp-content/themes/dt-the7/inc/extensions/custom-meta-boxes/metabox-fields.php on line 112

Warning: Declaration of RWMB_Taxonomy_List_Field::meta($meta, $post_id, $saved, $field) should be compatible with RWMB_Field::meta($post_id, $saved, $field) in /www/htdocs/w0178823/flunkyoucrew.de/wp-content/themes/dt-the7/inc/extensions/custom-meta-boxes/metabox-fields.php on line 935

Warning: Cannot modify header information - headers already sent by (output started at /www/htdocs/w0178823/flunkyoucrew.de/wp-content/themes/dt-the7/inc/extensions/custom-meta-boxes/metabox-fields.php:112) in /www/htdocs/w0178823/flunkyoucrew.de/wp-admin/includes/misc.php on line 1114

Warning: call_user_func_array() expects parameter 1 to be a valid callback, class 'RWMB_Simple_Proportions_Field' does not have a method 'normalize' in /www/htdocs/w0178823/flunkyoucrew.de/wp-content/plugins/facebook-gallery/meta-box/inc/field.php on line 531

Warning: call_user_func_array() expects parameter 1 to be a valid callback, class 'RWMB_Simple_Proportions_Field' does not have a method 'normalize' in /www/htdocs/w0178823/flunkyoucrew.de/wp-content/plugins/facebook-gallery/meta-box/inc/field.php on line 531

Warning: call_user_func_array() expects parameter 1 to be a valid callback, class 'RWMB_Fancy_Category_Field' does not have a method 'normalize' in /www/htdocs/w0178823/flunkyoucrew.de/wp-content/plugins/facebook-gallery/meta-box/inc/field.php on line 531

Warning: call_user_func_array() expects parameter 1 to be a valid callback, class 'RWMB_Simple_Proportions_Field' does not have a method 'normalize' in /www/htdocs/w0178823/flunkyoucrew.de/wp-content/plugins/facebook-gallery/meta-box/inc/field.php on line 531

Warning: call_user_func_array() expects parameter 1 to be a valid callback, class 'RWMB_Dropdown_Pages_Field' does not have a method 'normalize' in /www/htdocs/w0178823/flunkyoucrew.de/wp-content/plugins/facebook-gallery/meta-box/inc/field.php on line 531

Warning: call_user_func_array() expects parameter 1 to be a valid callback, class 'RWMB_Fancy_Category_Field' does not have a method 'normalize' in /www/htdocs/w0178823/flunkyoucrew.de/wp-content/plugins/facebook-gallery/meta-box/inc/field.php on line 531

Warning: call_user_func_array() expects parameter 1 to be a valid callback, class 'RWMB_Simple_Proportions_Field' does not have a method 'normalize' in /www/htdocs/w0178823/flunkyoucrew.de/wp-content/plugins/facebook-gallery/meta-box/inc/field.php on line 531

Warning: call_user_func_array() expects parameter 1 to be a valid callback, class 'RWMB_Dropdown_Pages_Field' does not have a method 'normalize' in /www/htdocs/w0178823/flunkyoucrew.de/wp-content/plugins/facebook-gallery/meta-box/inc/field.php on line 531

Warning: call_user_func_array() expects parameter 1 to be a valid callback, class 'RWMB_Fancy_Category_Field' does not have a method 'normalize' in /www/htdocs/w0178823/flunkyoucrew.de/wp-content/plugins/facebook-gallery/meta-box/inc/field.php on line 531

Warning: call_user_func_array() expects parameter 1 to be a valid callback, class 'RWMB_Simple_Proportions_Field' does not have a method 'normalize' in /www/htdocs/w0178823/flunkyoucrew.de/wp-content/plugins/facebook-gallery/meta-box/inc/field.php on line 531

Warning: call_user_func_array() expects parameter 1 to be a valid callback, class 'RWMB_Fancy_Category_Field' does not have a method 'normalize' in /www/htdocs/w0178823/flunkyoucrew.de/wp-content/plugins/facebook-gallery/meta-box/inc/field.php on line 531

Warning: call_user_func_array() expects parameter 1 to be a valid callback, class 'RWMB_Simple_Proportions_Field' does not have a method 'normalize' in /www/htdocs/w0178823/flunkyoucrew.de/wp-content/plugins/facebook-gallery/meta-box/inc/field.php on line 531

Warning: call_user_func_array() expects parameter 1 to be a valid callback, class 'RWMB_Dropdown_Pages_Field' does not have a method 'normalize' in /www/htdocs/w0178823/flunkyoucrew.de/wp-content/plugins/facebook-gallery/meta-box/inc/field.php on line 531

Warning: call_user_func_array() expects parameter 1 to be a valid callback, class 'RWMB_Simple_Proportions_Field' does not have a method 'normalize' in /www/htdocs/w0178823/flunkyoucrew.de/wp-content/plugins/facebook-gallery/meta-box/inc/field.php on line 531

Warning: call_user_func_array() expects parameter 1 to be a valid callback, class 'RWMB_Simple_Proportions_Field' does not have a method 'normalize' in /www/htdocs/w0178823/flunkyoucrew.de/wp-content/plugins/facebook-gallery/meta-box/inc/field.php on line 531

Warning: call_user_func_array() expects parameter 1 to be a valid callback, class 'RWMB_Simple_Proportions_Field' does not have a method 'normalize' in /www/htdocs/w0178823/flunkyoucrew.de/wp-content/plugins/facebook-gallery/meta-box/inc/field.php on line 531

Warning: call_user_func_array() expects parameter 1 to be a valid callback, class 'RWMB_Fancy_Category_Field' does not have a method 'normalize' in /www/htdocs/w0178823/flunkyoucrew.de/wp-content/plugins/facebook-gallery/meta-box/inc/field.php on line 531

Warning: call_user_func_array() expects parameter 1 to be a valid callback, class 'RWMB_Simple_Proportions_Field' does not have a method 'normalize' in /www/htdocs/w0178823/flunkyoucrew.de/wp-content/plugins/facebook-gallery/meta-box/inc/field.php on line 531

Warning: call_user_func_array() expects parameter 1 to be a valid callback, class 'RWMB_Fancy_Category_Field' does not have a method 'normalize' in /www/htdocs/w0178823/flunkyoucrew.de/wp-content/plugins/facebook-gallery/meta-box/inc/field.php on line 531

Hi my client is showing this error.

**Comment by rilwis** [comment]
Hi,

The errors say your custom fields which extends from Meta Box fields don't have the same parameters for some methods. Please just update your fields, making sure the parameters the same and the errors will gone.

If you need any help, I can work on the code for you.

**Comment by rafasegat** [comment]
Hi

Can you fix it?

What's your email?


Thanks so much!
Raf
http://rafsegat.com

*Hire me! I'm available for freelance work.*

On Tue, Dec 5, 2017 at 6:51 PM, Tran Ngoc Tuan Anh <notifications@github.com

**Comment by rilwis** [comment]
Yes, I can. Please send your info to anhtnt [at] elightup.com.

**Comment by rafasegat** [comment]
I just sent it, but no one answer me.

Thanks so much!
Raf
http://rafsegat.com

*Hire me! I'm available for freelance work.*

**Comment by rilwis** [comment]
I've replied you via email. Let's talk there.
