### ISSUE TITLE
Slow loading of a 'page edit' screen

### ISSUE THREAD

**Issue by kkPavel** [wpmetabox/meta-box#1195]
Hello!

I'm using the 'MetaBox Conditional Logic' plugin to develop an advanced page settings in my theme. I have 86 fields on a 'Edit Page' screen in the admin panel. Most of them are depend by other fields. The problem is the speed of loading the "Edit Page" screen with so many fields. The loading speed is ~10 seconds now. Very slow...

Could you give me any advice to improve speed of "Edit Page" screen loading in this situation?

Regards,
Paul

**Comment by rilwis** [comment]
Hi Paul,

I think the number of fields with the conditional logic slows down the page. As the JavaScript code needs to run when page is loaded to prepare for all the logic. It's a heavy JS code. We'll try to make if more lightweight and faster. On the user side, I think the only way is reduce the number of fields and/or logic.

**Comment by kkPavel** [comment]
Okay, Thank you!

**Comment by kkPavel** [comment]
Hello!

I have improved the edit page loading speed by making a little changes in the plugin JS code. I'm not sure but maybe it will be useful for future updates. I put the 'runConditionalLogic(conditionals)' call and event listeners into a handler of window 'load' method in in the **'conditional-logic.js'** file.

**Before:** 

```
// Load conditional logic by default
runConditionalLogic(conditions);

// Listening eventSource apply conditional logic when eventSource is change
if (window.eventSource.length > 1) {
	$(document).on('change keyup click', window.eventSource, function(event) {
		runConditionalLogic(conditions);
	});
}
```

**After:**

```
$(window).on('load', function(){
	// Load conditional logic by default
	runConditionalLogic(conditions);

	// Listening eventSource apply conditional logic when eventSource is change
	if (window.eventSource.length > 1) {
		$(document).on('change keyup click', window.eventSource, function(event) {
			runConditionalLogic(conditions);
		});
	}
});
```

I improved the page load speed by 70% (from 13s to 4s). The page has more than 100 fields.

Best regards,
Paul

**Comment by rilwis** [comment]
Hi Paul,

Thanks for your help! I will add your fix to the plugin and release a new version!

That's a good fix!

**Comment by brett-ambr** [comment]
Just following up on this point. For conditional logic, when we have a lot of content on the page, it slows the editor down extremely. It takes anywhere from 3-15 seconds just to select a radio button. 

This is gone the moment the conditional logic plugin is turned off. 

We have an editor that allows the client to select different layout types (via your groups plugin), so there are quite a few meta fields (60+). As mentioned, the more content we add to the page, the slower it gets. It's at the point where it's essentially unuseable. Please advise any workarounds or strategies, thank you!

**Comment by rilwis** [comment]
Hi @brett-ambr ,

The fix in this issue was applied in the Conditional Logic extension.

However, as the extension heavily uses DOM elements to perform the check, it's still slow. I'd suggest to reduce the number of fields (by organizing them better) and/or the number of conditions.

I'll keep improving the JS part, but probably not much at the moment.
