### ISSUE TITLE
Group Columns issue

### ISSUE THREAD

**Issue by wgstjf** [wpmetabox/meta-box#1201]
Hi,

I have just noticed an issue that didn't exist before I updated to the latest versions of MB, Columns and Group...hope you can help.

I have a Meta box with the following fields:

```php
// TEXT - Panel Title
array(
	'name'  => __( 'Panel Title', 'indigo-options' ),
	'desc' => 'What is the title for this panel?',
	'id'    => $prefix.'primary_title',
	'class'  => 'big-text',
	'type'  => 'text',
	'std'   => '',
	'clone' => false,
	'columns'   => '6',
	'add_to_wpseo_analysis' => true,
),

// IMAGE ADVANCED - Promo Panel Image
array(
  'name'  => 'Panel Side Image',
  'desc'  => 'Upload or select an image. <b>Min dimensions 1400px(w) x 630px(h)</b>',
  'id'    => $prefix.'primary_image',
  'type'  => 'image_advanced',
  'std'   => '',
  'max_file_uploads' => 1,
  'columns'     => '6',
  'clone' => false,
),
array(
    'id' => $prefix.'primary_buttons',
    'type' => 'group',
    'clone' => false,
    'sort_clone' => true,
    'collapsible' =>  true,
    'save_state' =>  true,
    'group_title' =>  'Panel Buttons Setup',
    //'columns' => '12',
    // List of sub-fields
    'fields' => array(
        .....etc....

```

and it is now showing like this.  The problem being that the 'Panel Buttons Setup' group is not full width.  

![image](https://user-images.githubusercontent.com/3740694/34604006-27f160ac-f1fe-11e7-8b70-2a1fd2eff229.png)

If I define the group as having 12 columns width then the entire metabox doesn't close properly leaving subsequent metabox inside this one...

![image](https://user-images.githubusercontent.com/3740694/34604190-d7998692-f1fe-11e7-90b2-affdd42638ef.png)

Can you replicate this issue?  Any thoughts on a fix?

Cheers,

Will

**Comment by rilwis** [comment]
Hi Will, just found the bug. Please update!

**Comment by wgstjf** [comment]
Outstanding as always.  Will update now.

Cheers,

Will

**Comment by wgstjf** [comment]
Problem solved, thanks!  :-)
