### ISSUE TITLE
My site fall dow in part

### ISSUE THREAD

**Issue by lreis2104** [wpmetabox/meta-box#1203]
My mainpage and another one fall down when I've upload to 4.13.1 

I would like to install a previous one.

Would be possible?

**Comment by lreis2104** [comment]
I could upload a backup of my site. Anyway I've using 4.13.0 without any problem. My template YOGA CLUB from softwebmedia and my site https://vidalongeva.es

**Comment by rilwis** [comment]
Do you see any errors in the log?

If you use cPanel, there's a section errors log that you can see all errors.

**Comment by rilwis** [comment]
Let me know if the problem still occur. Feel free to reopen the issue.
