### ISSUE TITLE
Meta Box for Yoast SEO

### ISSUE THREAD

**Issue by eideindustries** [wpmetabox/meta-box#1204]
I am not sure where this is supposed to be added. Any help would be appreciated. 

Usage

After installing the plugins, just add 'add_to_wpseo_analysis' => true to the fields’ configuration to add them to Yoast SEO Content Analysis.

**Comment by rilwis** [comment]
For example, you define a custom field like this:

```php
array(
    'id' => 'my_content',
    'title' => 'My Content',
    'type' => 'textarea',
)
```

Then to make it analyzable by Yoast SEO, simple modify it to:

```php
array(
    'id' => 'my_content',
    'title' => 'My Content',
    'type' => 'textarea',
    'add_to_wpseo_analysis' => true,
)
```

**Comment by eideindustries** [comment]
Thank you for the response, where can I find the place to modify that?

**Comment by rilwis** [comment]
You need to find the code that register your meta box.
