### ISSUE TITLE
Feature Request: Post Field Clonable inside Group (Meta Box Builder)

### ISSUE THREAD

**Issue by parityhero** [wpmetabox/meta-box#1205]
Can we make the post field have the ability to be cloned when inside a group?

**Comment by rilwis** [comment]
It's already supported. Just set `'clone' => true` for `post` field and it will be cloneable, whether or not it's inside a group.

**Comment by parityhero** [comment]
Oh sorry there I meant with the meta box builder extension

**Comment by rilwis** [comment]
Ah, I got it. Let me check that.

**Comment by rilwis** [comment]
FYI, the latest version of [Meta Box Builder](https://metabox.io/plugins/meta-box-builder/) has fixed this.
