### ISSUE TITLE
Metabox Map Not working on front end

### ISSUE THREAD

**Issue by TECKSPEED** [wpmetabox/meta-box#1207]
I am working locally on a website for a client, I have so far loved the plugin, however, running locally only i have found that the map does not show on the front end of my site. I ensured that I have a valid API Key for google maps and also ensured that I have not for some reason hit my quota. 

I have setup the text address field and the map field in my functions.php but cannot get the map to show on the front end of the site.

![image](https://user-images.githubusercontent.com/10875873/35889778-0c9fcfec-0b6b-11e8-9a59-e5eada32a21e.png)

![image](https://user-images.githubusercontent.com/10875873/35889794-1ad3b920-0b6b-11e8-9600-475d3d3952e8.png)

**Comment by rilwis** [comment]
Hello, I see you use `$prefix` in your code. Did you miss to pass it into the `rwmb_meta` function?

**Comment by TECKSPEED** [comment]
‘$prefix’ is empty I got the meta key directly from the custom fields on the post.

**Comment by rilwis** [comment]
Can you try:

`echo rwmb_meta( 'retailer_map_location' );`

Also, do you see any error in the console? Or is there any CSS that hides the map?

**Comment by rilwis** [comment]
Feel free to re-open this issue if you still see the bug.
