### ISSUE TITLE
Reverse srcset order so smallest image is first in list

### ISSUE THREAD

**Issue by Lippiun** [wpmetabox/meta-box#1208]
Hi,

I'm using the image_advanced field and I'm displaying the images with the attribute ['srcset']. However, when I look at the source code for the image and compare it to the post_thumbnail source the srcset values are reversed. 

The post thumbnail orders the srcset by the smallest image first whereas when I look at the source code for the images generated by metabox, the largest is displayed first. 

I'm wondering if there is a way of reversing this order so it's the same as the post thumbnail?

**Post thumbnail code**
`srcset="http://bluemoontesting.co.uk/susatchwell/wp-content/uploads/2018/02/st-pauls-slider-2-555x400.jpg 555w, http://bluemoontesting.co.uk/susatchwell/wp-content/uploads/2018/02/st-pauls-slider-2-1110x800.jpg 1110w">`

**Images generated by metabox code**
`srcset="st-pauls-door.jpg 1010w, st-pauls-door-768x1151.jpg 768w, st-pauls-door-505x757.jpg 505w, st-pauls-door-839x1258.jpg 839w, st-pauls-door-420x629.jpg 420w, st-pauls-door-720x1080.jpg 720w, st-pauls-door-360x540.jpg 360w"`

 ```
<figure class="scene_element scene_element--fadeinup" itemprop="associatedMedia" itemscope itemtype="http://schema.org/ImageObject"> <a href="<?php echo $ImgFtLeft['full_url']; ?>" itemprop="contentUrl" data-size="<?php echo $ImgFtLeftFull['width']; ?>x<?php echo $ImgFtLeftFull['height']; ?>'"> <img src="<?php echo $ImgFtLeft['url']; ?>" srcset="<?php echo esc_attr($ImgFtLeft['srcset']); ?>" 
											sizes="(max-width: 767px) 100vw, (min-width: 768px) and (max-width: 991px) 100vw, (min-width: 992px) and (max-width: 1199px) 415px, (min-width:1200px) and (max-width: 1400px) 505px, (min-width:2048px) 1010px, 505px" itemprop="thumbnail" alt="<?php echo $ImgFtLeft['title']; ?>" > </a>
                                <figcaption itemprop="caption description">
                                    <?php echo $ImgFtLeft['caption']; ?> </figcaption>
                            	</figure>
```

**Comment by rilwis** [comment]
Hi,

I don't see that in my output. Here is the code I use:

![code](https://i.imgur.com/dnrE7ef.png)

And here is the output:

![output](https://i.imgur.com/Gb6b0AS.png)
