### ISSUE TITLE
Map marker not show in WordPress 4.9.4 and latest Metabox plugin

### ISSUE THREAD

**Issue by waqasriaz** [wpmetabox/meta-box#1210]
Here is screenshot http://take.ms/wECXF

**Comment by rilwis** [comment]
Hi @waqasriaz ,

Sorry for the late reply. We're just been back from the Tet holiday. Regarding the bug, I've just tested and the map market is showing:

![google maps](https://i.imgur.com/oPWhPGl.png)

Do you see any error in the console? Normally, Google Maps will shows errors in the console of there's any.

By the way, can you send me your meta box code to check?

**Comment by waqasriaz** [comment]
This is console http://take.ms/N4nnP
It work when i use this CSS
.gmnoprint[style] {
    overflow: visible !important;
    opacity: 1 !important;
}

**Comment by rilwis** [comment]
Thanks for your help! The bug came from the ambitious CSS selector in the [Meta Box Columns](https://metabox.io/plugins/meta-box-columns) extension. I've fixed and updated the plugin. Please update and let me know how it goes.
