### ISSUE TITLE
Little help please

### ISSUE THREAD

**Issue by yupii1986** [wpmetabox/meta-box#1212]
Hi,
Awesome product,
I want to build my theme and i need some info,
I use layerswp framework, This theme framework have in customizer 6 header types.
I used online generator metabox and add to my function.php but how can i take info from customizer?
Thanks

**Comment by rilwis** [comment]
Hi, to get info from customizer, please use get_theme_mod() function. Also check the layerswp framework docs for more details, it probably use a different way to get / set data.
