### ISSUE TITLE
Customize autogenerated metabox for relationships

### ISSUE THREAD

**Issue by Giacomo92** [wpmetabox/meta-box#1213]
Hy everyone,
is there a way to customize the html of the relationships for the backend side?

I have to add more **children's field**  in order to edit it directly from father view. I also have to add the **drag feature** so i can handle the print order of the custom post's children.

This is a screen from Band Edit View (I use the same example of the [site tutorial](https://metabox.io/plugins/mb-relationships/))

<img width="1430" alt="schermata 2018-02-23 alle 02 23 15" src="https://user-images.githubusercontent.com/11694429/36573319-8fea2776-1840-11e8-96df-6997886b659b.png">

In a few words, I have to recreate all the functionality of the existing "Text List" field type. 

Thank you for your help

**Comment by rilwis** [comment]
Hi,

I will add the drag feature tomorrow. Regarding the children's field, what do you need exactly? Is it similar to connection meta data?

**Comment by Giacomo92** [comment]
Thank you so much @rilwis . I will wait for the update. 

Regarding the children's field I need a quick edit/add/remove for the children custom post. So for example I can edit the event title and the post content directly from Band Edit View.
What can I do to render this information ?

**Comment by rilwis** [comment]
I've just updated with the "sortable" feature.

Regarding the editing, it's not supported for now. I'd love if you can help me on that.

**Comment by Giacomo92** [comment]
I can try to add this feature@rilwis.

I have just update the plugin. 
On backend side it is all perfect but on the frontend I still have the post_date order.

**Comment by rilwis** [comment]
You need to set `'orderby' => 'post__in'` to sort the posts by the order in the backend. Otherwise, the `orderby` param is auto set to `post_date`.

**Comment by Giacomo92** [comment]
Here there is my code:
`    
      $connected = new WP_Query( array(
	'relationship' => array(
		'id'   => 'percorsi_to_punti_interesse',
		'from' => get_the_ID(), // You can pass object ID or full object
	),
	'nopaging'     => true,
	'orderby' => 'post__in'
     ) );

	$pis = $connected->posts;
	foreach ($pis as $pi){
		var_dump($pi);
		//code for a single child
	}

        wp_reset_postdata();
`

I can not see any  **post__in** in the dump of $pi variable. Also in my opinion, if a set **'sort_clone' => true** I am expecting the backend order order as default.

**Comment by Giacomo92** [comment]
Hi @rilwis, have you got any news about the order of children posts?

Your code are not working.

**Comment by rilwis** [comment]
@Giacomo92 Just fixed it in the recent version. Please update and let me know how it goes.

**Comment by Giacomo92** [comment]
Yeah it's working like a charm.

Thank you so much @rilwis
