### ISSUE TITLE
Image Advanced Won't Add/Remove/Save With Many Uploads

### ISSUE THREAD

**Issue by KincadePavich** [wpmetabox/meta-box#1216]
I have an Image Advanced MetaBox field that I use to display galleries on many different pages on our site. On the pages with 10 images or so, the field works perfectly. I can add, remove, update the Image Advanced field. No problems. I don't know exactly what the magic number is, but once I hit a lot of uploads nothing works. Can't add, can't remove. We have a portfolio with 253 images that I can't update whatsoever. The code is the same; I tested this on a page that had 3 images and was working properly (add, remove, update). I added 300 images and it saved, and now I can no longer make any changes.

Here's the function...

    function portfolio_gallery( $meta_boxes ) {
	$prefix = '';

	$meta_boxes[] = array(
		'id' => 'portfolio_box',
		'title' => esc_html__( 'Isotope Portfolio', 'metabox-online-generator' ),
		'post_types' => array( 'page' ),
		'context' => 'advanced',
		'priority' => 'default',
		'autosave' => false,
		'fields' => array(
			array(
				'id' => $prefix . 'image_advanced_1',
				'type' => 'image_advanced',
				'name' => esc_html__( 'Image Advanced', 'metabox-online-generator' ),
				'desc' => esc_html__( 'Tags: logo, design, promotional, apparel, website, printing, signs', 'metabox-online-generator' ),
				'max_file_uploads' => 1000,
				'max_status' => true
			),
		),
	);

	return $meta_boxes;
    }
    add_filter( 'rwmb_meta_boxes', 'portfolio_gallery' );

If anyone has any suggestions it would be greatly appreciated. On the page I added 300 to as a test I can't even remove them, so I have to hide them via CSS for the time being. I don't want to remove the field entirely, as we have many pages with galleries that I don't want to get removed. I need to figure  out how to get desired functionality with very large galleries.

Thanks.
Kincade

**Comment by rilwis** [comment]
Hi, the `image_advanced` fields loads saved value via ajax request, so it takes a little time to load all pages. **Only when it’s loaded, the field inputs are added**. So, please don’t update the post before it finishes loading (in that case all inputs are not fully added, and updating will make the post lost saved values).

I think this is the problem with large galleries, that when page loads, not all images are loaded. Unfortunately, that's the default behavior. There's no solution for this yet.

**Comment by KincadePavich** [comment]
That's interesting and good to know; although there's no clean solution yet it's good to know I can just wait a bit to make sure everything has loaded and still make updates. Thank you!
