### ISSUE TITLE
Getting Error on the top of each page

### ISSUE THREAD

**Issue by FandomSpotlite** [wpmetabox/meta-box#1217]
Receiving the error:
Warning: Invalid argument supplied for foreach() in /homepages/37/d687371089/htdocs/clickandbuilds/WordPress/CosplaySpotlite/wp-content/themes/agazine/functions.php on line 101

This is showing up on the top of every page on my website at www.fandomspotlite.com - definitely has to do with MetaBox and deactivating the plugin crashes the site. Need to either fix or remove cleanly.

**Comment by rilwis** [comment]
Hello,

As the error message clearly says: the error occurs in the line 101 of the `functions.php` **of the theme**. So, check out that file and see what's there. Post that code here so I can help.
