### ISSUE TITLE
Getting error in Image Select Field in the latest update

### ISSUE THREAD

**Issue by abhi21x** [wpmetabox/meta-box#1218]
Hi Team

Only getting this error for **Image Select** field. Rest of the fields are working good so far.

-----------------------------

**Notice**: Undefined index: options in /Applications/MAMP/htdocs/wptest/wp-content/plugins/meta-box/inc/fields/image-select.php on line 32

**Warning**: Invalid argument supplied for foreach() in /Applications/MAMP/htdocs/wptest/wp-content/plugins/meta-box/inc/fields/image-select.php on line 32

**Comment by rilwis** [comment]
Please post your code to register meta boxes.

**Comment by abhi21x** [comment]
```
function image_select_metabox( $meta_boxes ) {
	$prefix = 'cmu-';

	$meta_boxes[] = array(
		'id' => 'image-select-metabox',
		'title' => esc_html__( 'Image Select', 'CMU' ),
		'post_types' => array( 'post', 'page' ),
		'context' => 'after_title',
		'priority' => 'default',
		'autosave' => false,
		'fields' => array(
			array(
				'id' => $prefix . 'image_select_1',
				'type' => 'image_select',
				'name' => esc_html__( 'Image Select', 'CMU' ),
				'force_delete' => false,
				'max_file_uploads' => '4',
			),
		),
	);

	return $meta_boxes;
}
add_filter( 'rwmb_meta_boxes', 'image_select_metabox' );
```

**Comment by rilwis** [comment]
Hi, `image_select` is not like that. See [this docs](https://docs.metabox.io/fields/image-select/) for details.

In your case, change `image_select` to `image_advanced` and it will work.
