### ISSUE TITLE
update post meta manually - Field type: image_upload

### ISSUE THREAD

**Issue by wp098** [wpmetabox/meta-box#1221]
Hello, 
I thank you for this good plugin. that's so prefect.

I wanna update post meta where it's field type is **image_upload**.
So, I put my attachments ids in an array. like this:
```
$ar = array();
$ar[0] = 75598; // an attachment ID
$ar[1] = 9999; // an attachment ID
$ar[2] = 911119; // an attachment ID

update_post_meta(122, 'images', $ar ); // "images" is my field ID
```
But In dashboard photos can't load ...!

> I tried so much but I think it is not easy ! Please help me.

Thanks a lot,

**Comment by rilwis** [comment]
Hello,

The values for image field is saved as [multiple lines in the post meta](https://docs.metabox.io/fields/image-advanced/#data), so you need to change the code to:

```php
foreach ( $ar as $img ) {
    add_post_meta( 122, 'images', $img, false );
}```
