### ISSUE TITLE
Group addon: Optimize delete/collapse icon positions

### ISSUE THREAD

**Issue by flowdee** [wpmetabox/meta-box#1223]
In my opinion the the _collapse_ and _delete_ icons are not at a good position right now.

<img width="1160" alt="bildschirmfoto_2018-03-24_um_16_50_11" src="https://user-images.githubusercontent.com/2278756/37865935-a8174554-2f83-11e8-9561-492dd5c5011d.png">

The risk of clicking "delete" instead of "collapse" is way too high. Not for me personally, but for many customers which are not that "skilled" with their mouse.

Either the positioning of the icons should be optimized or alternatively a javascript confirmatio (when deleting an item) added.

**Comment by rilwis** [comment]
I've just released a new version of the [Meta Box Group](https://metabox.io/plugins/meta-box-group/), which has 2 improvements for this:

- The remove link is now placed next to the group title, and only appears when hover the group title.
- There's a confirmation popup when users click on the remove link.

Please update to version 1.2.15!

Cheers,
Anh
