### ISSUE TITLE
taxonomy_advanced not working

### ISSUE THREAD

**Issue by pipdig** [wpmetabox/meta-box#1224]
With the latest version of Metabox 4.14.1, the taxonomy_advanced field is pulling through a value even when no value has been selected for a post.

So when using rwmb_meta to check for a value, it always returns an array of taxonomy data rather than NULL. This has caused a serious issue in our themes since features are being activated for post content that should not display.

Rolling back to version 4.14.0 fixed the issue.

I hope you guys can fix asap :)

```
$meta_boxes[] = array(
	'id'       => 'meta_boxes_id',
	'title'    => 'Title',
	'pages'    => 'post',
	'context'  => 'side',
	'priority' => 'low',
	'fields' => array(
		array(
			'name'  => "Name",
			'id'    => field_id'',
			'taxonomy' => 'tax_name',
			'type'  => 'taxonomy_advanced',
		)
	)
);
```

The following will always return true, even if a value has not been selected for the post in the loop:
```
if (rwmb_meta('field_id')) {

}
```

**Comment by rilwis** [comment]
Hi @pipdig , can you check the fix in the recent commit?

**Comment by pipdig** [comment]
Hi @rilwis, that fixed it, thanks for the quick response!

Do you know when this will be released in an update to the plugin on the WP repo?

**Comment by rilwis** [comment]
Tomorrow. Can you confirm the fix works for your themes?

**Comment by pipdig** [comment]
Yes it is now working as expected in all of our themes. Looking forward to the update and thanks again!

**Comment by rilwis** [comment]
New version is available :)

**Comment by pipdig** [comment]
Awesome, everything is working as expected now. Thanks for the super quick update.

We've been using Meta Box for many years and haven't had any issues, keep up the great work!
