### ISSUE TITLE
Image Advanced JS Events

### ISSUE THREAD

**Issue by JasonTheAdams** [wpmetabox/meta-box#1230]
Greetings!

Looking at porting an existing project using another meta box framework over to Meta Box. One need that we've got is that we used the HTML field to add a small react app for previewing what the group fields will look like when rendered. This requires hooking into a number of JS events. Most are built right in, but I was curious what events there are for the Image Advanced field. Basically, we'd need a `change` event and ability to get the id of the image (max 1 image). Is there currently a change event? It looks like there is but I wanted to confirm.

With that, it would be awesome if the documentation reflected the JS events/hooks available in the same way that the PHP hooks are. 😃 

Great work!

**Comment by rilwis** [comment]
Hi Jason,

Sorry to the delay.

The `change` event for `image_advanced` field is in the [`media.js`](https://github.com/wpmetabox/meta-box/blob/master/js/media.js#L160) file. When an image is added or removed, it's fired on the hidden input of the field. This hidden input is used to store the field options.

See this screenshot: https://i.imgur.com/0cuQAoJ.png

There are not many JS events / hooks in Meta Box :). There are only some custom clone events that we use internally to make the clone works. However, if you need any custom event, please just ask. I'll add.

**Comment by JasonTheAdams** [comment]
Very good to know, thank you!
