### ISSUE TITLE
Fatal Error unexpected "[" on line 124

### ISSUE THREAD

**Issue by designsbyd** [wpmetabox/meta-box#1233]
## Issue Overview
updated the meta-box plugin and the whole site crashed. lines begining at 119:

119. 	public static function raw_meta( $object_id, $field, $args = array() ) {
120. 		if ( empty( $field['id'] ) ) {
121. 			return '';
122. 		}
123. 
124. 		$meta = wp_get_object_terms( $object_id, $field['taxonomy'], [
125. 			'orderby' => 'term_order',
126. 		] );
127. 		$meta = wp_list_pluck( $meta, 'term_id' );
128. 
129. 		return $field['multiple'] ? $meta : reset( $meta );
130. 	}

## Steps to Reproduce (for bugs)

1. update meta-box plugin
2. error on line 124 of taxonomy.php
3.
4.

## Expected Behavior

i would expect it to function as usual but even after going through the ftp and renaming the plugin and reinstalling it the error persists.

## Current Behavior

fatal error which makes the entire site unviewable/unusable

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by designsbyd** [comment]
renaming the taxonomy.php file resolves the issue but then i don't have custom taxonomies.

**Comment by rilwis** [comment]
Sorry, that's the PHP 5.4 syntax. I guess you're using an old version of PHP. If you have a chance, tell your host provider to upgrade it.
