### ISSUE TITLE
Taxonomy Advance does not return a term object

### ISSUE THREAD

**Issue by Giacomo92** [wpmetabox/meta-box#1234]
I use taxonomy advance as field. This is my code:

```
array (
				'name' => __('exterior_color'),
				'id' => 'exterior_color',
				'type' => 'taxonomy_advanced',
				'taxonomy' => 'exterior-color',
				'field_type' => 'select_advanced',
				'class' => 'oa-select-color',
				'tab' => 'features',
			),
```
When I try to get his value with this code:
```
$terms = rwmb_meta('exterior_color');
```
Instead of return me a term object, I only get the term id. Pratically this code from documentation does not work:

```
if ( ! empty( $terms ) && ! is_wp_error( $terms ) ) {
    foreach ( $terms as $term ) {
        echo '<p>', $term->name, '</p>';
    }
}
```

**Comment by rilwis** [comment]
I've just tested your code and it returns me a term object. So I guess the problem is the same as in this ticket #1235 . Probably you use the filter `rwmb_meta_boxes` only in the admin area. Please check it.
