### ISSUE TITLE
Custom Field does not save the value

### ISSUE THREAD

**Issue by Giacomo92** [wpmetabox/meta-box#1236]
In order to follow the theme structure I have to store a term_name as a terms’ ID on a custom post. This is a different approach compared to taxonomy_advanced. So I try to reproduce all the select ovverriding the html method (I only set value == term->name instead term->id). The select is created correctly with all its value but nothing is saved. 

This is the code:
```
class RWMB_Oa_Taxonomy_Advanced_Field extends RWMB_Field {
		public static function html( $meta, $field ) {
$current_value = get_post_meta(get_the_ID())[$field["taxonomy"]][0];

			$options = get_terms($field['id'],array( "hide_empty" => 0 ));
			$output = "<select id='" . $field["id"] ."' class='rwmb-taxonomy_advanced rwmb-select_advanced select2-hidden-accessible'>";
			$output .= '<option value="">Seleziona</option>';
			foreach ($options as $option){
				$selected = "";
				if($option->name == $current_value){
					$selected = "selected";
				}

				$output .= sprintf(
					'<option value="%s" %s>%s</option>',
					esc_attr( $option->name ),
					$selected,
					esc_attr( $option->name )
				);
			}
			$output .= "</select>";
			return $output;
		}

	}
```

**Comment by rilwis** [comment]
Hello,

The method you used in your [custom field type](https://docs.metabox.io/custom-field-type/) is `html`, which outputs the field's HTML only. In order to change the value saved in the database (which in this case is field's name), you should use the method `value`. Please see [this docs](https://docs.metabox.io/rwmb-field-class/) for list of available methods.

**Comment by Giacomo92** [comment]
I just fix the code. Here the fix, if can be useful for someone:

I have changed the way to retrieve the taxonomy like this:
`rwmb_meta($field['id'])`

and I add the **name attribute** (I think metabox retrieve the value by this attribute ).

`name='" . $field["id"] ."'`

I have tried to extend other method but when I succeded to set **option value == {$option->name}** 
I can not retrieve the selected value with only the $option->name because I have not the meta_id anymore. This is line that fails:
`selected( in_array( $object->$id, $meta ), true, false ),`

**Comment by rilwis** [comment]
Hi,

To make the `in_array` code work, you need to add `multiple` to the `<select>` tag. Also, make sure which kind of data you want to save in the DB, term ID or term name.
