### ISSUE TITLE
Custom content

### ISSUE THREAD

**Issue by aientrp** [wpmetabox/meta-box#1237]
Hi,

I have an idea to add a customizable content field (eg news feed), where visitor can specify what type of news he wants to see constantly (eg sportnews, science and economics). The choice should be stored in cookies so next time visitor coold see the same feed.
Can I realize this with your plugin?

Thanks.

**Comment by rilwis** [comment]
Hello,

This is possible with a custom field type, where you specify the type of news and source. Then you decide to output it in the frontend. Please see [this docs](https://docs.metabox.io/custom-field-type/) on how to create a custom field type.
