### ISSUE TITLE
Missing size parameter in wp_get_attachment_image_srcset

### ISSUE THREAD

**Issue by Giacomo92** [wpmetabox/meta-box#1239]
Testing `rwmb_meta` function I see on the line below that are missing a parameter in `wp_get_attachment_image_srcset` function so the srcset returned is not filtered.

https://github.com/wpmetabox/meta-box/blob/2e7daf5dc30496b9dd3293dbdfa30f611bc362f5/inc/fields/image.php#L125

I think it would be better like this
```
$info['srcset'] = wp_get_attachment_image_srcset( $file, $args['size']  );
```

The same approach of this line

https://github.com/wpmetabox/meta-box/blob/2e7daf5dc30496b9dd3293dbdfa30f611bc362f5/inc/fields/image.php#L111

**Comment by rilwis** [comment]
I've just added the param. Thanks a lot for your help!
