### ISSUE TITLE
MB for Yoast SEO creating JS errors in admin area

### ISSUE THREAD

**Issue by wgstjf** [wpmetabox/meta-box#1240]
## Issue Overview

We have a large number of MB fields some of which are cloneable groups of fields.  Some of the fields have a value of 'true' for 'add_to_wpseo_analysis'.  When the page loads we get an uncaught JS error:

![image](https://user-images.githubusercontent.com/3740694/40504146-51c9eae6-5f88-11e8-84cc-65179d6b1ff0.png)

The error is being generated by the MB Yoast SEO plugin script, specifically line 49

```
// Listen to field change and update Yoast SEO analyzer.
listenToField: function( fieldId ) {
	if ( isEditor( fieldId ) ) {
		tinymce.get( fieldId ).on( 'keyup', module.update );
	} else {
	document.getElementById( fieldId ).addEventListener( 'keyup', module.update ); //this line
	}
},
```

I am wondering whether the issue is coming from one or more of the following:

1. The fact that we have cloneable fields or groups of cloneable fields
2. That some of the cloneable groups contain wysiwyg editors
3. That we have conditional logic working to show/hide fields
4. Whether the script is for some reason looping through more than just form fields

MB Updater is installed and as such I can confirm I have up-to-date versions of all MB plugins.

Any help greatly appreciated as always.

Cheers,

Will

**Comment by rilwis** [comment]
Hi Will, let me check the plugin and will get back to you soon.

**Comment by rilwis** [comment]
Hi Will, can you check the fix at https://github.com/wpmetabox/mb-yoast-seo/commit/975455b930572b6754f1bc59551baaa964acd211?

(Download the .zip file here https://github.com/wpmetabox/mb-yoast-seo/archive/fix-js-error.zip)
