### ISSUE TITLE
taxonomy_advanced needs option for link to "+ Add New Term"

### ISSUE THREAD

**Issue by claytoncollie** [wpmetabox/meta-box#1241]
When using the `taxonomy_advanced` field, I would like to have the same functionality as the default taxonomy term metabox to add a new term on the fly. My specific use case is for a law firm website. I have a repeatable group of 4 fields, 3 select fields populated by taxonomy terms and finally a text field. I would like to add a new school to the taxonomy without jumping to the edit term page then coming back into the post edit screen. You might be able to use the existing WP JS functionality if the field has a unique ID.

![image](https://user-images.githubusercontent.com/4236538/41421736-0a301e68-6fbd-11e8-8674-bba2fb8413a2.png)

**Comment by rilwis** [comment]
Hi @claytoncollie,

Was this feature created by CMB2? Do you have a sample code for CMB2 to do that?

**Comment by claytoncollie** [comment]
No this is not available on CMB2. This is just a screenshot mockup.

I was looking into the default functionality for the taxonomy metaboxes and it looks like the JS targets the ID of the default category/taxonomy/tag metaboxes.  

The link is built at wp-admin/includes/meta-boxes.php at line 548

The JS used to add a term on the fly is in wp-admin/js/post.js at line 550

Like I said, the JS targets the ID of the metabox. 

Probably needs to be refactored for this use case. 

Wish I could help more :(

**Comment by rilwis** [comment]
Thanks a lot for the details @claytoncollie . I thought it's in CMB2 so I can learn from it. Anyway, I'll try to code that myself.

**Comment by Giacomo92** [comment]
Hi I have already coded this feature extending the taxonomy field. Here the code:
```if ( class_exists( 'RWMB_Field' ) ) {
    class RWMB_Oa_Taxonomy_Advanced_Field extends RWMB_Field {
		public static function html( $meta, $field ) {

			$options = get_terms($field['taxonomy'],array( "hide_empty" => 0 ));
			//Select
			$output = "<select id='" . $field["id"] ."' name='" . $field["id"] ."' class='rwmb-taxonomy_advanced rwmb-select_advanced select2-hidden-accessible'>";
			$output .= '<option value="">Seleziona ' . $field["name"] .'</option>';
			foreach ($options as $option){
				$selected = "";
				if($option->name == $meta){
					$selected = "selected";
				}

				$output .= sprintf(
					'<option value="%s" %s>%s</option>',
					esc_attr( $option->name ),
					$selected,
					esc_attr( $option->name )
				);
			}
			$output .= "</select>";
			//Tooltip
			if($field['tax_info']){
				$tax_type = $field['taxonomy'];
				$url = admin_url( 'edit-tags.php?taxonomy=' . $tax_type .'&post_type=listings', 'https' );
				$output .= '<a href="' . $url . '" class="oa-link-tax" target="_blank" alt="Aggiungi una Taxonomy">
								<i class="fa fa-plus-square"></i>
							</a>';
			}
			return $output;
		}

	}
}

```
I hope this can help you @claytoncollie. I can make a pull request if you want @rilwis

**Comment by rilwis** [comment]
@Giacomo92 Does it add new term via ajax?

**Comment by Giacomo92** [comment]
Nope @rilwis it's just a "shortcode" to the right taxonomy page. When I extend this field, I also think to add a modal with the taxonomy field and save them via ajax but in the end I created only a link to speed up the add process because:
- That form is already existing on the taxonomy page;
- I do not know what type of metabox component I have to display for a certain taxonomy's field;
- I have to reproduce too many fields in a small place (I have many custom fields)

**Comment by rilwis** [comment]
I got it. Thanks a lot @Giacomo92 !

**Comment by claytoncollie** [comment]
@Giacomo92 Thanks for sharing!

@rilwis Adding via ajax through a text link to closely mimick WP default functionality would be ideal, but hey, it's your code. I could see adding an icon could be confusing if the user is already used to clicking a + Add Term link. BUT if it was an icon, I would suggest a dashicon as they already enqueued by default.  My main pain point is jumping from screen to screen. The sites I would like to use this on are large and it takes a massive amount of time to fill out a single profile. Adding terms on the fly via ajax seems like the best way to go versus a modal or jumping to the term edit screen.

**Comment by rilwis** [comment]
@claytoncollie I did some coding, but had some troubles. Then I paused it for a while to fix other bugs. I'll be back on that soon.

PS: Thanks a lot for your support!

**Comment by davidatkadpro** [comment]
I should spend more time on Github lol was just going to write this request in the FB group.

Yes, something, as shown above, would be brilliant, a link/button that pops up a modal to add the term title.

And to give it even more swag, to add the slug, description and meta boxes would be really cool.
 
![mb term modal](https://user-images.githubusercontent.com/18738015/44181275-4eff4380-a144-11e8-8696-d960be9de1c2.jpg)
<img width="209" alt="mb term modal options" src="https://user-images.githubusercontent.com/18738015/44181280-57577e80-a144-11e8-9eab-bf5d55d7138f.PNG">
<img width="202" alt="mb term" src="https://user-images.githubusercontent.com/18738015/44181297-663e3100-a144-11e8-8e2b-b737b119c7b1.PNG">

**Comment by claytoncollie** [comment]
@rilwis bump...hope you have time to work on this in between WP 5.0 improvements. much appreciated!

**Comment by rilwis** [comment]
Just a late note that it's done in 1c58d9c452eed426a21c33705a28b5eaf379f25c

**Comment by claytoncollie** [comment]
@rilwis should this be working inside a Group field? 

I tested on a `select_advanced` field inside a group field and outside a group field. I added the truthy flag `add_new` to my field and see the "Add New" label. When I click on that link, it shows the text field but nothing else. 

Should there be a button to trigger the ajax? 

Hitting enter tries to publish the post.

**Comment by rilwis** [comment]
@claytoncollie No, it doesn't work inside a group. I made it a normal input, not ajax since using ajax requires updating the select/select_advance/radio/checkbox_list of terms. It works as an individual field only.
