### ISSUE TITLE
FEATURE REQUEST: "Post field" combo selector (Meta Box Builder)

### ISSUE THREAD

**Issue by parityhero** [wpmetabox/meta-box#1242]
Can we add the ability for the "Post" field dropdown to list both pages and posts. 

The user wants to sometimes be able to select blog posts to display, and other times link to more standard pages...I've added 2 "Post" fields as a workaround so if the page one is empty, it will pull the information from the post one.

Would be awesome if we could let them select a page or post from the one dropdown!

![image](https://user-images.githubusercontent.com/9137721/41555400-f8ded132-730d-11e8-9535-e05cde586cfe.png)

**Comment by rilwis** [comment]
This feature is done and will be released in the next version of the [Builder](https://metabox.io/plugins/meta-box-builder/)!
