### ISSUE TITLE
Returning Meta Box data without RWMB_Core::get_meta_boxes()

### ISSUE THREAD

**Issue by wenis** [wpmetabox/meta-box#1243]
Hi!

I am struggling to figure out how to get details of a meta box since RWMB_Core::get_meta_boxes() has been deprecated.

The theme I am extending used to have an old version (4.8.7) of Meta Box bundled and my code worked just fine.  Now that the theme author has updated the Meta Box version, RWMB_Core::get_meta_boxes() is no longer returning any data.

The theme uses Meta Box on a custom post type and there are several fields added.  What I had been doing was iterating over the list of Meta Box fields in order to create options with the Titan Framework.

I hooked into the options page like so:

```
// Hook earlier than createOptionsPage in the loader so meta_fields exist

add_action( 'tf_create_options', array( $this, 'hashFields' ), 5 );
```

And my function updated a class array called "meta_fields"...

```
public function hashFields()
{
    if ( ! class_exists( 'RW_Meta_Box' ) ) {
        return;
    }
    $meta_boxes = RWMB_Core::get_meta_boxes();

    foreach ( $meta_boxes as $meta_box ) {
        $meta_box = RW_Meta_Box::normalize( $meta_box );
        if ( ! in_array( 'property', $meta_box['post_types'] ) ) {
            continue;
        }
        foreach ( $meta_box['fields'] as $field ) {
            if ( ! empty( $field['id'] ) ) {
                array_push( $this->meta_fields,
                    array(
                        'id'    => $field['id'],
                        'name'  => isset( $field['name'] ) ? $field['name'] : '',
                ) );
            }
        }
    }
}
```

This was working just fine so I could iterate over $this->meta_fields when creating the options page:

```
foreach ( $this->meta_fields as $field ) {
    $mappingTab->createOption( array(
        'name'      => $field['id'],
        'id'        => $field['id'],
        'type'      => 'select',
        'desc'      => isset( $field['name'] ) ? $field['name'] : '',
        'options'   => $opts,
    ));
    $mappingTab->createOption( array(
        'name'  => 'Default Value',
        'id'    => "{$field['id']}_default_value",
        'type'  => 'text',
        'desc'  => 'Enter a default value for "Set as Default"',
    ));
    $mappingTab->createOption( array(
        'name'  => 'Set as Default',
        'id'    => "{$field['id']}_use_default",
        'type'  => 'checkbox',

    ));
    $mappingTab->createOption( array(
        'name'      => 'Do Not Map',
        'id'        => "{$field['id']}_no_map",
        'type'      => 'checkbox',
        'default'   => true,

    ));
    $mappingTab->createOption( array(
        'id'    => "{$field['id']}_heading",
        'type'  => 'heading',
    ) );
}
```

Now, the data is not populating so my mapping options do not appear on the page.

When I dump version 4.8.7 of Meta Box back into the theme plugin my code works just fine but it breaks some other things in the theme.

If I add a filter in my hooks like this:

`add_filter( 'rwmb_meta_boxes', array( $this, 'hashFields' ), 20 )`

And update my function following the new documentation like so:

```
public function hasFields( $meta_boxes )
{
    if ( ! class_exists( 'RW_Meta_Box' ) ) {
        return;
    }
    foreach ( $meta_boxes as $meta_box ) {
        if ( 'property-meta-box' != $meta_box['id'] )  {
            continue;
        }
        foreach ( $meta_box['fields'] as $field ) {
            if ( ! empty( $field['id'] ) ) {
                array_push( $this->meta_fields,
                    array(
                        'id'    => $field['id'],
                        'name'  => isset( $field['name'] ) ? $field['name'] : '',
                ) );
            }
        }
    }
}
```

If I exit/var_dump in that function I can see the data in an array as expected, but it looks like Meta Box isn't available when the Titan Framework creates the options page so my mappings/options are not created.

I'm sure rookie mistakes are being made here as I'm new to WordPress development.

Is there another way to get all the field information/schema from a Meta Box so I can iterate over it?  This seems like an awful lot of code/work to do something seemingly simple.

Thank you for the help.

**Comment by rilwis** [comment]
Hi, you can get the info about meta boxes using the [Meta Box registry](https://github.com/wpmetabox/meta-box/blob/master/inc/meta-box-registry.php).

```php
$meta_box_objects = rwmb_get_registry( 'meta-box' )->all();

// Now you can loop through these objects and get the meta box settings.

// To get array of meta box settings like before, use this:
$meta_boxes = array();
foreach ( $meta_box_objects as $meta_box_object ) {
     $meta_boxes[] = $meta_box_object->meta_box;
}
```

**Comment by wenis** [comment]
Thank you very much for the quick reply.

This was actually the first place I checked, however, I'm probably doing something wrong because when I try to grab the registry I find nothing...

```
$meta_box_objects = rwmb_get_registry('meta-box')->all();
exit(var_dump($meta_box_objects));
```
returns:

`array(0) { }`

Maybe the meta boxes aren't loaded yet?

Also, maybe how the meta boxes are defined?  This is the code I have extended...

```
add_filter( 'rwmb_meta_boxes', 'register_metaboxes' );

if( !function_exists( 'register_metaboxes' ) ) {
    function register_metaboxes() {

        if (!class_exists('RW_Meta_Box')) {
            return;
        }

        global $meta_boxes, $wpdb;

        $meta_boxes[] = array(
            'id' => 'property-meta-box',
...
```
Note the use of globals.  Should $meta_boxes be passed in my function like: 

`function register_metaboxes($meta_boxes)`

?

Thanks again.

**Comment by rilwis** [comment]
Oh, your code to register meta boxes seems too old. We have changed the syntax since version 4.8. No more checking for class_exists and no more using global variable. Please follow [this docs](https://docs.metabox.io/creating-meta-boxes/) for that.

**Comment by wenis** [comment]
Ok.  I'm still struggling and appreciate your help.

I have updated my syntax to register meta boxes so its in line with the documentation.  Its works and I can see the meta boxes for my custom post type.

However, I still cannot figure out why nothing is appearing for rwmb_get_registry, or whats going on when trying to populate data from meta boxes into my options class property (called meta_fields).

This is what I'm doing:

When the options class initializes this fires:

```
	public function addHooks()
	{
		add_filter('rwmb_meta_boxes', array( $this, 'setMetaFields'), 20 );
		// Hook earlier than createOptionsPage in the loader so meta_fields exist
		//add_action( 'tf_create_options', array( $this, 'hashFields' ), 5 );
	}
```

The purpose of that filter is to try and set the meta_fields property of the options class:

```
	public function setMetaFields( $meta_boxes )
	{
		foreach ( $meta_boxes as $meta_box ) {
			if ( 'property-meta-box' != $meta_box['id'] )  {
				continue;
			}
			foreach ( $meta_box['fields'] as $field ) {
				if ( ! empty( $field['id'] ) ) {
					array_push( $this->meta_fields,
						array(
							'id' 	=> $field['id'],
							'name'	=> isset( $field['name'] ) ? $field['name'] : '',
					) );
				}
			}
		}
		return $meta_boxes;
	}
```
If I exit(var_dump($this->meta_fields)) from within the setMetaFields function the data is there as expected.

However, outside of this function, if I were to put an exit(var_dump($this->meta_fields)) immediately following the add_filter then the data is not there.

I have also tried hooking to rwmb_meta_boxes from my original tf_create_options hook / 'hashFields' function.  That doesn't work either.  Same thing.

What am I doing wrong here?

**Comment by rilwis** [comment]
It might relate to *when* you run the filter. When do you run `addHooks`?

Ideally, the code to add filter to `rwmb_meta_boxes` should be put right in the `functions.php` file, or in your plugin file. Do not put it inside any condition (like `is_admin()`) or any other hook (like `init` or `admin_init`). Only then you can get it with the `rwmb_get_registry`.

**Comment by wenis** [comment]
It has to be related to loading order.

Even when I put this code in my main plugin file as the very first line:

```
$meta_boxes = rwmb_get_registry('meta-box')->all();
exit(var_dump($meta_boxes));
```

Nothing is returned.

The theme I am extending creates the meta boxes.  My plugin just tries to read them so I can build a mapping table (middle ware) between the meta-box and a database table.

The purpose of the addHooks function in my classes is to hook to wordpress add_filter or add_action.  Its fired from the class constructor.  All my hooks go here.

I did figure out a very dirty workaround, which I am embarrassed by because honestly I have no idea why this works.  I'll post it here in case it helps someone else.

I'm hooking to the titan framework _before_ the options page is created so I can populate the meta box fields.

```
	public function addHooks()
	{
		// Hook earlier than createOptionsPage in the loader so meta_fields exist
		add_action( 'tf_create_options', array( $this, 'hashFields' ), 5 );
	}
```

I had to use apply_filters with a closure that just returns the $meta_boxes.  It returns an array with a bunch of stuff in it, so I just filter it out.

```
public function hashFields()
{
	$meta_boxes = apply_filters('rwmb_meta_boxes', array(function($meta_boxes){return $meta_boxes;}), 20);
	foreach ($meta_boxes as $meta_box) {
		if ( ! is_array($meta_box) || ! array_key_exists('id', $meta_box) || 'property-meta-box' != $meta_box['id'] )  {
			continue;
		}
		foreach ( $meta_box['fields'] as $field ) {
			if ( ! empty( $field['id'] ) ) {
				array_push( $this->meta_fields,
					array(
						'id' 	=> $field['id'],
						'name'	=> isset( $field['name'] ) ? $field['name'] : '',
				) );
			}
		}
	}
}

```

Anyway.  I very much appreciate your help.  I'm not satisfied by how crappy this code is, but I've spent so long on this I need to move on.  If anyone else figures this out, please let me know so I can do this in a more elegant way.

Thanks again.

**Comment by rilwis** [comment]
Hey @wenis, glad that you figured a solution. It's not really good, but at least, it works. I don't use Titan framework, so I'm not sure how it fires its actions or something related. But I think you can take a look at the [MB Settings Page](https://metabox.io/plugins/mb-settings-page/) extension. It allows you to create theme options page with all the features for custom fields using the same syntax.

I'll close this issue for now. If you need any help, please just re-open it.

**Comment by wenis** [comment]
Alright...  The good news is I'm learning, but, unfortunately that "apply_filters" work around crashes Wordpress.

I did fix this and thought I'd come back and post about it in case someone using the google is in a situation where they need to create options pages from meta box data using the titan framework.

Using the excellent "Query Monitor" plugin, I was able to see the order in which actions where firing.

Meta boxes hooks in 'init' at priority 20 in RWMB_Core.



```
// Uses priority 20 to support custom post types registered using the default priority.
add_action( 'init', array( $this, 'register_meta_boxes' ), 20 );

```

The titan framework was hooking at 'init' with priority 1 in the main plugin file 'titan-framework.php'.

```
// Create the options.

add_action( 'init', array( $this, 'trigger_option_creation' ), 1 );
```

I just pushed the priority back to 100 for titan and viola...  Now I am able to populate my meta data prior to options being created.

like this:

```
	public function setMetaFields()
	{
		$meta_box_objects = rwmb_get_registry('meta_box')->all();
		$meta_boxes = array();
		foreach ($meta_box_objects as $meta_box_object) {
			$meta_boxes[] = $meta_box_object->meta_box;
		}
		foreach ($meta_boxes as $meta_box) {
			if ( ! is_array($meta_box) || ! array_key_exists('id', $meta_box) || 'property-meta-box' != $meta_box['id'] )  {
				continue;
			}
			foreach ( $meta_box['fields'] as $field ) {
				if ( ! empty( $field['id'] ) ) {
					array_push( $this->meta_fields,
						array(
							'id' 	=> $field['id'],
							'name'	=> isset( $field['name'] ) ? $field['name'] : '',
					) );
				}
			}
		}
	}

```

Thanks again for the support.  Seeing as the titan framework has been abandoned I will check out your extensions for my next project.
