### ISSUE TITLE
MB Settings Page - Programatically modify field value

### ISSUE THREAD

**Issue by wgstjf** [wpmetabox/meta-box#1245]
Hi guys,

Bit of a tricky one here...I need to be able to update a field value, set using MB Settings Page, via a function.

The field in question is a 'Next Available Membership Number' value and I need to be able to increment it by 1. 

The following code shows where I have got to so far the section where I need to add some code to update the 'member_number_next' value:

```php
#-----------------------------------------------------------------
# Check Member Number for possible duplicate and then update next member number
#-----------------------------------------------------------------

function indigo_increment_member_number($post_id, $post, $update) {
	global $post;

  $post_type = get_post_type($post_id);
  $next_member_number = indigo_get_next_member_number();
  
  if ( "member" != $post_type || true === $update ) return; // If this isn't a 'member' post or is an update, don't do anything.

	if ( isset( $_POST['member_number'] )) { 
    if ($_POST['member_number']<$next_member_number) { // If posted member_number is less than next_member_number then use next_member_number instead
      update_post_meta($post_id,'member_number',$next_member_number);      
    }
    
    #-----------------------------------------------------------------
    # *** NEED TO INCREMENT NUMBER HERE... ***
    # The field I need to update is shown below (member_number_next):
    # $indigo_membership_settings = get_option( 'indigo_membership_settings' );
    # $member_number_next = $indigo_membership_settings['member_number_next'];
    #-----------------------------------------------------------------

  }
}
add_action( 'save_post', 'indigo_member_update_users',10,3);
```

As always, any help greatly appreciated :-)

Cheers,

Will

**Comment by wgstjf** [comment]
Apologies - I've figured it out :-)

In case anyone else is looking for similar, this is what I've used:

```php
$next_member_number_incremented = $next_member_number + 1;
$rwmb_setting_method = new RWMB_Setting_Storage; // Obviously requires MB Settings Page to work!
$increment_next_member_number = $rwmb_setting_method->update('indigo_membership_settings','member_number_next',$next_member_number_incremented);
```

Cheers,

Will

**Comment by wgstjf** [comment]
Anh,

The above solution no longer works and has broken some functionality in a live site. :-(

Can you let me know the best way to update an MB Settings Page field value please and one that is not likely to be removed in a future version of the plugin?

I would appreciate it you could get back to me as soon as possible as we have at least one live client site with issues now.

Kind regards,

Will

**Comment by wgstjf** [comment]
Hi guys,

This problem has reared its head again.  Can you help asap as we have a live site experiencing issues.

Cheers,

Will

**Comment by rilwis** [comment]
Hi Will,

The new version of MB Settings Page switched to Composer, so the class name is changed.

You might want to update the class name to `MBSP\Storage`.

**Comment by wgstjf** [comment]
Worked perfectly.  Sorry for the late reply :-)
