### ISSUE TITLE
'type' => 'group', showing me only one field and do not show another one

### ISSUE THREAD

**Issue by Akrasnovskis** [wpmetabox/meta-box#1254]
Hi, I spend like a long day and I have no idea why I can't make it work, and what exactly I'm doing wrong.  I'm trying to create a group, that it can be cloned if necessary. The group need include just two fields, one for URL and another is the text for this URL. Below you can see entire meta box for the specific post type. 

The reason of the group, the client could have multiple buttons to be added to a page, sometimes is 1 URL and sometimes is 5, but each button needs to be specified, to avoid confusion. I thought that  "clone" feature is the best option, but even in below code I have two fields to be displayed, but only showing me one, even when I look through the backend code.

I was checking all documentation, but cannot find any of those examples that works.

Thanks in advance for any bits of advice.

A version of a plugin is 4.13.1

    $meta_boxes[] = array(
        'id'         => 'featured_publication',
        'title'      => 'Featured Publication',
		'desc' 				=> esc_html__( 'If you have more than one link, please use button to add more' ),
        'post_types' => 'publications',
        'context'    => 'normal',
        'priority'   => 'high',
        'fields' => array(
			array(
				'name'          	=> 'Background image',
				'id'            	=> 'featured_pub_bkg',
				'type'          	=> 'file_advanced',
				'force_delete'     	=> false,
				'max_file_uploads' 	=> 1,
				),
			array(
				'id'               => 'subheading',
				'name'         => 'Sub Heading',
				'type'           => 'text',
				'size'            => '100',
				),
			array(
				'id' 		=> $prefix . 'featured_links',
				'name'     => 'URL',
				'desc' 	=> esc_html__( 'If you have more than one link, please use button to add more' ),
				'type' => 'group',
				'clone' => true,
				'sort_clone' => true,
				'collapsible' =>  true,
				'save_state' =>  true,
				'fields'	=> array(
							array(
								'name' => 'URL Name',
								'id'   => 'featured_links_text',
								'type' => 'text',
								'clone' => false,
								'size' => '50',
							),
							array(
								'name' => 'URL Link',
								'id'   => 'featured_links_url',
								'type' => 'url',
								'clone' => false,
								'size' => '50',
							),
				),
			),
		),
				 
    );

**Comment by rilwis** [comment]
Hi,

Do you see it working in the backend? Does it return only 1 link in the frontend or the backend?

**Comment by Akrasnovskis** [comment]
Just one questions, is this functions required more expensive bundle with more extensions?

**Comment by rilwis** [comment]
Hi @Akrasnovskis ,

I've just tested your code and it works just fine for me. Here is the screenshot after saving the data:

![group](https://i.imgur.com/tDbRl6l.png)

Regarding the question: the Group extension is available for purchasing as [individual extension](https://metabox.io/plugins/meta-box-group/) or in [a bundle](https://metabox.io/pricing/). And it is not included in the Builder, you need to purchase the Group extension to make it work.

**Comment by Akrasnovskis** [comment]
Hello Rilwis,

Thanks you for clarifying that, now I understand why it no work, its because required extensions, I purchased developer version,so now seems like work so far :))) thanks
