### ISSUE TITLE
PHP Error Warnings

### ISSUE THREAD

**Issue by thefrosty** [wpmetabox/meta-box#1255]
Visit the Meta Box Template and click save (it helps to have Query Monitor installed). Notice the errors that are generated from the plugin.

Enter your example YAML data in the template, save and remove then re-save.

Screenshot:
<img width="1388" alt="screen_shot_2018-07-25_at_3_31_55_pm" src="https://user-images.githubusercontent.com/367897/43231272-83521084-9020-11e8-801f-7c7a17a69df9.png">

**Comment by rilwis** [comment]
Hi Austin,

Please check the YAML syntax, or post it here. There must be something wrong in the template that the YAML parser returns the wrong configuration array.
