### ISSUE TITLE
Metaboxes Locations Error in Gutnburg

### ISSUE THREAD

**Issue by themecatinfo** [wpmetabox/meta-box#1257]
Hi,
I have found some errors in developing my themes by adding compatible with WP Gutenberg. And error is that metabox contexts (locations ) not work with **form_top, after_title, before_permalink**

**Comment by rilwis** [comment]
Hi,

Actually this is not a bug. It's more like a bad behavior from Gutenberg. Gutenberg removes all the contexts from the screen, and allow us to use only the bottom section on the screen. So, no matter what context we set, meta boxes are always at the bottom.
