### ISSUE TITLE
oembed.php on line 94

### ISSUE THREAD

**Issue by ArtstudioWorks** [wpmetabox/meta-box#1260]
Hello,
Thank you for good job with metabox plugin. 
I want to report about issue /meta-box/inc/fields/oembed.php on line 94
Lower 5.4 PHP versions report bug **Parse error**: syntax error, unexpected ':'.
Can you change 
`$embed ?: $not_available;`
with
`$embed ? $embed : $not_available;`

**Comment by rilwis** [comment]
Thanks for reporting! I've just fixed it.
