### ISSUE TITLE
Add functions before submit

### ISSUE THREAD

**Issue by bowodesign** [wpmetabox/meta-box#1264]
Hi,

I want to ask something about meta box, is it possible to add some custom functions before process submitting, for example like this…

1. I create an input text box on the post
2. When I create a new post, I fill that text box with some value, for example, google.com
3. But then before the value saved I add base64 encoding
4. So when I display that value, the result would be Z29vZ2xlLmNvbQ==

I don’t want to encode the value when its display, for example, echo base64_encode(rwmb_meta( ‘input_id’ )); I want the encoding process happens when publish button pushed

Is it possible?

(I write this on wp plugin forum too, but I think better write in here)

**Comment by rilwis** [comment]
I'll closed this issue as it's answered on [wordpress.org forum](https://wordpress.org/support/topic/add-functions-before-submit/).
