### ISSUE TITLE
JS error while reordering image_advanced field images

### ISSUE THREAD

**Issue by m4v1** [wpmetabox/meta-box#1265]
## Issue Overview
In the Wordpress admin panel I'm getting a javascript error while reordering the images of an image_advanced field. The images are visually reordered but, after saving the post, they are back on the same position.

## Steps to Reproduce
I tried with and without other plugins installed.
Wordpress and meta-box plugin are both up to date (currently 4.9.8 and 4.15.4).
Maybe it's not relevant but the post is a custom post type.
Tested it on Chrome 68.0.3440.106 and Firefox 61.0.1.

While reordering images I get this error on js console:

`Uncaught TypeError: Cannot read property 'previousModels' of undefined at n.resetItemViews (media.js?ver=4.15.4:261)`

Debugging the js code I noticed that the "options" parameter passed to the resetItemViews() function is empty, and this is causing the error.

## Expected Behavior
The images are switched and saving the post keeps the new images order.

## Current Behavior
The images are visually switched, but after saving the post the position is reverted.

## Possible Solution
This seems like a Backbone.js related issue, the strange thing is that both backbone.js and the media.js file of metabox plugin are not updated since months, but I have this bug only since june/july 2018.

I am testing a workaround editing the resetItemViews() function, I will submit a pull request soon.

**Comment by rilwis** [comment]
Closed as fixed in #1266.
