### ISSUE TITLE
Online generator does not escape single quotes properly

### ISSUE THREAD

**Issue by rlafuente** [wpmetabox/meta-box#1271]
## Issue Overview

This happens in the Online Generator. If a field description contains single quotes, they are not escaped in the generated code, causing errors when pasting the code into functions.php.

## Steps to Reproduce (for bugs)

1. Open the Online Generator
2. Create a new field and input a Description which includes a single quote character (`'`)
3. The generated code contains the character as is, messing up the remaining code.

## Expected Behavior

The single quote character should be escaped in the generated code (`\'`).

## Current Behavior

The quote character is not escaped, which screws up the rest of the code (evident in the syntax highlighting). 

## Possible Solution

Scan the input strings and escape problematic characters accordingly.

**Comment by matchlessweb** [comment]
I knew I wasn't crazy! I used the online generator recently and the code that was spit out is throwing the following error:

**syntax error, unexpected 'Property' (T_STRING), expecting '('**

I believe the error code is specific to the very first line seen below, which might explain why even the formatting for embedding the code here seems off. I'm brand new to all things Meta Box and php. Could you help me understand what's  wrong with this generated code? 

**Inserted Code starts below here**

`function Matchless Property( $meta_boxes ) {
	$prefix = 'MW';

	$meta_boxes[] = array(
		'id' => 'mwlistingdetails',
		'title' => esc_html__( 'MW Listing Details', 'matchless-property' ),
		'post_types' => array( 'post' ),
		'context' => 'normal',
		'priority' => 'default',
		'autosave' => true,
		'fields' => array(
			array(
				'id' => $prefix . 'tagline',
				'type' => 'text',
				'name' => esc_html__( 'Tagline', 'matchless-property' ),
				'placeholder' => esc_html__( 'i.e. Awesome Hunting Land', 'matchless-property' ),
			),
			array(
				'id' => $prefix . 'address',
				'type' => 'text',
				'name' => esc_html__( 'Address', 'matchless-property' ),
				'placeholder' => esc_html__( 'i.e. 101 County Rd.', 'matchless-property' ),
			),
			array(
				'id' => $prefix . 'county',
				'name' => esc_html__( 'County', 'matchless-property' ),
				'type' => 'select',
				'placeholder' => esc_html__( 'Select an Item', 'matchless-property' ),
				'options' => array(
					'Adams' => 'Adams',
					'Alcorn' => 'Alcorn',
					'Amite' => 'Amite',
					'Attala' => 'Attala',
					'Benton' => 'Benton',
					'Bolivar' => 'Bolivar',
					'Calhoun' => 'Calhoun',
					'Chickasaw' => 'Chickasaw',
					'Chocktaw' => 'Chocktaw',
					'Claiborne' => 'Claiborne',
					'Clarke' => 'Clarke',
					'Clay' => 'Clay',
					'Coahoma' => 'Coahoma',
					'Copiah' => 'Copiah',
					'Covington' => 'Covington',
					'DeSoto' => 'DeC',
					'Forrest' => 'Forrest',
					'Franklin' => 'Franklin',
					'George' => 'George',
					'Greene' => 'Greene',
					'Grenada' => 'Grenada',
					'Hancock' => 'Hancock',
					'Harrison' => 'Harrison',
					'Hinds' => 'Hinds',
					'Holmes' => 'Holn',
					'Humphreys' => 'Humphreys',
					'Issaquena' => 'Issaquena',
					'Itawamba' => 'Itawan',
					'Jackson' => 'j',
					'Jasper' => 'Jac',
					'Jefferson' => 'Jefferson',
					'Jefferson Davis' => 'Jefferson',
					'Jones' => 'Jones',
					'Kemper' => 'Kemper',
					'Lafayette' => 'Lafayette',
					'Lamar' => 'Lamar',
					'Lauderdale' => 'Lauderdale',
					'Lawrence' => 'Lawrence',
					'Leake' => 'Leake',
					'Leflore' => 'Leflore',
					'Lincoln' => 'Lincoln',
					'Lowndes' => 'Lowndes',
					'Madison' => 'Madison',
					'Marion' => 'Marion',
					'Marshall' => 'Marshall',
					'Monroe' => 'Monroe',
					'Montgomery' => 'Montgomeru',
					'Neshoba' => 'Neshoba',
					'Newton' => 'Newton',
					'Oktibbeha' => 'Oktibbeha',
					'Panola' => 'Panola',
					'Pearl River' => 'Pearl',
					'Perry' => 'Perry',
					'Pike' => 'Pike',
					'Pontotoc' => 'Pontotoc',
					'Prentiss' => 'Prentiss',
					'Quitman' => 'Quitman',
					'Rankin' => 'Rankin',
					'Scott' => 'Scott',
					'Sharkey' => 'Sharkey',
					'Simpson' => 'Simpson',
					'Smith' => 'Smith',
					'Stone' => 'Stone',
					'Sunflower' => 'Sunflower',
					'Tallahatchie' => 'Tasll',
					'Tate' => 'Tate',
					'Tippah' => 'Tippah',
					'Tishomingo' => 'Tishi',
					'Tunica' => 'Tunica',
					'Union' => 'Tn',
					'Walthall' => 'Walthall',
					'Warren' => 'Warren',
					'Washington' => 'Washington',
					'Wayne' => 'Wayne',
					'Webster' => 'Webster',
					'Wilkinson' => 'Wilkinson',
					'Winston' => 'Winston',
					'Yalobusha' => 'Yalobusha',
					'Yazoo' => 'Yazoo',
				),
				'std' => 'Adams',
			),
			array(
				'id' => $prefix . 'price',
				'type' => 'text',
				'name' => esc_html__( 'Price', 'matchless-property' ),
				'placeholder' => esc_html__( 'i.e. $500,000', 'matchless-property' ),
			),
			array(
				'id' => $prefix . 'agent_1',
				'type' => 'text',
				'name' => esc_html__( 'Agent 1', 'matchless-property' ),
				'placeholder' => esc_html__( 'i.e. Cole DeLong', 'matchless-property' ),
			),
			array(
				'id' => $prefix . 'agent_1_phone',
				'type' => 'text',
				'name' => esc_html__( 'Agent 1 Phone', 'matchless-property' ),
				'placeholder' => esc_html__( 'i.e. (601) 555-555', 'matchless-property' ),
			),
			array(
				'id' => $prefix . 'agent_1_photo',
				'type' => 'file_input',
				'name' => esc_html__( 'Agent 1 Photo', 'matchless-property' ),
			),
			array(
				'id' => $prefix . 'agent_2',
				'type' => 'text',
				'name' => esc_html__( 'Agent 2', 'matchless-property' ),
				'placeholder' => esc_html__( 'i.e. John Doe', 'matchless-property' ),
			),
			array(
				'id' => $prefix . 'agent_2_phone',
				'type' => 'text',
				'name' => esc_html__( 'Agent 2 Phone', 'matchless-property' ),
				'placeholder' => esc_html__( '(601) 555-5555', 'matchless-property' ),
			),
			array(
				'id' => $prefix . 'agent_2_photo',
				'type' => 'file_input',
				'name' => esc_html__( 'Agent 2 Photo', 'matchless-property' ),
			),
			array(
				'id' => $prefix . 'status',
				'name' => esc_html__( 'Status', 'matchless-property' ),
				'type' => 'select',
				'placeholder' => esc_html__( 'Select an Item', 'matchless-property' ),
				'options' => array(
					'For Sale' => 'For Sale',
					'Pending' => 'Pending',
					'Leased' => 'Leased',
					'For Lease' => 'For Lease',
				),
				'std' => 'For Sale',
			),
			array(
				'id' => $prefix . 'google_map_upload',
				'type' => 'file_advanced',
				'name' => esc_html__( 'Google Map Upload', 'matchless-property' ),
				'max_file_uploads' => 1,
				'max_status' => true,
			),
			array(
				'id' => $prefix . 'topo_map_upload',
				'type' => 'file_advanced',
				'name' => esc_html__( 'Topo Map Upload', 'matchless-property' ),
				'max_file_uploads' => 1,
				'max_status' => true,
			),
			array(
				'id' => $prefix . 'aerial_map_upload',
				'type' => 'file_advanced',
				'name' => esc_html__( 'Aerial Map Upload', 'matchless-property' ),
				'max_file_uploads' => 1,
				'max_status' => true,
			),
		),
	);

	return $meta_boxes;
}
add_filter( 'rwmb_meta_boxes', 'Matchless Property' );`

I see your note regarding single quote character needing to be escaped, but I'm not sure if that's the issue at hand with my particular code here. Or is it? :/

**Comment by rlafuente** [comment]
I think the issue is not related -- from what I see, the problem with your code is having a space in the name of your function `Matchless Property`. Try removing it (e.g. `MatchlessProperty`) and see how it works.

Using a code checker like [this one](http://phpcodechecker.com/) is a quick way to try and debug issues like these.

**Comment by matchlessweb** [comment]
That instantly fixed it. When I ran the code through the linter it didn't indicate the specific issue with the syntax, so I felt lost. But that added space did seem to be the issue. I'm very grateful for your help!

**Comment by rilwis** [comment]
@rlafuente Thanks for your feedback. The issue is fixed.
