### ISSUE TITLE
Google Maps Api Key Issue

### ISSUE THREAD

**Issue by boethius** [wpmetabox/meta-box#1274]
## Issue Overview
The API calls in the admin section don't have a key, even though there are keys defined in both inc/fields/map.php, in the `geo` property, and as a filter.

```
 // Location
  $metaBoxes[] = array(
    'id'       => 'location',
    'title'    => 'Information',
    'pages'    => array('location'),
    'context'  => 'normal',
    'priority' => 'high',
    'geo.api_key' => 'AIza...',
    'geo' => array(
      'api_key'   =>'AIza...',
    ),
    'fields' => array(
      // array(
      //   'name' => 'Location', // Optional
      //   'id' => 'Location',
      //   'type' => 'group',
      //   'clone' => false,
      //   'fields' => array(
          array(
            'name' => 'Map',
            'id'   => 'map',
            'type' => 'map',
            'api_key'   => 'AIza...',
            'address_field' => 'address',
          ),
          array(
            'name' => 'Label (on map)',
            'id'   => 'label',
            'type' => 'text',
          ),
          array(...
```

and in `functions.php`

```
add_filter( 'gmap_api_params', function( $params ) {
    $params['key'] = 'AIza...';
    return $params;
});
```

## Expected Behavior
Google needs an Api Key, so it should be loaded in the url.

## Current Behavior
`<script type="text/javascript" charset="UTF-8" src="https://maps.googleapis.com/maps-api-v3/api/js/34/5/map.js"></script>`

Thanks for any help.

**Comment by rilwis** [comment]
Hi,

Looks like the URL `https://maps.googleapis.com/maps-api-v3/api/js/34/5/map.js` is the *rendered* URL, not the original URL that we enqueue in the plugin. The URL we enqueue is just `https://maps.google.com/maps/api/js?key=YOUR_API_KEY`. Google might redirects the enqueued URL to its final URL.

Anyway, if key does not present, then you'll got an error in the dev console of the browser. Please check that.
