### ISSUE TITLE
[BUG] MetaBox Builder - Text List Array to String

### ISSUE THREAD

**Issue by parityhero** [wpmetabox/meta-box#1275]
MetaBox: v4.15.5
Builder: v2.9.1

Creating a text list with a period (e.g. test@test.com) in the placeholder will cause an array to string conversion.

Also if you have a backslash in any of the fields, it generates this notice and the metabox will not appear at all on the page/post screen: 
Notice: unserialize(): Error at offset 334 of 421 bytes in /var/www/test.com/wp-content/plugins/meta-box-builder/inc/class-meta-box-builder.php on line 256

Post/Page Screen:
![textlist_with_period_placeholder2](https://user-images.githubusercontent.com/9137721/45766990-69c74b00-bc0f-11e8-969f-edfbbe9dd017.png)

Builder:
![textlist_with_period_placeholder](https://user-images.githubusercontent.com/9137721/45766991-69c74b00-bc0f-11e8-8257-e3c379f9d98f.png)

Code:

```php
add_filter( 'rwmb_meta_boxes', 'your_prefix_register_meta_boxes' );
function your_prefix_register_meta_boxes( $meta_boxes ) {
	$meta_boxes[] = array (
		'title' => 'test',
		'id' => 'test',
		'post_types' => array(
			'post',
		),
		'context' => 'normal',
		'priority' => 'high',
		'fields' => array(
			array (
				'id' => 'text_list_1',
				'type' => 'text_list',
				'name' => 'Text List Field',
				'options' => 
				array (
					'test' => 'test',
					'test2' => 'test2',
					'example' => 'example',
					'email' => 
					array (
						'com' => 'Email',
					),
					'exampl3' => 'exampl3',
				),
			),
		),
	);
	return $meta_boxes;
}
```

**Comment by rilwis** [comment]
I think using `.` makes the plugin think it's a [**dot notation**](https://docs.metabox.io/extensions/meta-box-builder/#dot-notation).

**Comment by parityhero** [comment]
Maybe we should only allow dot notation for keys/options, and ignore for placeholder values? Is that possible?

**Comment by rilwis** [comment]
This bug has been fixed in the latest version of the builder. Please update.
