### ISSUE TITLE
[BUG] jQuery events and clones not working

### ISSUE THREAD

**Issue by davidatkadpro** [wpmetabox/meta-box#1276]
I have come across behaviour of jQuery events asre not working on elements that have been cloned in the same session.
I have picked it up in a group of fields that can be cloned, and also cloneable fields. 

When targeting any of the cloned elements with jQuery and performing an event, say:
`jQuery('.container .rwmb-text-clone .text-field-class').keyup(function() {.... `
The original element works fine and if I save the fields and try after the reload all the clones works fine also, but none of the clones in the same session work.

I have been hunting through the DOM to seen any notible differances but thats kind of a long list.

**Comment by davidatkadpro** [comment]
I have found a way around as it seems to be a common problem with anything that has been added to the document after being loaded, I used a delegated event handler as per this:
jQuery('.container').on( 'click', '.text-field-class', function() {....

This seems to work as you are throwing the event back to the container and not the cloned element.

**Comment by rilwis** [comment]
Hi David,

The jQuery event doesn't work for **dynamic elements** which are added to the DOM tree after page loads. So your 2nd comment is right. You should use event delegation to target the container instead of the specific element.

This is not a bug, this is just how JavaScript event works.

**Comment by davidatkadpro** [comment]
Lol yeah think I had a moment, have done much JS and jQuery in a while and have got a bit rusty.
