### ISSUE TITLE
Get registered fields for $object_id

### ISSUE THREAD

**Issue by radeno** [wpmetabox/meta-box#1278]
## Issue Overview
There is missing template functions like getting returning all fields for $object_id.
Something like this https://github.com/AdvancedCustomFields/acf/blob/c8e181c848009aa9f6a3919ee19981fb2774f634/includes/api/api-template.php#L207

Is should increase easier support implementation into another plugins.

I try to extend Media Cleaner plugin to support MetaBox but getting fields of object is not in easy way.
I can get all registered metaboxes, but then it must be custom code.
```php
$meta_boxes = rwmb_get_registry( 'meta_box' );
$meta_boxes->get_by(['object_type' => 'post']);
```
So how to get fields by object_id and object_type?
Algoritm:
1. Getting all registered metaboxes by object type, like code before.
2. Filter all metabox by object_type
3. Get all fields from filtered metaboxes and remap to associative array
4. Get all post/term/user meta based on object type and object id
5. Append `value` key (maybe values?) to every field object?
6. Return associative array

Any better hint how to get registered fields with values for object ?

**Comment by rilwis** [comment]
Closed as PR #1280 is merged.
