### ISSUE TITLE
Programatically set the value of a field

### ISSUE THREAD

**Issue by diegusleik** [wpmetabox/meta-box#1282]
Hi.
I am trying to find the way to programatically set the value of a field.

In [this post](https://metabox.io/support/topic/programmatically-modify-field-value-prior-to-displaying-in-admin/) they show the way to do it by using a filter that "changes the value before showing to users".

But, I need to save the value (example: a product stock) not before showing to users but after a product sale is made.

So, is there a function - like _rwmb_meta_set( $field_id, $new_value)_ - that I can use?

Thanks in advance.

**Comment by rilwis** [comment]
Hi,

To set the value of a field, please use `update_post_meta` function:

`update_post_meta( $post_id, $field_id, $new_value );`

Please check the format of the `$new_value` [here](https://docs.metabox.io/database/).
