### ISSUE TITLE
Conditional Logic: Slow loading and response time of 'editor screen'

### ISSUE THREAD

**Issue by brett-ambr** [wpmetabox/meta-box#1284]
Hello!

I'm using the 'MetaBox Conditional Logic' plugin, as well as the 'Meta Box Group' plugin to create an editor that allows the user to pick certain layouts.

There are 8 layouts, and each has around 3-10 fields conditional to each layout, so maybe around 60-80 fields total.

There is a very slow load time (up to 10 - 15 seconds), this is only really noticeable once I put a decent amount of content in. The load time disappears when 'MetaBox Conditional Logic' plugin is turned off.

Also there is a very slow response time based of my interactions, such as selecting a field or clicking a radio button, takes from 5-15 seconds to select. This also disappears when the plugin is turned off.

Do you have any advice or workarounds for this kind of problem?  I cannot show it to the client until this is resolved. Please let me know. Thank you so much.

**Comment by rilwis** [comment]
Hi @brett-ambr ,

I answered your question in this issue https://github.com/wpmetabox/meta-box/issues/1195#issuecomment-432480274. Please take a look.

**Comment by rilwis** [comment]
Hi again,

I’ve made a significant improvement on checking the conditions, which (in my tests) increase the speed up to 4 times. Please update to version 1.6.0 and let me know how it works for you.

**Comment by rilwis** [comment]
PS: Let's close this issue and track the conversation on [support forum](https://metabox.io/support/topic/slow-loading-and-response-time-of-editor-screen/#post-11834).
