### ISSUE TITLE
Post field with select_advanced and multiple

### ISSUE THREAD

**Issue by stefanue** [wpmetabox/meta-box#1285]
## Issue Overview
When using post field with multiple set to true, rwmb_meta function returns single result instead of array.

```
array(
    'name'  => 'Select a Case Studies',
    'id'    => "{$prefix}case_studies",
    'type'  => 'post',
    'post_type' => 'case-studies',
    'field_type'  => 'select_advanced',
    'multiple' => true,
    'placeholder' => 'Select Case Studies',
    'query_args'  => array(
        'post_status'    => 'publish',
        'posts_per_page' => - 1,
    ),
),

```
## Steps to Reproduce 

```
$case_studies = rwmb_meta('WDC_case_studies');
var_dump($case_studies);
```

returns:

`string(4) "3346"`

## Works when using WP function to retrieve  post meta

```
$case_studies = get_post_meta(get_the_id(), 'WDC_case_studies', false);
var_dump($case_studies);
```

returns:
```
array(3) { 
    [0]=> string(4) "3346" 
    [1]=> string(4) "2337" 
    [2]=> string(4) "2345" 
}
```

**Comment by Giacomo92** [comment]
I think it is a similar to  #1234.
Please check how you use the filter **rwmb_meta_boxes**. In my case it was only included in the admin area and 
**rwmb_meta()** function it only returned the current post id.
