### ISSUE TITLE
Conditional Logic JS error

### ISSUE THREAD

**Issue by wgstjf** [wpmetabox/meta-box#1290]
Hi guys,

Just updated to the latest version of Conditional Logic (v.1.6.2) and we are now getting the following JS error:

```
Uncaught TypeError: conditions.forEach is not a function
    at getWatchedElements (conditional-logic.js?ver=1.5:342)
    at init (conditional-logic.js?ver=1.5:521)
    at conditional-logic.js?ver=1.5:528
    at dispatch (load-scripts.php?c=1…e,utils&ver=4.9.8:3)
    at r.handle (load-scripts.php?c=1…e,utils&ver=4.9.8:3)
```
MB version 4.15.7 is also installed.

Rather critical we get this working asap so would love your thoughts as soon as possible.

Cheers,

Will

**Comment by wgstjf** [comment]
No improvement unfortunately :-(

Any other thoughts?

Cheers,

Will

**Comment by rilwis** [comment]
Hi Will,

I've just fixed the bug and released new version. Please update!

**Comment by wgstjf** [comment]
Works perfectly, thanks :-)
