### ISSUE TITLE
text_list doesn't behave as expected when clone = false

### ISSUE THREAD

**Issue by bynicolas** [wpmetabox/meta-box#1292]
## Issue Overview
When using text_list as a single unit (not cloning) I can only access the first option value saved in the database.

current metabox version is `4.15.7 `

## Steps to Reproduce (for bugs)
when defining the metabox field
```
...
[
  'name'        => 'Website',
    'id'          => $prefix . 'website',
    'type'        => 'text_list',
    'options' => [
      'Bob's site' => esc_html__( 'Site name', 'rwmb' ),
      'https://exemple.com' => esc_html__( 'URL', 'rwmb' )
     ]
],
...
```
## Expected Behavior

I expect to retrieve the value in an array as such 

```
$values = rwmb_meta( $field_id );
echo $values[0]; // Site name'
echo $values[1]; // URL
```

## Current Behavior

Currently, the only first option value is returned ( i.e. `Site name`) as a string

so if I do `echo $values[0];` I would get `B` as the first character in the string `Bob's site`

This looks like a bug as adding `'clone' => true` works as expected, it returns an array of arrays for each clone with `value[0]` being `Site name`and `value[1]` being `URL` for each clone saved.

**Comment by rilwis** [comment]
After this commit  2d1d7fb, I see the problem is fixed. Let me know if you still see it.
