### ISSUE TITLE
WYSIWYG and WordPress 5.0

### ISSUE THREAD

**Issue by fireform** [wpmetabox/meta-box#1293]
## Issue Overview
The problem appears in WordPress 5 only, so no problem in 4.9 and below. WYSIWYG field in "Visual" mode doesn't save value when block editor (Gutenberg) is active, but saving works when switch to "Text" mode. No problem if [Classic editor](https://wordpress.org/plugins/classic-editor/) plugin is enabled as well.

WordPress 5.0.

Meta box 4.15.7.

Extensions:

mb-term-meta v. 1.2.3
meta-box-conditional-logic v. 1.6.4
meta-box-group v. 1.2.17
meta-box-tabs v. 1.1.1

Gutenberg [causes some issues](http://take.ms/fJ2WQ) in Firefox's console, btw, so it may be a reason. Further info https://github.com/WordPress/gutenberg/issues/12655 But, in Chrome saving also not working ([console in Chrome](http://take.ms/NFNWF)).

## Steps to Reproduce (for bugs)

Example code:

```
'fields' => array(
	array(
		'name'				=> __( 'Description', 'textdomain' ),
		'id'    			=> '_wysiwyg',
		'type'  			=> 'wysiwyg',
		'desc'				=> __( 'Bla.', 'textdomain' ),
		'raw'				=> true,
		'options' 			=> array(
			'tinymce'			=> array(
				'plugins'			=> 'paste,wplink,wordpress,textcolor,colorpicker',
				'toolbar1' 			=> 'undo,redo,italic,link,unlink,bold,hilitecolor,forecolor,backcolor,alignleft,aligncenter,alignright',
				'toolbar2' 			=> '',
				'toolbar3' 			=> ''
			),
		),
	),
),
```

It's simple to reproduce: just save post and reload back end (because Gutenberg fires "save_post" via ajax). No need to check on the front end, using rwmb_meta().

**Comment by rilwis** [comment]
It's fixed in  dad4d0b . New version will be available today.
