### ISSUE TITLE
wysiwyg.js error

### ISSUE THREAD

**Issue by pipdig** [wpmetabox/meta-box#1294]
There seems to be a JS error in wysiwyg.js. Tested on both WP4 and 5 with Classic Editor - https://i.imgur.com/QcAJo5S.png

**Comment by rilwis** [comment]
Thanks! I'm checking it.

**Comment by rilwis** [comment]
Can you please check the fix?

**Comment by pipdig** [comment]
Hi @rilwis!

Unfortunately it did not solve the issue - https://i.imgur.com/qFlhSyp.png

I also just noticed that the error only occurs when Yoast is active. If you try activating Yoast you should see the same error at your end.

**Comment by rilwis** [comment]
I made a continue fix to this at https://github.com/wpmetabox/meta-box/commit/896011f5e941fc2285ab689d47a35e61ff321bc7. Can you try again with browser cache cleared?

**Comment by pipdig** [comment]
That fixed it! 👍
