### ISSUE TITLE
JS Error when settting slider min max using php variable

### ISSUE THREAD

**Issue by wgstjf** [wpmetabox/meta-box#1299]
Hi guys,

Struggling here... :-)

I need to be able to set a slider's min and max vars using php variables as below:

```php

$radius_min = 5;
$radius_max = 300;
$radius_default = 50;

// SLIDER - Radius
array(
  'name' => __( 'Radius', 'indigo-metaboxes' ),
  'id'   => $prefix . 'radius',
  'type' => 'slider',
	'suffix'	=> 'miles',
  'js_options' => array(
      'min'   => $radius_min, 
      'max'   => $radius_max,
      'step'  => 5,
  ),
  'std' => $radius_default,
  'columns'  => '4',
),
```

It all works fine if I replace the php vars with numbers, eg...

```php
// SLIDER - Radius
array(
  'name' => __( 'Radius', 'indigo-metaboxes' ),
  'id'   => $prefix . 'radius',
  'type' => 'slider',
	'suffix'	=> 'miles',
  'js_options' => array(
      'min'   => 5, 
      'max'   => 300,
      'step'  => 5,
  ),
  'std' => 50,
  'columns'  => '4',
),
```

The error I get in the console is "a.toFixed is not a function".  I assume this is something to do with the JS seeing a string not a number but I'm not sure how to fix.  Any help greatly appreciated as always.

Cheers,

Will

**Comment by rilwis** [comment]
Hi Will,

Can you make sure the variable is set and the value is number (not string) when passing to the field settings?

**Comment by rilwis** [comment]
Hi Will,

Glad you figured it out. The value for `max` and `min` must be integers. So, nice trick!

Regarding the range, unfortunately, it saves only the user's selected value. Maybe you can help me to make it work with 2 values ;)

**Comment by wgstjf** [comment]
Finishing up a number of projects at the moment so can't give this my full attention but initial thoughts (trying to keep it simple...) would be to pipe-separated the top and bottom values and is the 'range' option is set to true

```js
options.slide = function ( event, ui ) {
	if (options.range==true) {
		$input.val( ui.values[ 0 ] + "|" + ui.values[ 1 ] );
		$valueLabel.text( ui.values[ 0 ] + "|" + ui.values[ 1 ] );
	} else {
		$input.val( ui.value );
		$valueLabel.text( ui.value );
	}
};
```

You could then just split this in the html function...

What do you think?
