### ISSUE TITLE
Site meta support 

### ISSUE THREAD

**Issue by spacedmonkey** [wpmetabox/meta-box#1301]
In WordPress 5.1 multisite added support for site meta data. https://make.wordpress.org/core/2019/01/28/multisite-support-for-site-metadata-in-5-1/

Field manager should also support this meta type.

Any questions regarding this, I am one of the developers that worked on the core patch, so just message me.

**Comment by rilwis** [comment]
Hi @spacedmonkey ,

Thanks a lot for your info. I've just got the news this morning. I'll be working on that soon. Probably will need your help on some technical issues.

**Comment by rilwis** [comment]
This is available in the version 1.4.0 of the [MB Settings Page](https://metabox.io/plugins/mb-settings-page/).
