### ISSUE TITLE
Add custom field to standard metabox 'publish'

### ISSUE THREAD

**Issue by matteo030** [wpmetabox/meta-box#1302]
Hi, is it possible to add a meta-box field to an existing standard meta box like 'submitdiv'?

I tried following this tutorial https://docs.metabox.io/edit-meta-boxes/#main and this is the code i'm using: 

```
add_filter('rwmb_meta_boxes', 'register_checkbox_featured', 20);
function register_checkbox_featured($meta_boxes)
{
    foreach ($meta_boxes as $k => $meta_box) {

        if (isset($meta_box['id']) && 'submitdiv' == $meta_box['id']) {

            $meta_boxes[$k]['fields'][] = array(
                'name' => 'My Checkbox',
                'id' => 'my_checkbox',
                'type' => 'checkbox',
            );
        }
    }
    return $meta_boxes;

}
```
but it is not working because var_dump($meta_boxes) gives me an empty array.
If i just add a new meta-box everything works as expected.

**Comment by rilwis** [comment]
Unfortunately, it's not possible. You might need to hook to existing WP's action. Meta Box will always create a new meta box wrapper.
