### ISSUE TITLE
Hello I have  a question

### ISSUE THREAD

**Issue by firaztimur** [wpmetabox/meta-box#1303]
![4columns](https://user-images.githubusercontent.com/46876847/54127759-9d936880-441b-11e9-920e-3d2f3741614f.jpg)

I want to chekbox_list position the bulk
code:
array(
              'name' => esc_html__( 'Frontage', 'easy-real-estate' ),
              'id'      => 'Cephe_ozellikleri',
              'type'    => 'checkbox_list',
              'tab'     => 'details',
              'columns' => 12,
              'inline'     => 'true',
              // Options of checkboxes, in format 'value' => 'Label'
              'options' => array(
                'east'       => 'East',
                'north'      => 'North',
                'south'      => 'South',
                'west'       => 'West',

              ),
              // Display options in a single row?
              // 'inline' => true,
              // Display "Select All / None" button?
              'select_all_none' => true,

          ),

**Comment by rilwis** [comment]
I answered this somewhere (don't remember now). But posting the answer here for reference:

The only way to do this is via custom CSS. You need to enqueue your own CSS (or use `custom_html` field to write CSS directly) and set the CSS for it.
