### ISSUE TITLE
Taxonomy field is not saving it's value

### ISSUE THREAD

**Issue by stefanue** [wpmetabox/meta-box#1305]
## Issue Overview
Hi, i wanted to use the taxonomy field to be able to select terms from the custom taxonomy. The field is populated and the selected value stays selected after publish/update, but can't be accessed via `rwmb_meta()` function or the `get_post_meta()` function.

## Steps to Reproduce (for bugs)

This is the code I use:

`array(`
`    'name' => 'Gallery Type Tax',`
`    'id' => 'gallery_taxonomy_tax',`
`    'type' => 'taxonomy',`
`    'taxonomy' => 'platform_category',`
`    'field_type' => 'select_advanced',`
`);`

And to get it's value I use

`$gallery_taxonomy_tax = rwmb_meta('gallery_taxonomy_tax');`

This will return: `string(0) ""`

I also looked at the entire `post_meta` object and didn't found `gallery_taxonomy_tax` over there at all.

`$all_post_meta = get_post_meta(get_the_id());`
`echo '<pre>' . var_dump($all_post_meta) . '</pre>';`

If you change from ` 'type' => 'taxonomy'` to `'type' => 'taxonomy_advanced'` everything works just fine.

**Comment by rilwis** [comment]
@stefanue The `taxonomy` field does **not** save value in the post meta. It only [sets terms for posts](https://docs.metabox.io/fields/taxonomy/#data).

So, using `get_post_meta` won't work. If you use `rwmb_meta`, you'll get a list of terms. Not sure why it didn't work for you, maybe you call `rwmb_meta` when the meta boxes are not registered yet (they're registered at `init` hook with priority 20).
