### ISSUE TITLE
Do not cache Post and User query results

### ISSUE THREAD

**Issue by radeno** [wpmetabox/meta-box#1307]
## Issue Overview
Hi,
MetaBox results for association query for Post or User selecting is cached by default
https://github.com/wpmetabox/meta-box/search?q=wp_cache_set&unscoped_q=wp_cache_set

Because MetaBox don't use any hook to cleaning up. In Select box are displayed old results when new post or user is created, updated or removed.

I think this should be removed because boxes for post or user selecting are used only in admin interface. So it doesn't any performance impact to caching or not.

Most important is to have data as fresh as possible.
Database should be scaled and optimized, incorrect data not.

**Comment by radeno** [comment]
This commit makes huge regression https://github.com/wpmetabox/meta-box/commit/ea868625622b5dad607e8e4a1550a1cb9d6a0528

**Comment by rilwis** [comment]
There was a problem that made me implemented the caching solution: when you have a cloneable post field, then each clone will make a query to the database. So with a single post field that has 10 clones, there are 10 queries are made. With caching, the number of queries is only one.

Probably we need a way to clear cache instead of removing it.

**Comment by radeno** [comment]
Or make caching as optional. Caching is "second-class citizen". First class are "raw data". So maybe adding option to defining it as enabled or disabled.
And making some action hook to get cache key.

**Comment by rilwis** [comment]
The cache using `wp_cache_*` will return raw data unless you use a persistent caching mechanism like Memcached or Redis. If you don't, the cache data is stored only in the memory and will be refreshed after each request.

I think removing cache when a new post/term/user is added/updated is a good solution.

**Comment by radeno** [comment]
We are using Redis. And many performant sites uses Redis/Memcache. So persistent cache is very bad "bug"

**Comment by rilwis** [comment]
I see. Let me find a solution.

**Comment by rilwis** [comment]
@radeno Just pushed a fix for this.

WP has a mechanism to set the last changed when a post is modified (sadly it doesn't has for user, so I have to manual add that). The cache key is now depends on the last changed time. So it's always fresh.

I notice that WP uses the same technique for `get_terms`. So I just do the same.

One thing I found is WP doesn't removed the old cache. Not sure why. Probably cache plugins need to do that themselves.

Please try and let me know what you think.

**Comment by radeno** [comment]
Hi @rilwis 
i don't even known about  wp_cache_get_last_changed exist.
Based on documentation it should work. But i think only from version WP 5.0, which is totally fine for us, but i don't know about usage version combination of Metabox and WP.
- https://github.com/WordPress/WordPress/blob/3a772651488c87e96b9c6862e1c243dd5cb67dd3/wp-includes/default-filters.php#L102
- https://github.com/WordPress/WordPress/blob/8e9315f51e4dd60ee77ef7b2d4df0fe8327a9e3b/wp-includes/post.php#L6886

**Comment by radeno** [comment]
Do you plan add same cache mechanism for Taxonomy/Term field?

**Comment by rilwis** [comment]
Hi @radeno ,

The function `wp_cache_get_last_changed` is actually available from WP 4.7:

https://github.com/WordPress/WordPress/blob/master/wp-includes/functions.php#L6549

(The `wp_cache_get_last_changed` function probably is added later for shorter code).

Another note is that the last changed time is set in `clean_post_cache` function which is available since WP 2 and is called when a post is inserted or updated.

So, I think it's fine. I tested on WP 4.7 and WP 4.9 and didn't see a fatal error.

> Do you plan add same cache mechanism for Taxonomy/Term field?

WP already uses last changed time for caching with `get_terms` function:

https://github.com/WordPress/WordPress/blob/master/wp-includes/class-wp-term-query.php#L676

So it's automatically work when a term is added or changed.

**Comment by radeno** [comment]
@rilwis 
about availability of `wp_cache_get_last_changed` there are no doubts, but for persistent cache like Redis or Memcache it is meaningful only from 5.0 and up, because updating/clearing `last_change` is made by action when post is really changed.
https://github.com/WordPress/WordPress/blob/master/wp-includes/default-filters.php#L102 and alternatives `added/edited/deleted_term_meta` so as `XXX_comment_meta` because  `wp_cache_set_posts_last_changed` and other alternatives doesn't exists before version 5.0.

You are right about caching WP_Term_Query. It is just strange that Term, Comment and Network Query has it, but Post Query don't.

I think your commit will work really well. Any timeline to publish new version?

**Comment by rilwis** [comment]
@radeno 

The line you pointed is updating the last changed time when post meta is updated. Not when a new post is created or an existing post is updated.

That's done in the `clean_post_cache` function here:

https://github.com/WordPress/WordPress/blob/master/wp-includes/post.php#L6366

`clean_post_cache` is called in many places, for example here when a new post is created:

https://github.com/WordPress/WordPress/blob/master/wp-includes/post.php#L3834

I'll prepare for the new version now.

**Comment by radeno** [comment]
Oh, wordpress is big black box :)

Thank you for making it work!
