### ISSUE TITLE
Ideas on how best to extend the osm field to work with various tile providers

### ISSUE THREAD

**Issue by baden03** [wpmetabox/meta-box#1309]
Due to Google's mapping API changes, many seem to be switching over to open-source alternatives. The osm field uses Leaflet and Open Street Maps, which is wonderful, however the standard OSM tiles may not be ideal for some use cases.

I have successfully modified the osm field to accept some new attributes that allow the use of MapBox and Esri/ArcGIS by passing additional info in the osm field declaration:
```
'tile_server'   => 'https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={accessToken}',
'tile_id'       => 'mapbox.streets',
'attribution'   => 'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors, <a href="https://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery &copy; <a href="https://www.mapbox.com/">Mapbox</a>',
'access_token'  => 'your_mapbox_api_token',
```
You can check it out on my [meta-box/osm-map-tiles branch](https://github.com/baden03/meta-box/tree/osm-map-tiles)
This works quite well, however it seems it might not be flexible enough to deal with the many different tile servers out there.

Would it make more sense to simply include the [Leaflet Providers](https://github.com/leaflet-extras/leaflet-providers) extension? Seems an easy way to switch between [many map styles](http://leaflet-extras.github.io/leaflet-providers/preview/index.html).

Either way, extra info would still need to be passed to the map servers. And it's different depending on the provider.
MapBox is looking for:
```
id: '<insert map_ID here>',
accessToken: '<insert ACCESS_TOKEN here>'
```
While Geoportail France has a different way of asking the same thing:
```
variant: '<insert resource ID here>',
apikey: '<insert api key here>'
```
Any thoughts are greatly appreciated before I start going further down this path.

Standard OSM Map:
![osm](https://user-images.githubusercontent.com/835758/57468260-6955f000-7284-11e9-90be-4961fe98c6e7.png)

ERSI Map:
![ersi-png](https://user-images.githubusercontent.com/835758/57468278-707cfe00-7284-11e9-91f2-b334fcc665f1.png)

MapBox map:
![mapbox](https://user-images.githubusercontent.com/835758/57468294-77a40c00-7284-11e9-8ccd-dda2f1583779.png)

**Comment by baden03** [comment]
just decided to create my own _osm_advanced_ field type. Issue marked as resolved.

**Comment by rilwis** [comment]
Hi @baden03,

I've just looked at your code and it seems nice. I think the difference in the parameters required by tile servers can be done by passing an array to the field.

Can you share what you have done here and we'll continue to work on this?
