### ISSUE TITLE
OSM Nominatim > Address Details

### ISSUE THREAD

**Issue by baden03** [wpmetabox/meta-box#1310]
The osm map includes autocomplete/geosearch capabilities from nominatim. At the moment it's only returning the Address, Lat and Lng values. Enough to populate the address field and drop a marker on the map at the right spot. Great!

With a very simple modification, the nominatim can easily provide a breakdown of the address into elements using the [addressdetails parameter](https://nominatim.org/release-docs/latest/api/Details/#output-details). It would work like this:

in the osm.js > $address.autocomplete source request:
```
$.get( 'https://nominatim.openstreetmap.org/search', {
	format: 'json',
	q: request.term,
	countrycodes: that.$canvas.data( 'region' ),
	"accept-language": that.$canvas.data( 'language' ),
	addressdetails: 1, // this is what we are talking about
},
```
will now provide a break out of the address details like so:
```
address:
	city_district: "Hamburg-Mitte"
	country: "Deutschland"
	country_code: "de"
	house_number: "123"
	postcode: "20359"
	road: "Strawberry Fields"
	state: "Hamburg"
	suburb: "St. Pauli"
```
then the response would need to be expanded to include all these juicy new details:
```
response( results.map( function ( item ) {
	return {
		label: item.display_name,
		value: item.display_name,
		latitude: item.lat,
		longitude: item.lon,
		/* here go the rest of the address details */
		postcode: item.address.postcode,
};
```
And finally, these could be automatically bound to matching fields in the select function.

Yes, I know there is talk of an [OSM Geolocaiton Extension](https://metabox.io/support/topic/open-street-map-available-fields/) in the works, but in the meantime, this seems like a pretty simple update.

I am half-way done with this implementation, but wanted to post this idea and get some feedback before continuing.

Also because I need a break.
And a beer...
...or three.

**Comment by baden03** [comment]
Just a quick update on some issues with the address details provided by Nominatim. It seems the keys are [completely defined by Nominatim](https://github.com/openstreetmap/Nominatim/blob/1542a006cbb315812316e6788ad68f7f3010e557/lib/lib.php#L121), so it's not exactly reliable to map to standard address fields.  For example, to fill in a field called 'city' we'll need to check if Nominatim is calling the location a 'town' or a ''village'... 

Also, as shown in the example above for St. Pauli, Hamburg. Hamburg is both the City and the State, however the state address detail is simply not included.

**Comment by baden03** [comment]
After getting the GeocodeJSON version to work, I decided to not use Nominatim due to the large amount of documented issues with [address normalisation and address format](https://github.com/openstreetmap/Nominatim/issues/479).

Switched over to https://opencagedata.com/ and am very pleased with the results.
Issue marked as closed.

**Comment by rilwis** [comment]
Hi @baden03,

It's great that you have integrated with GeocodeJSON and OpenCage. Can you share what you have done here? It might help me to improve the plugin or others looking for solutions.

**Comment by baden03** [comment]
here you go:
https://github.com/baden03/meta-box/tree/osm-map-tiles

If you have specific questions, let me know.

**Comment by rilwis** [comment]
Thanks a lot, @baden03
