### ISSUE TITLE
Meta Boxes unresponsive

### ISSUE THREAD

**Issue by popepay** [wpmetabox/meta-box#1311]
## Issue Overview
Since a week or so, I cannot edit any pages in my website anymore.
All buttons are unresponsive. I suspect the Meta Box plugin to be the issue. 
See screenshot, while the website still works, no content is shown when editing. All the blue buttons redirect to the top of the page without allowing me to edit the meta boxes.
It worked fine last week (prior to update to wordpress 5.2 maybe?)

## Screenshots / Video
(see attached)

![image](https://user-images.githubusercontent.com/17018621/58289930-cbc2ec00-7d6c-11e9-9ffc-65bd3a576774.png)

**Comment by rilwis** [comment]
Looks like there's a Fatal error in PHP. Please enable the WP_DEBUG and see what's wrong.
