### ISSUE TITLE
POST VIEW COUNT IN THE POSTS ARCHIVE WIDGET

### ISSUE THREAD

**Issue by Micu22** [wpmetabox/meta-box#1314]
- I use the newest version of every plugin.

I need to make a post view count for my elementor post widget and post archive widget.
The Idea is simple, in the Meta line of Card layout of post widgets in elementor I want to be able to add a little eye icon, a number and “minuty” which is Polish for minutes.(screenshot 1)

I don’t really know how to use custom fields on posts, I have added one(screenshot 3), called it read-time and I’ve put numbers in it. But elementor doesn’t allow me to show it in front end, the post widget only accepts Author-meta, Date-meta, comments-meta and time-meta.(screenshot 2)
Could you help?

I need to know:
1. how to add metadata(metabox) which will contain data about the length of reading the post, if possible one that will automatically count the length based on article length
2. a way to display it in elementor post/archive widget

## Expected Behavior
Elementor widget showing a meta data in a meta line which was created with meta box plugin

## Possible Solution
The best way would be to make it automatic(the system knew how many minutes based on article length),but If the author of the post has to type the number of minutes it’s still okay.

## Screenshots / Video
![screenshot 3](https://user-images.githubusercontent.com/51614436/59191195-1c18b700-8b7f-11e9-986a-fff83cab6929.jpg)
![screenshot 2 ](https://user-images.githubusercontent.com/51614436/59191196-1c18b700-8b7f-11e9-8a1b-5aac3d721b14.jpg)
![screenshot 1](https://user-images.githubusercontent.com/51614436/59191197-1cb14d80-8b7f-11e9-8402-08e27bffa3ba.jpg)

**Comment by rilwis** [comment]
Hi @Micu22,

Meta Box can help you add custom fields to posts. And you can do that by following the guide [here](https://docs.metabox.io/quick-start/).

However, it's the Elementor limitation that it can't output custom fields in its layout. The layout in Elementor is fixed and can't be changed. You can select/show what it offers, no more.

**Comment by Micu22** [comment]
There has to be a way to modify elementor to be able to show it in the
widget.. people make plugins that enhance elementor so my question is how
to do it.

_____________
Michał Kuczek
534 288 597
bo, Pewnych rzeczy nie mamy czasu NIE robić!

**Comment by rilwis** [comment]
@Micu22 Please reach out to Elementor team for help for this.
