### ISSUE TITLE
date.js: rwmb is not defined

### ISSUE THREAD

**Issue by stekky81** [wpmetabox/meta-box#1332]
Date picker doesn't show up because of a javascript error: rwmb is not defined
The bug was also reported by another user here:
https://metabox.io/support/topic/rwmb-is-not-defined/
The solution is really simple:
in meta-box/inc/fields/datetime.php
on line 71, add 'rwmb' as wp_register_script dependency:
wp_register_script( 'rwmb-date', RWMB_JS_URL . 'date.js', array( 'jquery-ui-datepicker', 'underscore', 'rwmb' ), RWMB_VER, true );
Please fix this bug, I have to patch several sites at each plugin update :-(

**Comment by rilwis** [comment]
Hi @stekky81 ,

The `rwmb` variable is enqueued before date script in [meta-box.php](https://github.com/wpmetabox/meta-box/blob/master/inc/meta-box.php#L154). There might be another problem. Would you mind posing the code of your meta box?

**Comment by stekky81** [comment]
This is the code from one of our website
```php
add_filter( 'rwmb_meta_boxes', 'ws_register_meta_boxes' );

function ws_register_meta_boxes( $meta_boxes )
{
	$meta_boxes[] = array(
		'title'	=> 'Autori del servizio',
		'pages'	=> array( 'post' ),
		'fields' => array(
			array(
				'name' => 'Autori',
				'id' => 'ws_autori',
				'type' => 'text',
				'std' => 'Redazione',
			),
		)
	);

	$meta_boxes[] = array(
		'title'	=> 'Eventi',
		'pages'	=> array( 'post' ),
		'fields' => array(
			array(
				'name' => 'Inizio evento',
				'id' => 'ws_event_from',
				'type' => 'date',
				'js_options' => array(
					'dateFormat' => 'dd/mm/yy',
					'minDate' => '-1y',
					'maxDate' => '+2y'
				),
				'timestamp' => true,
			),
			array(
				'name' => 'Fine evento',
				'id' => 'ws_event_to',
				'type' => 'date',
				'js_options' => array(
					'dateFormat' => 'dd/mm/yy'
				),
				'timestamp' => true,
			),
		)
	);
	
	return $meta_boxes;
}
```
The problem occur in many of our websites, using different themes.

**Comment by stekky81** [comment]
Problem solved, it was related to a custom enqueue in the theme. Thanks for you help!

**Comment by rilwis** [comment]
Glad that you resolved the problem. Yes, `rwmb` should be a dependency for custom enqueues. I'll add it to the list of dependencies for other scripts as well.
