### ISSUE TITLE
How to Keep the Post Pending for Review ?

### ISSUE THREAD

**Issue by sbkalim** [wpmetabox/meta-box#1337]
I am new to Metabox. I was using it, I got it very useful and saved huge amount of time. Suddenly I got an issue that I cannot keep the post status Pending for Review instead of Publish Can anybody Help?

Thanks in advance
Saif 

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by rilwis** [comment]
Hi Saif, can you please provide more details on that? How did you register meta box? Do you use MB Frontend Submission?

**Comment by sbkalim** [comment]
Hi,
Thanks for your reply.
Just solved the issue.
Yes I am using MB Frontend Submission. After fixing that issue now I am getting one different problem. Just below the form, Its got a huge blank space. Can you help ?

https://bnbdealer.com/sell-a-bnb/

![Screenshot_2019-09-21 Sell A BNB](https://user-images.githubusercontent.com/12701349/65377426-c0e97b00-dcbc-11e9-94d1-3491824ffefe.png)

**Comment by rilwis** [comment]
It's probably the CSS issue with your theme. Please check that.
