### ISSUE TITLE
TGMPA can't activate metabox plugin, urgent!

### ISSUE THREAD

**Issue by Ninetheme** [wpmetabox/meta-box#1338]
Please check with tgmpa and resolve activation problem, also please disable after activation plugin re-direct.

**Comment by rilwis** [comment]
I've just tested and see Meta Box still can be activated. This is my video:

https://www.loom.com/share/0908e711948e473c82e3e1d60ca20ef6

Do you see it differently? Can you make a video?

**Comment by Ninetheme** [comment]
I will send you video but metabox not working after plugin update : https://d.pr/free/v/5UnwZQ

**Comment by rilwis** [comment]
So, it's not about Meta Box can't be activated. It's about it's not working, isn't it?

Anyway, I don't see the problem in your video. Can you please explain it a little bit?

**Comment by Ninetheme** [comment]
Hi again,

I think there are some issues that affect all the theme-selling authors and make us lose a lot of time with customers. 

1. Please turn off redirection to the metabox page after activation of the plug-in.

2. [https://d.pr/free/i/usAJSB] Please disable this notice, not need to see for free metabox plugin

Thank you!

**Comment by rilwis** [comment]
Hi @Ninetheme:

1. I'll check the installation with TGMPA and disable for that.
2. The message is available only when there's a premium extension installed. If only Meta Box is installed, there's no message. Besides, users can just close the message and it won't show when refreshing the page.

**Comment by Ninetheme** [comment]
Please disable metabox  activation key notices on the header and plugins area, I'm tired of explaining this to all my customers. You should move these warnings to the metabox menu, otherwise I will have to delete all of my templates.

**Comment by rilwis** [comment]
Hi @Ninetheme,

Please include the premium extensions into your themes directly, not using TGMPA. That way, the notices won't show anymore.

See this docs for how to do that:

https://docs.metabox.io/extensions/integration/#bundling-extensions
