### ISSUE TITLE
Textarea field doesn't save <iframe>

### ISSUE THREAD

**Issue by minimaluminium** [wpmetabox/meta-box#1340]
## Issue Overview

`textarea` field doesn't save `<iframe></iframe>` embed codes. For example, this setting is used for adding a video embed code.

```php
array(
    'name' => esc_html__( 'Video embed code', 'domain' ),
    'id' => "{$prefix}pf_video_data",
    'type' => 'textarea',
    'cols' => 20,
    'rows' => 4,
),
```

1. Plain text -> OK
2. `<div>Some text</div>` -> OK
3. `<iframe></iframe>` -> FAIL

It used to work, but suddenly stopped working.

WP: v5.2.3
MB: v5.2.1

**Comment by rilwis** [comment]
Please add: `'sanitize_callback' => 'none'` to the field settings.

For details, please see https://docs.metabox.io/sanitization/
