### ISSUE TITLE
WP5.3 image_advanced edit link (pencil icon) opening in _BLANK

### ISSUE THREAD

**Issue by SimonvanWijhe** [wpmetabox/meta-box#1351]
Hi guys,

I am experiencing the following problem since I updated Wordpress to 5.3

When clicking the pencil icon of the image_advanced field it doen not open in a modal as usual, but on a new page. There is a visible javascript error in the console. 

To reproduce this I did a clean install of Wordpress 5.3, theme twentytwenty and ONLY the metabox.io plugin. I created an image_advanced field and tried to edit an image. I recorded the issue and I did get an error in my  @console.

Any ideas on how to fix this?

![Screen-Recording-2020-01-10-at-15 35 23](https://user-images.githubusercontent.com/41121933/72164790-a26fd280-33c6-11ea-93f1-5136f5479636.gif)

**Comment by rilwis** [comment]
Hi @SimonvanWijhe ,

I see [your post](https://metabox.io/support/topic/wp5-3-admin-image-edit-link-pencil-icon-opening-in-_blank-instead-of-iframe/) in the support forum, so let's close this issue. We'll discuss there.

**Comment by SimonvanWijhe** [comment]
Thanks!
