### ISSUE TITLE
Hierarchical Taxonomy in Metabox Group (cloneable)

### ISSUE THREAD

**Issue by vinrgates** [wpmetabox/meta-box#1352]
Hello, Is it possible to get and display the value of taxonomy in the metabox group?

The reason put the taxonomy field in the metabox group is because I need to display the Text from the text field for each checked terms.

Please refer to the screenshot to get an easier understanding

Thank you
<img width="575" alt="Screen Shot" src="https://user-images.githubusercontent.com/30382350/72340919-6d3beb00-370c-11ea-832a-22ac4c1a0fa0.png">

**Comment by rilwis** [comment]
Please see [this docs](https://docs.metabox.io/displaying-fields/), and [docs for taxonomy field](https://docs.metabox.io/fields/taxonomy/).
