### ISSUE TITLE
MB Custom Post Types causing products to disappear from vendor store pages

### ISSUE THREAD

**Issue by sarahsampino** [wpmetabox/meta-box#1353]
Hi, I'm using the latest version of Meta Box and MB Custom Post Type.

## Issue Overview
After deactivating and re-activating all plugins, I've found that MB Custom Post Type is for some reason causing products to disappear from Vendor Store pages.

Here is a screenshot of the page with the plugin deactivated. Notice the thumbnail of the product at the bottom. On the left, none of my custom taxonomies appear in the filter search bar since the plugin is deactivated.
![Screen Shot 2020-01-20 at 12 32 11 AM](https://user-images.githubusercontent.com/55568990/72701288-cea0f700-3b1c-11ea-9c45-6e6d104c7662.png)

Here is a screenshot with the plugin activated. Notice the missing thumbnail with the words "No products were found matching your selection". On the left, my custom taxonomies appear.
![Screen Shot 2020-01-20 at 12 36 41 AM](https://user-images.githubusercontent.com/55568990/72701339-f55f2d80-3b1c-11ea-8b4d-63f86bac55fd.png)

Here is a link to this page, with the plugin de-activated: http://box5143.temp.domains/~audiobq4/vendors/ash-tay-shop-name/

Browser: Chrome

Can you help me resolve this?

Thanks!

Sarah

**Comment by rilwis** [comment]
Hi @sarahsampino ,

Can you please provide more details on your setup? Which plugins are you using?

**Comment by rilwis** [comment]
I'll close this issue as no replies. Feel free to re-open it if you still see the bug.
