### ISSUE TITLE
Some characters are removed on update

### ISSUE THREAD

**Issue by CharlieEtienne** [wpmetabox/meta-box#1354]
## Issue Overview

The specific string `%de` is removed on field update on latest version.
I have a simple text field in which I'm trying to write `%dept_name%`.
With meta-box 4.18.1 it works fine.
With meta-box 5.2.4 it removes `%de` from this string and the content of my field becomes `pt_name%`

## Steps to Reproduce

1. Fresh WP 5.3.2
2. TwentyTwenty Theme 1.1
3. Meta Box 5.2.4
4. in `functions.php` or wherever you want, paste this code to create a new cpt and a metabox text field in it :

```php
function test_custom_post_type() {	
	$args = array(
		'label'                 => __( 'Test'),
		'description'           => __( 'Test'),
		'supports'              => array( 'title', 'custom-fields' ),
		'hierarchical'          => true,
		'public'                => false,
		'show_ui'               => true,
		'show_in_menu'          => true,
		'menu_position'         => 5,
		'menu_icon'             => 'dashicons-book-alt',
		'show_in_admin_bar'     => true,
		'show_in_nav_menus'     => false,
		'can_export'            => false,
		'has_archive'           => false,
		'exclude_from_search'   => true,
		'publicly_queryable'    => false,
		'rewrite'               => false,
		'capability_type'       => 'page',
		'show_in_rest'          => false,
	);
	register_post_type( 'test', $args );
}
add_action( 'init', 'test_custom_post_type', 0 );


function test_get_meta_box( $meta_boxes ) {
	$prefix = 'test-';

	$meta_boxes[] = array(
		'id' => 'untitled',
		'title' => esc_html__( 'Untitled Metabox', 'metabox-online-generator' ),
		'post_types' => array('test'),
		'context' => 'advanced',
		'priority' => 'default',
		'autosave' => 'false',
		'fields' => array(
			array(
				'id' => $prefix . 'text_1',
				'type' => 'text',
				'name' => esc_html__( 'Text', 'metabox-online-generator' ),
			),
		),
	);

	return $meta_boxes;
}
add_filter( 'rwmb_meta_boxes', 'test_get_meta_box' );
```
5. try to populate field with `%dept_name%`

**Comment by rilwis** [comment]
Hi @CharlieEtienne ,

I've checked and found that the problem is caused by the sanitization mechanism, which was added to recent versions of Meta Box. For text input, it use `sanitize_text_field` function to sanitize the value before saving to the database. This function checks for `%` character at the beginning of the text and strips it.

To bypass the sanitization, please set `'sanitize_callback' => 'none'` for the field. For more details, please see [this documentation](https://docs.metabox.io/sanitization/).
