### ISSUE TITLE
Cannot install plugin via Composer any more.

### ISSUE THREAD

**Issue by antonkorotkov** [wpmetabox/meta-box#1355]
## Issue Overview

Cannot install using Composer anymore. Since 5.2.4.

## Steps to Reproduce (for bugs)

Run `composer require wpmetabox/meta-box`

## Expected Behavior

Plugin should be installed to `vendor` and autoloaded by Composer.

## Current Behavior

Plugins API is not available in the project and `autoload_static.php` does not have any reference to `meta-box.php`

## Possible Solution

I think it happens because of this commit https://github.com/wpmetabox/meta-box/commit/d64787169b1ce93902eb17785f6ad51c6bba5e8d#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780

## Screenshots / Video

Not applicable.

## Related Issues and/or PRs

https://github.com/wpmetabox/meta-box/commit/d64787169b1ce93902eb17785f6ad51c6bba5e8d#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780

**Comment by rilwis** [comment]
Hi @antonkorotkov ,

I've just tried to run the composer command and it seems fine to me. Please see this video:

https://imgur.com/jyHmzxV

Also note that the plugin doesn't add any file to autoload. You should manually add the plugin's main file to your `composer.json` autoload. Please see [this guide](https://docs.metabox.io/composer/) for details.

**Comment by antonkorotkov** [comment]
@rilwis installing does work for me as well. What does not work - is that plugin's API is not available after:  
```php
require plugin_dir_path( __FILE__) . 'vendor/autoload.php';
```

> Also note that the plugin doesn't add any file to autoload. You should manually add the plugin's main file to your composer.json autoload. Please see this guide for details.

This is kinda weird. Can you link me to the guide where this is described? 

Thanks.

**Comment by rilwis** [comment]
Did you add the `vendor/wpmetabox/meta-box/meta-box.php` file to your `composer.json`? It's required to run the autoload.

**Comment by antonkorotkov** [comment]
Are you talking about the way you were doing it before the commit I reference? 

https://github.com/wpmetabox/meta-box/blob/6897ee3b0ccd88f39a0f5451f8a6916750da78cb/composer.json#L25-L29

**Comment by rilwis** [comment]
Yes, that's right.

See this [composer.json](https://github.com/wpmetabox/library/blob/master/composer/composer.json) file for reference (note where to autoload meta-box.php file).

**Comment by antonkorotkov** [comment]
Ok, got it. 
Don't you think you should mention this in [the guide](https://docs.metabox.io/composer/)? That is not obvious at all :)

**Comment by rilwis** [comment]
Will do now!
