### ISSUE TITLE
Metabox not displaying properly after wordpress update

### ISSUE THREAD

**Issue by Rustynails4** [wpmetabox/meta-box#1356]
Huge issue with Metabox.

updated wordpress and now it wont display properly. anyone else experiancing this?
![slider](https://user-images.githubusercontent.com/60621782/73678344-13cc4800-471d-11ea-8bbc-414507260259.PNG)

**Comment by pavlicko** [comment]
Also had an issue with metabox, but mine was resolved by disabling the classic editor and using Gutenburg instead.

**Comment by rilwis** [comment]
Hi @Rustynails4 & @pavlicko 

Can you please give more details about your environment? WP version, meta box code, Meta Box plugin version, premium extensions you use.

**Comment by Rustynails4** [comment]
Metabox version 5.2.6 / Wordpress version 5.3.2 / not sure about metabox code as it came with the theme at least a couple of years ago.

**Comment by Rustynails4** [comment]
I disabled the clasic editor and it still looks pretty bad.

**Comment by Rustynails4** [comment]
I am not a fan of Gutenburg

**Comment by rilwis** [comment]
@Rustynails4 what theme are you using?

Can you reach to the theme author and ask for update? Maybe they use old versions of Meta Box extensions.
