### ISSUE TITLE
Error after update Meta Box to 5.2.6: Cannot iterate on string offsets by reference in image.php

### ISSUE THREAD

**Issue by AheadVictor** [wpmetabox/meta-box#1357]
Hello,

after update Meta Box to 5.2.6 on my Wordpress 5.3.2, I have an error with image.php, those one:

- PHP Fatal error:  Uncaught Error: Cannot iterate on string offsets by reference in /home/gestions/gestionsaludmental.com/html/wp-content/plugins/meta-box/inc/fields/image.php:166

- PHP Warning:  Illegal string offset 'sizes' in /home/gestions/gestionsaludmental.com/html/wp-content/plugins/meta-box/inc/fields/image.php on line 166

We think the problem come from charge at meta-box image-advanced a .sgv image. This is the svg image: [https://gestionsaludmental.com/wp-content/uploads/2018/08/logo-comodidad-negro.svg](url)
So we search for the error and we try to found the solution, so we add to the code this patch on image.php:

![image](https://user-images.githubusercontent.com/60707773/73864536-22604f80-4842-11ea-9e04-d7f85bf37efe.png)

I don't know if we found the solution or this will have some problem aswell.

Thanks, we are in contact.

Victor.

**Comment by rilwis** [comment]
Hi @AheadVictor 

Did you use a plugin to add support for SVG?

Do you see the error when getting the field value on the front end? Or how do you see it?

**Comment by AheadVictor** [comment]
Hi,

We are not using a plugin in our Wordpress to add support for SVG, its just a filter to allow Svg extensions:

`function cc_mime_types($mimes) {
 $mimes['svg'] = 'image/svg+xml';
 return $mimes;
}
add_filter('upload_mimes', 'cc_mime_types');`

And yes we see the error on the front end  when we get a value from Meta Box -> image-advanced, the typical error of Wordpresss when something goes wrong: "This site is expecting technical difficulties. Please check your site admin email inbox for instructions."

**Comment by rilwis** [comment]
I've just tested and couldn't see any error. Here is my video:

https://www.loom.com/share/9dd5420eddca4a65a11d93b817fdd016

Can you check if there's anything I missed?

**Comment by rilwis** [comment]
Anyway, I've just pushed a fix for this.

**Comment by AheadVictor** [comment]
We didn't see any different, anyway thank you very much for your time on us.

**Comment by rilwis** [comment]
@AheadVictor 

We haven't released a new version yet. The fix is in https://github.com/wpmetabox/meta-box/commit/fe77e74a85008165d13fa120cfd2b5666bb6d4ef, can you please try it?

**Comment by AheadVictor** [comment]
Hello @rilwis,

We just tested your code and works perfectly.
