### ISSUE TITLE
Lost posts after editing Basic Settings

### ISSUE THREAD

**Issue by patriciomas** [wpmetabox/meta-box#1359]
## Issue Overview
Needed to change Post Type name, edited the Basic Settings: Plural Name, Singular Name, Slug.
Lost all posts related to that post type.
Tried editing back to the original settings, but did not recover posts.

## Steps to Reproduce (for bugs)
1. Create new Post Type
2. Create posts in the new post type
3. Edit Basic Settings in post type
4. Visit post type section to find all posts missing

https://electricas.patriciomas.cl/
Server Setup:
Operating System | Linux
Web Server | Apache/2.4.18 (Ubuntu)
WordPress Version | 5.3.2
Charset | UTF-8
Version | 7.0.33-0ubuntu0.16.04.9
MySQL Version | 5.7.29

## Expected Behavior

If the option to edit the Basic Settings is available, it should not erase or dissociate the relation between the posts and the Post Type you created.
Either disable editing for the fields that would break the relation or warn users of the consequences of editing these settings.

## Current Behavior
Lost all posts related to the Post Type after editing Basic Settings.

**Comment by rilwis** [comment]
Hi @patriciomas 

WordPress tracks posts in a post type by its slug. Whenever you change the slug, it means a complete new post type is registered. You're okay to edit the labels (Plural label, singular label and other labels), but you should not change the post type slug when you have some content.

The way to fix that is change the slug to the previous value. And there should not any change before doing that.
