### ISSUE TITLE
I'm using plugin version 5.2.7. I can't figure out if I'm using the wrong syntax to display the short code, but I can't get any of my fields to display. I don't know if it's poor documentation or if I'm doing something wrong. Any help would be appreciated.

### ISSUE THREAD

**Issue by basest** [wpmetabox/meta-box#1363]
## Issue Overview

I can't seem to figure out how to display my fields. I have created the meta box correctly. It's displaying properly in the post editing screen, but I guess I don't understand how to set the shortcode up. 
## Steps to Reproduce (for bugs)

1. I've attached the code for my meta box
[showinfo metabox.txt](https://github.com/wpmetabox/meta-box/files/4384270/showinfo.metabox.txt)

2.
3.
4.

## Expected Behavior

I'm trying to display a field from my meta box. In this case, it's a field called "musicby". I've used this shortcode [rwmb_meta id="musicby"]. I have also tried this shortcode: [rwmb_meta id="showinfo-musicby"] ("showinfo" is the ID of the meta box)

## Current Behavior

Nothing shows up.

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by rilwis** [comment]
Hi @basest , please provide more details in the issue. We have steps in the issue and please use them to describe it verbosely. Please don't write everything in the title. That makes us easier to check the bug for you and help you to fix it.

**Comment by basest** [comment]
I've updated the original post. My apologies for doing it incorrectly the first time.

**Comment by Longkt** [comment]
Hi @basest 

If you are using the shortcode in PHP code, use the function do_shortcode to show the shortcode

`echo do_shortcode('[rwmb_meta id="showinfo-musicby"]');`

**Comment by basest** [comment]
thanks for the reply. I am just using the shortcode in the content area of the post. Is this not possible with meta box shortcodes?

**Comment by Longkt** [comment]
You can use the shortcode in the content of the post as well, see my screen record
https://cl.ly/ebb99e5f482c
