### ISSUE TITLE
[feature-request] Setter companion to rwmb_meta

### ISSUE THREAD

**Issue by hsimah** [wpmetabox/meta-box#1366]
I am working on an [integration plugin with WPGraphQL](https://github.com/hsimah/wp-graphql-metabox). I have completed the basic data access, but I have not written any mutations. Given the `rwmb_meta` function makes reading fields so easy, why not have a `rwmb_set_meta` in order to easily do the writing?

**Comment by rilwis** [comment]
Let's discuss on the PR to keep everything in one place.
