### ISSUE TITLE
Taxonomy fields not cloneable

### ISSUE THREAD

**Issue by lucabi2** [wpmetabox/meta-box#1368]
Hi Ahn,
I wanted to attach multiple terms to a post item, but I can't get cloneable working when field type is set to 'taxonomy'. It works well with any other field type, including 'taxonomy_advanced', but this is not really my case. I've seen you fixed the 'taxonomy_advanced' case in 4.14.1, would it be possible to fix also for proper taxonomy fields?
Thanks, Luca

**Comment by rilwis** [comment]
Hi,

It's not a bug. `taxonomy` field is used to set post terms. So it can't be cloneable. If you need to set multiple terms, please set `'multiple' => true` or use `checkbox_list` field type.

**Comment by lucabi2** [comment]
Hi Han,
I understand the same result can be generally obtained by setting 'multiple' => true. Actually, my final need was to extend the taxonomy field with an additional combo-box in order to associate 2 taxonomies in a pair (add a role to an author, for example). I can't simply use 2 distinct taxonomy fields with multi-selection because I would loose the association between the selections.
This would be the ideal UI:
![image](https://user-images.githubusercontent.com/64684154/80915645-f88ccb00-8d53-11ea-95f8-f25408150d1a.png)
Thanks for the explanation, I think I'm going to extend the basic field class, though it requires more work.
