### ISSUE TITLE
Calling a specific post type to use in an array

### ISSUE THREAD

**Issue by BenKabuula** [wpmetabox/meta-box#1370]
![forum](https://user-images.githubusercontent.com/65104505/81492428-cb7e7200-9297-11ea-80f7-0acf3c8d5130.png)

Am trying to call a certain post type inside a meta box for a select option as shown on the image above its pulling the data properly
![cat](https://user-images.githubusercontent.com/65104505/81492469-35971700-9298-11ea-8827-04999214627f.png)
 but the problem arise when am trying to get the values on the front end as seen below on the Category 2 am getting digits not the desired value
![front-end](https://user-images.githubusercontent.com/65104505/81492438-eb159a80-9297-11ea-8fa3-3bfcb1b0f7bb.png)

Any assistance on this issue

**Comment by rilwis** [comment]
If `$post_list` is the field you're talking about, then you're saving post ID to the field. Then when getting the value, you'll get the ID, which is correct.

You might need to use functions like `get_post_title` to transform from ID to post title.

**Comment by BenKabuula** [comment]
Alright thank let me tweak my code
