### ISSUE TITLE
Feature request - Enable emojis in text fields

### ISSUE THREAD

**Issue by stefanue** [wpmetabox/meta-box#1371]
## Feature Overview

When using a text field:

```
 array(
    'name'  => 'Title',
    'id'    => "block_title",
    'type'  => 'text',
    'desc'  => 'Enter a block title',
    'std'   =>  'Hello World',
),
```

Can you enable use of emojis such as:

😀😃😄🔥🧨🍕❤️

**Comment by rilwis** [comment]
You can use them by setting `'sanitize_callback' => 'none'`. For more details, please see this docs:

https://docs.metabox.io/sanitization/

**Comment by stefanue** [comment]
Hi, 

Thanks for your quick reply. I just tried that and it doesn't work on my side. Code example below:

```
array(
    'name'  => 'Section Subtitle',
    'id'    => "section3_subtitle",
    'desc'  => '',
    'type'  => 'text',
    'sanitize_callback' => 'none',
    'std'   =>  '',
),
```

I tried to enter: Sample title 🔥

**Comment by rilwis** [comment]
I've just checked your code and see it works. Please see my video:

https://www.loom.com/share/60c7cf4def554d74aef5826e62b8bfda
