### ISSUE TITLE
unable to contact a template developer...what should I do?

### ISSUE THREAD

**Issue by domingon** [wpmetabox/meta-box#1374]
## Issue Overview
I purchased a template with themeforest: 
https://themeforest.net/item/craftory-directory-listing-job-board-wordpress-theme/20919308

I have started to enter some information realising that some areas are inaccessible for customisation. I was in contact with the developer until the past few days when his website  is nolonger available.

As there is a metabox plugin, I am suspecting that many of the forms and pages are hidden there but I cannot access.

Will having a metabox give me the access permissions needed to make the changes?

**Comment by rilwis** [comment]
Hi @domingon,

Thanks for contacting us. But this seems to be an issue with the theme and we can't help you with that.

**Comment by domingon** [comment]
thanks Rilwis, are you able to confirm if buying a license will provide me access to the sections of the template that I need to access and customise.

**Comment by rilwis** [comment]
Hi @domingon,

Buying a license from us allows you to:

- Use premium extensions in any site/theme/plugin you want. So you have an independent license from the theme author and might no longer depends on them to provide updates.
- Access to updates of the extensions
- Access to support forum

We provide support for the premium Meta Box extensions. So if you have any problem with it, we can help.

However, we don't provide support for themes, templates or other things that don't come from our extensions such as theme customization (which I believe this is the case).
