### ISSUE TITLE
Metabox.io cause blank page

### ISSUE THREAD

**Issue by A-Nash** [wpmetabox/meta-box#1375]
Hello all,

So I’m having a little issue with the plugin Metabox.io
When activated, my editor page in the admin panel goes blank and I can’t edit any page. Thought it was an update issue and updated the plugin but didn’t change anything. So I activated wp debug and this is the error I get on blank pages:
Fatal error: Call to undefined function wp_enqueue_editor() in /home/xxxx/www/xxx/xxx/wp-content/plugins/meta-box/inc/fields/wysiwyg.php

Thank you in advance for you answers.

**Comment by rilwis** [comment]
Hi @A-Nash ,

We see your topic on .org. Let's discuss there to avoid duplication.
