### ISSUE TITLE
Metabox group: wysiwyg does not display content after moving

### ISSUE THREAD

**Issue by SimonvanWijhe** [wpmetabox/meta-box#1376]
## Issue Overview

Content of wysiwyg field is not displayed after moving, if the field is dropped at the same place as before moving it.

## Steps to Reproduce (for bugs)

1. Add the following code to functions.php:
```
add_filter('rwmb_meta_boxes', 'meta_box_group_demo_register');
function meta_box_group_demo_register($meta_boxes)
{
    $meta_boxes[] = array(
        'title'  => 'Demo group',
        'fields' => array(
            array(
                'id'     => 'standard',
                'type'   => 'group',
                'clone'  => true,
                'sort_clone' => true,
                'fields' => array(
                    array(
                        'name' => 'Demo field',
                        'id' => 'demo-field',
                        'type' => 'wysiwyg',
                        'options' => array(
                            'textarea_rows' => 4,
                        ),
                    )
                ),
            ),
        ),
    );
    return $meta_boxes;
}
```
2. Create a post.
3. Add content to demo field.
4. Click 'Add more'
5. Add content to second demo field.
6. Pick up the first demo field.
7. Drop the field at the same spot as where it was picked up.

## Expected Behavior

Expect to the content to display, as before moving it.

## Current Behavior

The content of the field is not displayed. Selecting the field content reveals that the content is actually still there.
Possible workaround: first clicking the "text" button and then clicking the "visual" button solves the problem.

## Screenshots / Video

![demo-wysiwyg-sort-clone](https://user-images.githubusercontent.com/41121933/87153030-0eb88980-c2b7-11ea-9f36-6f2d32accba0.gif)

## Additional information:
* Wordpress 5.4.2
* Pugins: Metabox, Metabox Group
* Theme: twentytwenty
* Browser: Chrome version:83.0.4103.116
* MacOS

**Comment by Longkt** [comment]
Hi @SimonvanWijhe 

Thank you for pointing this out. You can use this CSS code in [the admin area](https://wordpress.org/plugins/admin-css-mu/) to fix this issue temporarily.

`body .rwmb-field .tmce-active .wp-editor-area {
	color: #000;
}`

Regards.

**Comment by SimonvanWijhe** [comment]
Hi @Longkt,

Thanks for your reaction. Unfortunately this doesn't really solve the problem.

The content is now shown (with the extra line of css). But still the html tags are shown. See recording. 

![demo-wysiwyg-sort-clone-with-css](https://user-images.githubusercontent.com/41121933/88192657-16741880-cc3d-11ea-894d-68ed67b25c53.gif)

For the html tags to disappear I would still have to click the "text" button followed by "visual".

Any ideas on when the issue will be fixed?

Best,
Simon

**Comment by SimonvanWijhe** [comment]
Related Issue: https://github.com/wpmetabox/meta-box/issues/1381

**Comment by rilwis** [comment]
We no longer see this bug. It's probably fixed in recent commits.

If you still see this bug, feel free to re-open or create a new issue.
