### ISSUE TITLE
Get field's description value

### ISSUE THREAD

**Issue by vinrgates** [wpmetabox/meta-box#1377]
Hello, is it possible to get a description value from a field?

Thank you

**Comment by Longkt** [comment]
Hi @vinrgates 

The function `rwmb_get_field_settings( $field_id, $args, $object_id )` helps you to get all settings of a field. For more information, please follow this [documentation](https://docs.metabox.io/rwmb-get-field-settings/#arguments).

Regards.

**Comment by vinrgates** [comment]
Thank you! :D @Longkt 

One more thing, how is it possible to use html tag on the description or default 'std' value?
