### ISSUE TITLE
Taxonomy field in Metabox Group won't save

### ISSUE THREAD

**Issue by vinrgates** [wpmetabox/meta-box#1380]
Hello,
The taxonomy filed won't preserve the selection.
The select field will reset back to the unselected condition every time the page is refreshed, I also checked the database and also the taxonomy page, it's not showing any posts linked to it.

IF the taxonomy field is not in the group it is working just fine.

Here's my metabox
```
array(
	'id'      	  => 'access_group',
	'type'    	  => 'group',
	'columns' 	  => 12,
	'tab'     	  => 'property-location',
	'clone'       => true,
	'clone_default'	=> true,
	'clone_as_multiple' => true,
	'sort_clone'  => true,
	'collapsible' => true,
	'group_title' => '{property_access}',
	'fields'  => array(
		array(
			'name'       => 'Property Access',
			'id'         => 'property_access',
			'type'       => 'taxonomy',
			'taxonomy'   => 'access',
			'field_type' => 'select_tree',
			'clone_default'	=> true
		),
	),
)
```

**Comment by Longkt** [comment]
Hi @vinrgates 

The field `taxonomy` doesn’t store any terms in the post meta. Instead, it sets post terms. Just like a replacement of Category or Tag meta box of WordPress so it does not work with Group. If you want to save the taxonomy as the post meta, please use the field `taxonomy_advanced`.

For more information, please follow these documentations
https://docs.metabox.io/fields/taxonomy-advanced/
https://docs.metabox.io/fields/taxonomy/#data
