### ISSUE TITLE
Metabox group: wysiwig content replaced with post content after deactivate Classic Editor

### ISSUE THREAD

**Issue by SimonvanWijhe** [wpmetabox/meta-box#1381]
## Issue Overview

Metabox group: wysiwig content replaced with post content after deactivate Classic Editor.

## Steps to Reproduce (for bugs)

1. Add the following code to functions.php:
```
add_filter('rwmb_meta_boxes', 'meta_box_group_demo_register');
function meta_box_group_demo_register($meta_boxes)
{
    $meta_boxes[] = array(
        'title'  => 'Demo group',
        'fields' => array(
            array(
                'id'     => 'standard',
                'type'   => 'group',
                'clone'  => true,
                'sort_clone' => true,
                'fields' => array(
                    array(
                        'name' => 'Demo field',
                        'id' => 'demo-field',
                        'type' => 'wysiwyg',
                        'options' => array(
                            'textarea_rows' => 4,
                        ),
                    )
                ),
            ),
        ),
    );
    return $meta_boxes;
}
```
2. Install "Classic Editor" plugin by Wordpress Contributors
3. Create a post.
4. Add some post content.
5. Add content to demo field.
6. Click 'Add more'
7. Add content to second demo field.
8. Switch the demo fields around.

## Expected Behavior

Expect the group fields to display their content, as before moving it.

## Current Behavior

The content of the group fields are replaced with the post content.

## Screenshots / Video
![demo-wysiwyg-group-classic-editor](https://user-images.githubusercontent.com/41121933/88521704-901d5500-cff5-11ea-805e-2a4ac90e5ad9.gif)

## Additional information:

* Related issue: https://github.com/wpmetabox/meta-box/issues/1376

* Wordpress 5.4.2
* Pugins: Metabox, Metabox Group, Classic Editor
* Theme: twentytwenty
* Browser: Chrome version:83.0.4103.116
* MacOS

**Comment by edwinsiebel** [comment]
This is a annoying bug. We also have the same issue.

I've traced it down to the file `js/clone.js` and specific line 245: 

```
tinymce.execCommand( 'mceAddEditor', true, this.id );
```

When removing this line, the drag and drop is successful, however the tab visual is switch to text, and the editor show the html instead of the styled text.

Hope this helps the journey into this bug.

**Comment by edwinsiebel** [comment]
Adding `editor.execCommand('mceSetContent', false, this.id);` above `tinymce.execCommand( 'mceAddEditor', true, this.id );` (line 245) does seem to fix the problem of the content being swapped.

The tabs are still scambled (see my previous post)

**Comment by viet34tqc** [comment]
@edwinsiebel 
What is 'editor' in `editor.execCommand('mceSetContent', false, this.id);`?

**Comment by edwinsiebel** [comment]
@viet34tqc , never mind my reaction. The `editor.execCommand('mceSetContent', false, this.id);` returns an error, so that's why `tinymce.execCommand( 'mceAddEditor', true, this.id );` was not executed, and thus that 'fixes' what I wrote in https://github.com/wpmetabox/meta-box/issues/1381#issuecomment-673975100.

**Comment by edwinsiebel** [comment]
Any research or improvements on this post?

**Comment by rilwis** [comment]
Hi,

This is an old issue and it seems to be fixed in the latest version of Meta Box and extensions. So I'll close the issue.

If you still notice the bug, please re-open it.
