### ISSUE TITLE
How to tell is this website is using your installed plugin?

### ISSUE THREAD

**Issue by TheHappyCreative** [wpmetabox/meta-box#1385]
Hi there, 
I've inherited a website that used two plugins
https://candleempire.com.au/
-Meta Box Conditional Logic
-Meta Box Tabs

It needs a license renewal before I can update the plugins, however I'm not actually sure the site is using them? I can't see any evidence of this. Can you advise how I can tell if either/both are being used? I would prefer to delete them if they are not being used. Thanks :)

**Comment by rilwis** [comment]
Hi, please go to the WordPress Dashboard > Plugins and you'll see all plugins. If you see them there and are activated, then they're being used on the website.

**Comment by TheHappyCreative** [comment]
Hi Tran,

This quite an unhelpful response.
Plugjns can be activated on a site and not actually used.

Can you point me in the direction of where I might see evidence of actual 'use' if the plugin on the site?

Thanks.

Stacey

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by rilwis** [comment]
Hi @TheHappyCreative,

I got it.

To see if Meta Box Conditional Logic is used, you need to check the meta boxes and fields to see if they're toggled under any condition (or depends on any other field's value).

To see if Meta Box Tabs is used, you can check if there's any style like tabs in the editing page.

For more details, please see how the plugins work:

https://metabox.io/plugins/meta-box-conditional-logic/
https://metabox.io/plugins/meta-box-tabs/

If you have access to code, it's best to check the code that registers meta boxes and custom fields. If the code has something similar to what these extensions need (check out the docs here https://docs.metabox.io/extensions/meta-box-conditional-logic/ and https://docs.metabox.io/extensions/meta-box-tabs/), then they're in use.
