### ISSUE TITLE
select2 and custom post types not working

### ISSUE THREAD

**Issue by rupert-quaderer** [wpmetabox/meta-box#1386]
#936  Issue Overview

In all this years i used the select2 field type to list custom post types in the backend. But for some reason this will now not working anymore. For your info: Wordpress version: 5.5.1 and the newest metabox free version: 5.3.3

## My Code for
```php
array(
'name'  => __('Link CTA', 'text_domain'),
placeholder' => 'Choose a Custom Post Type',
'id'    => 'my_id',
'type' 	=> 'post',
'post_type'  => 'custom_post_type_name',
'field_type' => 'select_advanced',
),
```

If i change the field_type to "select" everything is fine. Is this a bug or missunderstand i something?

**Comment by rilwis** [comment]
Hi @rupert-quaderer 

I've checked and found the field `post` works well with custom post type and with `field_type` is `select_advanced`. As this issue is old, I'll close it. If you still find the problem, feel free to re-open it.
