### ISSUE TITLE
File input not working with MB Term Meta

### ISSUE THREAD

**Issue by jeanmatthieud** [wpmetabox/meta-box#1388]
## Issue Overview
The "File" input doesn't works with the MB Term meta extension: the file is not uploaded.

## Steps to Reproduce (for bugs)
1. Install MB and MB Term Meta
2. Create a custom taxonomy
3. Add a "Input" MB field the custom taxonomy
4. Upload a file

## Expected Behavior
The file is saved

## Current Behavior
The file is not saved.

## Possible Solution
The attribute `enctype="multipart/form-data"` is missing on the taxonomy edit form tag.
In fact the action (and so function) `post_edit_form_tag` is not called for taxonomies.

The `add_actions()` function of `file.php` should be patched for taxonomies.

I had to manually add the following action in my plugin source code:
```php 
add_action('{$taxonomy}_term_edit_form_tag', array('RWMB_File_Field', 'post_edit_form_tag'));
```

[See the documentation](https://developer.wordpress.org/reference/hooks/taxonomy_term_edit_form_tag/)

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by rilwis** [comment]
Thanks a lot for your help. We've fixed it in the latest version 1.2.10. Please update.
