### ISSUE TITLE
image_advanced field store only one image

### ISSUE THREAD

**Issue by buraksahin59** [wpmetabox/meta-box#1389]
Hello guys, 
The problem is that image_advanced field can store only one image, not multiple images. Can you please help me about it?
Wordpress version is to it's latest released version 5.6.
Metabox version is to it's latest released version 5.3.5.
Thank you for your great plugin.

Warm Regards

## Issue Overview
The problem is that I choose multiple images (eg. 10) and when I save it, I only store only one image. Also, I disabled all plugins excluding Metabox and Really Simple SSL but nothing changed.

## Codes
```
function portfolio_gallery( $meta_boxes ) {    
    $meta_boxes[] = array(
        'id' => 'portfolio_box',
        'title' => esc_html__( 'Isotope Portfolio', 'metabox-online-generator' ),
        'post_types' => array( 'portfolio', 'service' ),
        'context' => 'normal',
        'priority' => 'default',
        'fields' => array(
            array(
                'id' => 'image_advanced_1_id',
                'type' => 'image_advanced',
                'name' => esc_html__( 'Image Advanced', 'metabox-online-generator' ),
                'max_file_uploads' =>99,
                'max_status' => true,
            ),
        ),
    );
    
    return $meta_boxes;
}
add_filter( 'rwmb_meta_boxes', 'portfolio_gallery' );
```

## Screenshots / Video

https://user-images.githubusercontent.com/5235659/103038619-f051fc00-457f-11eb-9b92-e02de80c92fa.mov

**Comment by Longkt** [comment]
Hi @buraksahin59 

I've tried to run your code on my testing site but not see any issue, screen record https://share.getcloudapp.com/9Zu0KlE8.

Please try to deactivate all plugins except Meta box, and switch to the default theme of WordPress (Twenty TwentyOne) and check this issue again.
