### ISSUE TITLE
OSM field not loading the saved value without an address field

### ISSUE THREAD

**Issue by robi09** [wpmetabox/meta-box#1392]
## Issue Overview
The osm field type is not loading the saved value if the address field is not defined,

## Steps to Reproduce (for bugs)
Create an osm field and don't attach an address to it.
Select a point on the map other the Dublin.
Save post.
Reload page.
Your selection is saved but not loaded

If you attach an address field, the saved selection is loaded.

## Expected Behavior
The saved selection should load as a default value.

Thank you.

**Comment by rilwis** [comment]
Fixed in 1a86d2b445ad52052f0015923707228f487b2c80
