### ISSUE TITLE
In MB Builder, Tooltip for Google Maps API Key is incorrect

### ISSUE THREAD

**Issue by brandonjp** [wpmetabox/meta-box#1396]
I wasn't sure where to submit this, but it should be a quick fix.

In the MetaBox Builder, for a Google Maps field, the tooltip next to the label for "Google Maps API key" is displaying the tooltip from the Address instead of a tooltip specific to the Google Maps API key.

Screenshot: https://cln.sh/3uGc7t

<img width="676" alt="CleanShot 2021-04-08 at 17 28 09@2x" src="https://user-images.githubusercontent.com/199599/114104063-d074e880-988f-11eb-9fa2-493aea2ddf2f.png">

**Comment by rilwis** [comment]
Thanks for your feedback! I've fixed this bug and will include it in the next version.
