### ISSUE TITLE
Last update does not list in WordPress Toolkit

### ISSUE THREAD

**Issue by ribeiroeder** [wpmetabox/meta-box#1399]
Hello

I have always used the WordPress Toolkit to massively manage plugin updates on the server I manage.

But this latest update v5.3.10 is not shown on the panel. Notice in the image that other plugins notify that there is an updated version.

WordPress Toolkit is based on WP-CLI.

![image](https://user-images.githubusercontent.com/24439523/117237610-b46a5580-ae01-11eb-9f28-550eb67eb85e.png)

**Comment by rilwis** [comment]
Hi @ribeiroeder,

WordPress Toolkit is out of our control. We provide new versions as other plugins on WordPress.org. If WordPress Toolkit works well with WordPress.org, then it should be not a problem.
