### ISSUE TITLE
Flexible Content / Page Builder

### ISSUE THREAD

**Issue by wgstjf** [wpmetabox/meta-box#1402]
Hi guys,

We're revisiting the idea of using MB to create a custom Page Builder capability as previously referenced in https://github.com/wpmetabox/meta-box/issues/1053

I was wondering whether you had any way of replicating the 'Flexible Content' functionality shown in this ACF video?

![](https://thewhitelabelagency.com/wp-content/uploads/2019/05/acf_flexible_content_demo.gif)

All the best,

Will

**Comment by rilwis** [comment]
Yes, please see [this tutorial](https://metabox.io/create-acf-flexible-content-field-with-meta-box/).

If you use our new [ACF Migration](https://metabox.io/plugins/mb-acf-migration/) extension, it'll migrate ACF flexible content to Meta Box as well.

**Comment by wgstjf** [comment]
Thanks for the quick reply.  What you proposed in the tutorial is exactly what we've been doing for a few years now but I was looking to see if the more user-friendly capability shown in the video above existed natively in MB.

I've now created a plugin that, though css, js and a couple of filters, extends the capability of MB (when used in conjunction with Group) to achieve the above effect and it is now working well.  See demo below: 

https://user-images.githubusercontent.com/3740694/123804873-81b27a00-d8e5-11eb-8c89-63a73a50da8b.mp4

My question is, is there any way to utilise functions from the clone.js script loaded by MB within my plugin js?  I know we can utilise rwmb functions but seemingly not clone related.  It would be great if this was possible as it would prevent me from having to duplicate js vars and functions such as cloneIndex, cloneValue and sortClones in my plugin js.

Thanks in advance,

Will

**Comment by rilwis** [comment]
Hi Will,

It's interesting to see your video.

Regarding clone, currently the code is wrapped in a closure, so it's not possible to use outside the script. I've just modified it to allow you to do that.

**Comment by wgstjf** [comment]
That's amazing!  Truly appreciate that change which will dramatically improve the stability of my plugin.

Have a great day.

Will

**Comment by wgstjf** [comment]
It would be great if you could add toggleRemoveButtons to the available functions as well?

Thanks again,

Will

**Comment by rilwis** [comment]
Done!
