### ISSUE TITLE
Getting a syntax error on my wordpress site after latest update of plugin

### ISSUE THREAD

**Issue by scd5531** [wpmetabox/meta-box#1403]
## Issue Overview
After plugin was updated wordpress site fails to load with this error:
Parse error: syntax error, unexpected ')' in /home/content/71/8401671/html/wp-content/plugins/meta-box/inc/fields/image.php on line 54

Wordpress version:  5.7.2
Plugin version: 5.4.2
Theme: Dante version 3.5.25

**Comment by rilwis** [comment]
Fixed in 715a1e988b6bc16f71b76e13f79e40591b071790
