### ISSUE TITLE
Use clone.js functions in custom MB extension plugin

### ISSUE THREAD

**Issue by wgstjf** [wpmetabox/meta-box#1405]
Thanks for the quick reply to #1402.  What you proposed in the tutorial is exactly what we've been doing for a few years now but I was looking to see if the more user-friendly capability shown in the video above existed natively in MB.

I've now created a plugin that, though css, js and a couple of filters, extends the capability of MB (when used in conjunction with Group) to achieve the above effect and it is now working well.  See demo below: 

https://user-images.githubusercontent.com/3740694/123804873-81b27a00-d8e5-11eb-8c89-63a73a50da8b.mp4

My question is, is there any way to utilise functions from the clone.js script loaded by MB within my plugin js?  I know we can utilise rwmb functions but seemingly not clone related.  It would be great if this was possible as it would prevent me from having to duplicate js vars and functions such as cloneIndex, cloneValue and sortClones in my plugin js.

Thanks in advance,

Will

_Originally posted by @wgstjf in https://github.com/wpmetabox/meta-box/issues/1402#issuecomment-870597212_

**Comment by rilwis** [comment]
Close it as we're discussing in #1402 .
