### ISSUE TITLE
house_number contains not all numbers

### ISSUE THREAD

**Issue by danielswiatek** [wpmetabox/meta-box#1410]
I´ve added the GeoLocation Plugin with Autocomplete. If i select the following adress "Langenbeckstraße 4-6, Mainz, Deutschland" the house_number "4-6" only the number 4 will copied to the house_number

**Comment by rilwis** [comment]
Hi, this is a premium extension, and we support for them on our [support forum](https://metabox.io/support/). Can you please re-post the question over there?
