### ISSUE TITLE
Placeholder for "Select an user"

### ISSUE THREAD

**Issue by superbmario** [wpmetabox/meta-box#1420]
Hi guys,

There is some slightly incorrect English in the User field. Instead of "Select an user" it should be "Select a user"

https://github.com/wpmetabox/meta-box/blob/2282a66b995a15283e02fb71ff2f20c3707eadfc/inc/fields/user.php#L84

**Comment by rilwis** [comment]
Thanks for your feedback! I've just fixed it.
