### ISSUE TITLE
Zion Builder Support

### ISSUE THREAD

**Issue by hj-collab** [wpmetabox/meta-box#1437]
Hello @rilwis,

Can you please help ZionBuilder Team to complete their metabox integration? They have recently introduced support for outputting dynamic metabox fields & clonable metabox fields. They need help with the Metabox Group Integration with their repeater builder. It supports ACF repeater right now. Can you please help them to the right direction?

Builder URL: https://zionbuilder.io/
Discord Server URL: https://discord.gg/pmXcAhw6
Github: https://github.com/zionbuilder/zionbuilder

I am also tagging the Zion Developer here. @zauan

Thank you

**Comment by rilwis** [comment]
Hi @hj-collab and @zauan,

I'm happy to help Zion team add the integration for Meta Box. Please let me know if you have any troubles working with Meta Box Group, or anything else.
