### ISSUE TITLE
Translation not showing

### ISSUE THREAD

**Issue by iWpress** [wpmetabox/meta-box#1460]
Hello!

You are great. "Meta box" - great job!
The translation of lines is not displayed: 12, 15, 16 and 17 of the **inc/about/sections/products.php** file.
Please replace '**falcon**' with '**meta-box**'.

Best regards, Wlodz Mur.
wm@iwpress.eu

**Comment by rilwis** [comment]
Thank you very much for your feedback! It's fixed now.

**Comment by iWpress** [comment]
Thanks a lot. You are great!
