### ISSUE TITLE
 Undefined array key 

### ISSUE THREAD

**Issue by wgstjf** [wpmetabox/meta-box#1464]
Hi guys,

We are seeing the following error:

_Warning: Undefined array key "upload_dir" in /home/***/public_html/wp-content/plugins/meta-box/inc/fields/file.php on line 437_

When using the following code:
`
$this_file_info = RWMB_File_Field::file_info( $this_file_id);
`
Looking at the code in inc/fields/file.php it seems that there is no check to see if the key exists in the array

`
public static function file_info( $file, $args = array(), $field = array() ) {
		if ( $field['upload_dir'] ) {
			return self::file_info_custom_dir( $file, $field );
		}
....
`
Is this something we are doing wrong or does the file_info function need to be modified to use isset?

Cheers,

Will

**Comment by rilwis** [comment]
Hi Will,

The `upload_dir` is available for the `$field` because it's normalized in `normalize` function. However, if you call `file_info` as a helper method to get file info array, it won't be available. I've added a check to prevent this warning.

**Comment by wgstjf** [comment]
Wonderful thanks!

Will
