### ISSUE TITLE
Uncaught Error: Class 'RWMB_Update_Option' not found when adding new post type

### ISSUE THREAD

**Issue by Knoclar** [wpmetabox/meta-box#1470]
## Issue Overview

When adding new post type, I got this error message : Fatal error: Uncaught Error: Class 'RWMB_Update_Option' not found...
Error that happens only in version 5.6.14 and using default theme 2022
I'm using bedrock for WordPress
## Steps to Reproduce (for bugs)

1. Activate Metabox
2. Activate Metabox AIO
3. Add new post type
4. See the error

Browser I use : Firefox 107.0.1 (64 bits)

## Expected Behavior

No error

## Current Behavior

Fatal Error

## Possible Solution

Downgrade to version 5.6.13

## Screenshots / Video

Here's the full error :
`Fatal error: Uncaught Error: Class 'RWMB_Update_Option' not found in path_to_wp\web\app\plugins\meta-box-aio\vendor\meta-box\mb-custom-post-type\src\Edit.php:111 Stack trace: #0 path_to_wp\web\app\plugins\meta-box-aio\vendor\meta-box\mb-custom-post-type\src\Edit.php(24): MBCPT\Edit->is_premium_user() #1 path_to_wp\web\wp\wp-includes\class-wp-hook.php(310): MBCPT\Edit->register_upgrade_meta_box('mb-post-type') #2 path_to_wp\web\wp\wp-includes\class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array) #3 path_to_wp\web\wp\wp-includes\plugin.php(517): WP_Hook->do_action(Array) #4 path_to_wp\web\wp\wp-admin\includes\meta-boxes.php(1599): do_action('add_meta_boxes', 'mb-post-type', Object(WP_Post)) #5 path_to_wp\web\wp\wp-admin\edit-form-advanced.php(271): register_and_do_post_meta_boxes(Object(WP_Post)) #6 path_to_wp\web\wp\wp-admin\post-new.php(75): require('path_to_wp...') #7 {main} thrown in path_to_wp\web\app\plugins\meta-box-aio\vendor\meta-box\mb-custom-post-type\src\Edit.php on line 111`

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by rilwis** [comment]
Fixed in mb-custom-post-type/commit/8e65f6e176f3522a1ee04af94b771a9eb768ff86
