### ISSUE TITLE
Switch labels are off

### ISSUE THREAD

**Issue by jstask82** [wpmetabox/meta-box#1495]
I tried to fix this myself and open a pull request, but my fork breaks my test environment. I only changed _meta-box/css/switch.css_.
Upon activation of Meta Box, I get

> Fatal error: Uncaught Error: Class "MetaBox\Updater\Option" not found in /Users/aaronkessler/Developer/ichwillzumfilm/wp-content/plugins/meta-box/inc/loader.php:103 Stack trace: #0 /Users/aaronkessler/Developer/ichwillzumfilm/wp-content/plugins/meta-box/meta-box.php(19): RWMB_Loader->init() #1 /Users/aaronkessler/Developer/ichwillzumfilm/wp-admin/includes/plugin.php(2314): include_once('/Users/aaronkes...') #2 /Users/aaronkessler/Developer/ichwillzumfilm/wp-admin/plugins.php(192): plugin_sandbox_scrape('meta-box/meta-b...') #3 /Users/aaronkessler/.composer/vendor/laravel/valet/server.php(250): require('/Users/aaronkes...') #4 {main} thrown in /Users/aaronkessler/Developer/ichwillzumfilm/wp-content/plugins/meta-box/inc/loader.php on line 103 

## Issue Overview

Switch labels are not centered inside the switch button.
## Steps to Reproduce (for bugs)

Add something like this
```
       [
            'name'      =>  __('Profil-Staus', NAME_SPACE),
            'label_description' => __('Veröffentliche Dein Profil wenn es vollständig ist.', NAME_SPACE),
            'id'        => PREFIX . 'public_mentor',
            'type'      => 'switch',
            'style'     => 'square',
            'on_label'  => 'Öffentlich',
            'off_label' => 'Privat',
        ],
```
to the field definition

## Expected Behavior

labels should be centered horizontally
## Current Behavior

labels are sticking to the top of the switch 
## Possible Solution

adding `line-height: 1.7;` to
```
.rwmb-switch-on,
.rwmb-switch-off {
	display: inline-block;
	float: left;
	margin: 0 4px;
	color: #fff;
	text-transform: uppercase;
	font-size: 11px;
	position: relative;
	z-index: 20;
}
```
inside _meta-box/css/switch.css_ should fix this
## Todos
- [ ] Tests
- [ ] Documentation

**Comment by nhatrangnet** [comment]
hi @jstask82 
Could you show show images or video about the bug ?

**Comment by jstask82** [comment]
Hey @nhatrangnet
you can see it on the last page of https://docs.google.com/document/d/1_1OZ-byWLf3L_Y4kxbJlOBtMv_hB-gsXEnjg4t1R5UY/edit in the last two images
