### ISSUE TITLE
Usage of Select Advanced for taxonomies in admin

### ISSUE THREAD

**Issue by edip123** [wpmetabox/meta-box#1497]
## Issue Overview
I created a custom field for taxonomies to select a post. When setting field_type to "select_advanced", it doesn't work, because the dependency "underscore" is missing. The JS console shows an error "jQuery.Deferred exception: _ is not defined ReferenceError: _ is not defined"
It works, when "underscore" is added as a dependency in select-advanced.php, line 14.

Code:
```
function add_category_customfields( $meta_boxes ) {
	$meta_boxes[] = [
		'title'      => 'Title',
		'taxonomies' => [ 'category' ],
		'fields'     => [
			[
				'name'       => 'Post',
				'id'         => 'category_content_post',
				'type'       => 'post',
				'post_type'  => [ 'post', 'page' ],
				'field_type' => 'select_advanced',
			],
		],
	];

	return $meta_boxes;
}
add_filter( 'rwmb_meta_boxes', 'add_category_customfields' );
```

Versions:
Wordpress: 6.2
Meta Box: 5.6.18
MB Term Meta: 1.2.10

## Steps to Reproduce (for bugs)
1. Create a custom field for a taxonomy with field type "Select advanced" or use code above to create it.
2. Go to a category
3. Try to search in the field

## Expected Behavior
Should show posts

## Current Behavior
Error message is displayed in console

## Possible Solution
Add "underscore" to dependencies in "select-advanced.php", line 14

**Comment by rilwis** [comment]
Thanks for your feedback! We've just fixed it.
