### ISSUE TITLE
Require image orientation on image_advanced field upload

### ISSUE THREAD

**Issue by wgstjf** [wpmetabox/meta-box#1503]
Hi guys,

The question is how can we define a required image orientation when using `image_advanced` field type?

I know that we can force a global orientation as follows:

```php
add_filter('wp_handle_upload_prefilter','x_media_min_dimensions'); 
function x_media_min_dimensions($file) {
    // Return file if not an image
    $mimes = array( 'image/jpeg','image/jpg', 'image/png', 'image/gif' );
    if( !in_array( $file['type'], $mimes ) ) return $file;
    // If an image then get image size and define min dimensions
    $img=getimagesize($file['tmp_name']);
    $minimum = ['width' => 800, 'height' => 800];
    $width= $img[0];
    $height =$img[1];
    if ($width < $height ) {
      return array("error"=>"Please upload landscape images only.");
    } elseif ($width < $minimum['width'] ) {
      return array("error"=>"Image dimensions are too small. Minimum width is {$minimum['width']}px. Uploaded image width is $width px");
    } elseif ($height <  $minimum['height']) {
      return array("error"=>"Image dimensions are too small. Minimum height is {$minimum['height']}px. Uploaded image height is $height px");
    } else {
      return $file;
    }
}
```

What I need to be able to do is define, when adding the field a required orientation and reject images that do not conform.  

```php
array(
  'name'  => __( 'Logo', 'indigo-metaboxes' ),
  'id'    => 'logo',
  'type'  => 'image_advanced',
  'std'   => '',
  'max_file_uploads' => 1,
  'columns'     => '4',
  'clone' => false,
  'attributes' => [
    'data-orientation' => 'landscape' // Something like this
    ],
),
```

The problem with the above example is that the filter is only aware of the $file and not the field (and its parameters) that called it.  

I appreciate this is somewhat outside the scope of Meta Box support but any thoughts on how to achieve this would be much appreciated.

Cheers,

Will

**Comment by rilwis** [comment]
Hi Will,

It seems like outside of the scope of Meta Box, so I'll close it.

However, below is my thoughts on this, maybe it helps you find a workaround:

The process of upload an image is done via ajax. When users click the **Add New** button, a popup shows, and lets users select an image or upload new ones via ajax. The bad news is this is handled with JavaScript, so we can't do anything with it via PHP. So, to handle this, we need these things:

1. A a way to send field settings via JavaScript. It must involve with the WordPress's media view JS, which is too complicated to understand and hijack. We use it in Meta Box and after a few years, it's harder and harder to maintain/understand.
2. Somehow hook into the PHP **before** the ajax call is fired.
3. Run your above filter.
4. Remove the hook **after** the ajax call is finished.

Unfortunately, I don't have a solution for 1. and 2. :(
