### ISSUE TITLE
subtitle custom field

### ISSUE THREAD

**Issue by zivaw** [wpmetabox/meta-box#1504]
## Issue Overview
 I used the online generator to create the code for a subtitle custom field (see code here: https://metabox.io/online-generator/?utm_source=WordPress&utm_medium=link&utm_campaign=plugin). When I am adding the code to the the functions file of my theme, it's giving me this message (see screenshot): "Your PHP code changes were rolled back due to an error on line 237 of file wp-content/themes/newsblock/functions.php. Please fix and try saving again."

syntax error, unexpected '<', expecting end of file

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Related Issues and/or PRs

<img width="1304" alt="Screenshot 2023-05-21 at 11 28 58 PM" src="https://github.com/wpmetabox/meta-box/assets/134231092/d34cf7eb-0ad0-4840-b61a-02ad32387e7d">

## Todos
- [ ] Tests
<img width="1304" alt="Screenshot 2023-05-21 at 11 28 09 PM" src="https://github.com/wpmetabox/meta-box/assets/134231092/f0660fec-f243-48f6-bcf4-a45c97540ca2">

- [ ] Documentation

**Comment by zivaw** [comment]
Can you locate the error?
<img width="1304" alt="Screenshot 2023-05-21 at 11 31 58 PM" src="https://github.com/wpmetabox/meta-box/assets/134231092/a855fe95-9966-47f6-8d76-0e2ec29e364c">

**Comment by zivaw** [comment]
This is the code that was generated:

<?php
add_filter( 'rwmb_meta_boxes', 'your_prefix_register_meta_boxes' );

function your_prefix_register_meta_boxes( $meta_boxes ) {
    $prefix = '';

    $meta_boxes[] = [
        'title'   => esc_html__( 'Subtitle Field Group', 'online-generator' ),
        'id'      => 'subtitle',
        'context' => 'form_top',
        'fields'  => [
            [
                'type' => 'text',
                'name' => esc_html__( 'Text', 'online-generator' ),
                'id'   => $prefix . 'text_b9sandba0i',
            ],
            [
                'type'       => 'post',
                'name'       => esc_html__( 'Post', 'online-generator' ),
                'id'         => $prefix . 'post_tzu5x0he0nh',
                'post_type'  => 'post',
                'field_type' => 'select_advanced',
            ],
            [
                'type' => 'heading',
                'name' => esc_html__( 'Heading', 'online-generator' ),
            ],
        ],
    ];

    return $meta_boxes;
}

**Comment by rilwis** [comment]
Please make sure to remove `<?php` when you pasting into your theme's `functions.php` file.
