### ISSUE TITLE
WP's preview functionality broken by this plugin as of WP v6.4

### ISSUE THREAD

**Issue by jacobph** [wpmetabox/meta-box#1546]
## Issue Overview

As long as any metaboxes are defined for a given post type, posts of that type can't be previewed from the Gutenberg editor. A new tab opens, and you'll be redirected to /wp-admin/undefined.

Disabling the plugin, or just removing any `add_filter('rwmb_meta_boxes'...` calls restores WP preview to a working state.

A similar issue has been raised on the official metabox support forums as well. Note that I'm experience this bug on ALL posts, not just those with custom post types.
https://support.metabox.io/topic/impossible-to-preview-posts/

## Steps to Reproduce (for bugs)

1. Enable plugin
2. define any metabox 
3. try to preview a post of the type that metabox is defin
4. get redirected to /wp-admin/undefined

This happens in chrome, ff, and safari. I assume it is browser agnostic.

**Comment by rilwis** [comment]
Hi @jacobph ,

Thanks for your feedback. We're investigating into this issue and narrowing it scope. We find that the validation module causes this bug and working on that. We'll update soon.

**Comment by rilwis** [comment]
Hi @jacobph ,

We've fixed this bug in 955e6a0 and will update the plugin soon. We're working on 2 small PRs which probably takes 2 days to complete. After that we'll update the plugin.

Thanks for your feedback.
