### ISSUE TITLE
Impossible to preview posts since WP 6.4.0

### ISSUE THREAD

**Issue by mvdhoek1** [wpmetabox/meta-box#1551]
I'm sorry in advance for not following the guidelines, but this link should clarify it all: https://support.metabox.io/topic/impossible-to-preview-posts/?swcfpc=1#post-44131

We're are using metabox 5.9.0.

**Comment by rilwis** [comment]
This is fixed in https://github.com/wpmetabox/meta-box/commit/955e6a0c11dfaf4f9d02e38a1cf08f703820c1ff

We’ll release a new version next week.
