### ISSUE TITLE
fix: defensively check for null post in add_fields() for php 8.3

### ISSUE THREAD

**Issue by balexey88** [wpmetabox/meta-box#1557]
Hello!

One of our customers requested some changes in `metabox` related to PHP 8.3
Could you please take a look https://github.com/udx/wp-stateless/pull/694?

Thanks you!

**Comment by rilwis** [comment]
We're working on that at #1560 . We think removing the type check for `$post` is better as it's compatible with PHP < 7.2.

**Comment by balexey88** [comment]
@rilwis thank you the update!
