### ISSUE TITLE
Metabox plugins won't update

### ISSUE THREAD

**Issue by freeassociates** [wpmetabox/meta-box#1602]
I purchased the Oshine theme from Brand Exponents via ThemeForest. It came with several Meta Box plugins, which it installed automatically. 

Meta Box seems to now be looking for a license in order to update to version 1.6.22 from 1.6.21. I'm not sure how to update it. Can you please advise me?

The plugins in question are:
* Meta Box Conditional Logic
* Meta Box Show Hide
* Meta Box Tabs

Meta Box itself is at version 5.10.0 and does not say it needs updating right now. Thanks.

**Comment by freeassociates** [comment]
@rilwis I posted this question over two weeks ago. Is anyone monitoring this github thread? Hope so!

Thanks in advance for your help with this.

**Comment by rilwis** [comment]
Hi @freeassociates ,

Meta Box is a free plugin and is available on wordpress.org. If your theme requires Meta Box, then you can install or update it from wordpress.org without any problems.

However, if your theme requires a **premium** extension, in this case, you have 3 premium extensions: Meta Box Conditional Logic, Meta Box Show Hide and Meta Box Tabs, then you need a valid license key **from MetaBox.io** (**not** from the theme) to have automatic updates for those extensions.

We'd recommend you to purchase a license key to get automatic updates for them. You can see the pricing on [our website](https://metabox.io/pricing/).
