### ISSUE TITLE
v5.10.0 Breaks Text List

### ISSUE THREAD

**Issue by vestaxpdx** [wpmetabox/meta-box#1603]
## Issue Overview
When updating from version **v5.9.11** to **v5.10.0** suddenly my **text_list** fields disappear on the backend. The data is still there as the front end is outputting but the UI breaks and you can't save new ones plus it doesn't show old existing data.

## Screenshots

v5.9.11 (working - showing existing data)
![working](https://github.com/user-attachments/assets/2ef4c12a-eb90-40c5-acfb-fc49c8b031cb)

v5.10.0 (broken - existing data has now vanished)
![broken](https://github.com/user-attachments/assets/dd6817eb-f8eb-46de-b118-882db9667ce9)

**Comment by tanftw** [comment]
Hi @vestaxpdx 

We have fixed this bug and you'll get a new update shortly.
