### ISSUE TITLE
Meta Box Custom table - Image field serialized with only one value

### ISSUE THREAD

**Issue by giuliodelmastro** [wpmetabox/meta-box#1609]
In my Meta Boxes I have a “thumbnail_id” field of type “image”. By saving the value in a custom table this is always serialized, despite the fact that it is not an array and the maximum image value is “1”.

Is there any way to solve this problem?

**Comment by wgstjf** [comment]
Have you tried the single_image field?  That should save just the image id for you.

https://docs.metabox.io/fields/single-image/

Cheers, Will

**Comment by rilwis** [comment]
`image` field always save multiple values, despite limit is set to 1. If you want to use only 1 image, it's better to use `single_image` field as @wgstjf suggested.
