### ISSUE TITLE
Dont See Submenus

### ISSUE THREAD

**Issue by hknim** [wpmetabox/meta-box#1610]
Only these submenus appear in the plugin's menu. How can I fix it?
![metabox](https://github.com/user-attachments/assets/25ff73c8-6407-41ed-be6d-01f747498724)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by rilwis** [comment]
Some submenus are available only when you install/enable corresponding [extensions](https://metabox.io/plugins/). For example:

- [MB Custom Post Types & Custom Taxonomies](https://metabox.io/plugins/custom-post-type/) => submenus: Post Types + Taxonomies
- [MB Views](https://metabox.io/plugins/mb-views/) => submenu: Views
