### ISSUE TITLE
Fatal Error in MetaBox 5.10.2: Undefined Method remove_first() During Post Creation/Update

### ISSUE THREAD

**Issue by mrkind** [wpmetabox/meta-box#1613]
Hi there!

We encountered a fatal PHP error when attempting to create or update a post in MetaBox version 5.10.2. The error appears related to the undefined method MetaBox\Support\Arr::remove_first() in the request.php file.

### Steps to Reproduce (for bugs)

1. Install MetaBox plugin version 5.10.2.
2. Add Clonable field `clone: true`
3. Attempt to create or update a post with Clonable MetaBox fields.
4. Observe the fatal error during post submission.

### Expected Behavior

The post should be created or updated successfully without causing any PHP errors.

### Current Behavior

When creating or updating a post, the following fatal error occurs:

`Fatal error: Uncaught Error: Call to undefined method MetaBox\Support\Arr::remove_first() in /var/www/wp-content/plugins/meta-box/inc/request.php on line 56`

This breaks the post creation/update process.

## Possible Solution

Reverting to MetaBox version 5.10.1 resolves the issue, suggesting a regression or missing method in the latest version (5.10.2).

## Screenshot

<img width="769" alt="image" src="https://github.com/user-attachments/assets/697bcbbd-ac1f-442d-92de-4359f1ec6e09">

**Comment by tanftw** [comment]
Hi Alex,

Are you cloning meta box from `master` branch? If so, we have updated our `metabox/support` library recently, please run: 

`composer update -o`

To update dependencies.

Cheers!
