### ISSUE TITLE
Insert a metabox though plug-in

### ISSUE THREAD

**Issue by Thunderlab** [wpmetabox/meta-box#169]
Is possible to insert a metabox just when some specific plugin is enable, or, even better, insert this metabox though the plug-in?

Thanks!!
Daniel

**Comment by andreasomovigo** [comment]
Hi, I'd need some help if someone could spend a minute...
so far I've used RWMB in my themes customization (functions.php) and I'm entusiastic of that, it works perfectly, now for the first time I'm trying to use it in a plugin. 
Assuming that the 'meta-box-master' plugin is active, and somewhere in functions.php there's a call to: 
    add_filter( 'rwmb_meta_boxes', 'myfunction_meta_boxes' );
    function myfunction_meta_boxes( $meta_boxes ){
        $meta_boxes[] = array(
        //etc etc
        );
        $meta_boxes[] = array(
        //et1 etc1
         );
    }
how do I add new meta boxes from the plugin I'm working on? this plugin creates a new post type and other stuff, and I need to use metaboxes dedicated to that CPT, I've tried to follow these instructions but without success..
thank you

**Comment by tanng** [comment]
Hi, andreasomovigo

You've missed the `return $meta_boxes;` on the last of your filter callback.
