### ISSUE TITLE
wysiwyg not saving paragraphs...

### ISSUE THREAD

**Issue by jezthomp** [wpmetabox/meta-box#23]
A wysiwyg within a meta box although saying the text is in a p tag, its not actually once its printed front end.

Bold tags work, as do others but the initial P tag does not.

Kind of making having the wysiwyg there a bit pointless?

Anyone else have this issue or just me?

**Comment by dwcouch** [comment]
I'm seeing this too - If I add <p></p> to paragraphs while in [text] then save - the html comes through on the front end.

However when I re-open, the editor is still in [text] but the html has been converted to html hex. &lt;p&gt;
Viewing it in visual of course now shows my html of course.

It's as if [text] saves html, but when re-opened it converts any html to the respective HTML Entity Names. So saving it again just makes a mess.

**Comment by rilwis** [comment]
Hi,

I've tested again with wysiwyg field type and don't see the problem (same as comments above). Here is how I input text (after save post, I see same result):

http://prntscr.com/6k74hn

And how it looks in the frontend:

http://prntscr.com/6k74lj

**Comment by dwcouch** [comment]
The visual editor view[image: Inline image 1]The

Text Editor view[image: Inline image 3]

Front end and html.[image: Inline image 7]

Edits via text to add p tags and a comment[image: Inline image 2]

This is what it looks like after saving:[image: Inline image 5]

This is how it renders:[image: Inline image 8]

The visual editor now looks like html.[image: Inline image 4]

If I make new edits to the text editor like this and save;[image: Inline
image 6]

It shows up on the front end like this:
[image: Inline image 9]


Oddly enough a quick workaround is to copy the html from the WYSIWYG editor
and paste it into the Text editor and then save.

**Comment by rilwis** [comment]
Can you upload images again? Looks like Github doesn't import images from email.

**Comment by dwcouch** [comment]
I edited the previous message. Sorry about that.

**Comment by dwcouch** [comment]
I found a stack-exchange post with a similar issue: http://wordpress.stackexchange.com/questions/94338/custom-editor-field-displaying-html-in-visual-editor

**Comment by rilwis** [comment]
Can you show me the code to register meta boxes?

**Comment by dwcouch** [comment]
```php
<?php
/**
 * Registering meta sections for taxonomies
 *
 * All the definitions of meta sections are listed below with comments, please read them carefully.
 * Note that each validation method of the Validation Class MUST return value.
 *
 * You also should read the changelog to know what has been changed
 *
 */

/********************* BEGIN DEFINITION OF META SECTIONS ***********************/
$prefix = 'badge_'; // doesn't seem to be globally supported.
global $badge_meta_sections;
$badge_meta_sections = array();

// first meta section
$badge_meta_sections[] = array(
	'title' => '',			// section title
	'taxonomies' => array('sr_expertise', 'sr_service'),			// list of taxonomies. Default is array('category', 'post_tag'). Optional
	'id' => 'first_section',					// ID of each section, will be the option name
	'fields' => array(							// list of meta fields

		// TEXT AREA
		array(
			'name' => 'Extended Description',
			'desc' => '<span class="description">Extended description.</span>',
			'id' => 'badge_verbose',
			'type' => 'wysiwyg',
			'std' => ''
		),

		// RADIO BUTTONS
		array(
			'name'    => 'Select a hover color',
			'id'      => "badge_hover_color1",
			'type'    => 'radio',
			// Array of 'value' => 'Label' pairs for radio options.
			// Note: the 'value' is stored in meta field, not the 'Label'
			'options' => array(
					'#1d2e5b' => '<span class="sr_Water		">Water 		</span><br>',
					'#634379' => '<span class="purple		">Purple 		</span><br>',
					'#445b6a' => '<span class="sr_Sea 		">Sea 			</span><br>',
					'#7895a4' => '<span class="sr_Wind		">Wind			</span><br>',
					'#5A6527' => '<span class="green 		">Green			</span><br>',
					'#818154' => '<span class="sr_Moss 		">Moss 			</span><br>',					
					'#8b6b29' => '<span class="sr_Nut_Brown">Nut Brown 		</span><br>',
					'#ba8747' => '<span class="sr_Grain 	">Grain 		</span><br>',
					'#FCC53F' => '<span class="yellow 		">Yellow 		</span><br>',
					'#e28025' => '<span class="sr_Golden 	">Golden 		</span><br>',
					'#ad1015' => '<span class="sr_Fire 		">Fire 			</span><br>',
					'#90352d' => '<span class="sr_Brick 	">Brick 		</span><br>',
					'#632d00' => '<span class="sr_Earth 	">Earth 		</span><br>',
					'#473f38' => '<span class="sr_Warm_Gray ">Warm Gray 	</span><br>',
					'#000000' => '<span class="sr_Black 	">Black 		</span><br>'
			),
		)
	)
);

/**
 * Register meta boxes
 *
 * @return void
 */
function YOUR_PREFIX_register_taxonomy_meta_boxes()
{
	// Make sure there's no errors when the plugin is deactivated or during upgrade
	if ( !class_exists( 'RW_Taxonomy_Meta' ) )
		return;

	global $badge_meta_sections;
	foreach ( $badge_meta_sections as $meta_section )
	{
		new RW_Taxonomy_Meta( $meta_section );
	}
}
// Hook to 'admin_init' to make sure the class is loaded before
// (in case using the class in another plugin)
add_action( 'admin_init', 'YOUR_PREFIX_register_taxonomy_meta_boxes' );


/********************* END DEFINITION OF META SECTIONS ***********************/

/********************* BEGIN VALIDATION ***********************/

/**
 * Validation class
 * Define ALL validation methods inside this class
 * Use the names of these methods in the definition of meta boxes (key 'validate_func' of each field)
 */
class RW_Taxonomy_Meta_Validate {
	function check_name($text) {
		if ($text == 'Anh Tran') {
			return 'He is Rilwis';
		}
		return $text;
	}
}

/********************* END VALIDATION ***********************/
?>
'''

**Comment by rilwis** [comment]
Oh, this is another plugin Taxonomy Meta. I will fix it later in [this repo](https://github.com/rilwis/taxonomy-meta).

**Comment by dwcouch** [comment]
Oh geez. Sorry Tran. I forgot these were separate.
I've got both installed inside a custom theme.
