### ISSUE TITLE
Split longitude and latitude entry for map locations into separate fields

### ISSUE THREAD

**Issue by noltedesign** [wpmetabox/meta-box#443]
Right now it saves as a comma separated single string. In order to do an advanced location query, you need to be able to query these guys individually. 

If you can query against longitude and latitude as single values, easier to identify 'nearby' posts, or posts within a certain area. 

Any suggestions? 

Thanks!

**Comment by Sinusite** [comment]
Moreover, having two separates field would be better for mashup and geocoding plugins, by naming fields :
geo_latitude, geo_longitude (we can already put geo_address with the adress field)

SEE : http://codex.wordpress.org/Geodata
Thanks :-)

**Comment by rilwis** [comment]
@Sinusite Interesting link! Thanks for sharing.

**Comment by funkedgeek** [comment]
related to https://github.com/rilwis/meta-box/issues/749

**Comment by Sinusite** [comment]
Note that it's working perfeclty with [geo mashup plugin](https://fr.wordpress.org/plugins/geo-mashup/) without two separates fields.( just name "geo_address" for 'type' => 'text', and by setting the id field name of 'type' => 'map' in settings ("Geocode Custom Field")..

**Comment by Johnnychaos** [comment]
Now map field returns HTML code:

`<div class="rwmb-map-canvas" data-map_options="{&quot;latitude&quot;:&quot;45.5820204&quot;,&quot;longitude&quot;:&quot;-122.74019629999998&quot;,&quot;width&quot;:&quot;100%&quot;,&quot;height&quot;:&quot;480px&quot;,&quot;marker&quot;:true,&quot;marker_title&quot;:&quot;&quot;,&quot;info_window&quot;:&quot;&quot;,&quot;js_options&quot;:{&quot;zoom&quot;:14,&quot;mapTypeId&quot;:&quot;ROADMAP&quot;}}" style="width:100%;height:480px"></div>`

Is there a way to get lat and long like before? It's not good solution for those who want to have custom map declarations.

**Comment by maticomp** [comment]
Bump from me. The update broke our display of all of our maps. We were relying on lat & long and rendeging using another mapping library.

**Comment by Johnnychaos** [comment]
I've found a solution - you need to use get_post_meta:
$map = get_post_meta( get_the_ID(), 'map_field', true );  // returns "lat,long"
$map = explode(',', $map);

**Comment by maticomp** [comment]
Yeah, I know how to hack this, not being able to access lat&long from Metabox without rendering a Google Map markup seems to me like a bug and unexpected behaviour though.

**Comment by rilwis** [comment]
In case you need to separate fields for **querying** the database (like looking for nearby places), this is a a simple hack:

https://wordpress.org/support/topic/seperate-latitude-and-longitude-from-map-meta-box

We would probably update this later when we found a good way to migrate old data.

**Comment by tanng** [comment]
FYI, this can be done when you use premium Meta Box Geolocation extension.
