### ISSUE TITLE
Best option to display uploaded images in a gallery/slider?

### ISSUE THREAD

**Issue by Paybax** [wpmetabox/meta-box#482]
Hello,

So I really love meta-box and it has worked great for my noobie coding skills, however I am having issues displaying the images in a way that I like. I get the thumbnails the way I want using just the default code for it which is

$images = rwmb_meta( 'gallery', 'type=image' );
foreach ( $images as $image )
{
    echo "<a href='{$image['full_url']}' title='{$image['title']}' rel='thickbox'><img src='{$image['url']}' width='{$image['width']}' height='{$image['height']}' alt='{$image['alt']}' /></a>";
}

but the issue I have is that it links to the full upload URL, however if it went to the attachment URL instead that would be a good solution for me. However when that happens I lose the photo order that was set using meta-box pluploader. Does anyone have any full code that I could use for this? Even it was the same photo order as the thumbs but listed the full images in a new window/page that would be perfect too. I just need something really simple, but I am not well versed enough to pull it off myself yet.

Here is a working example

http://gwenty.com/example/listings/2356-ravenhill-road-shawnigan-lake/

This is the last part stopping me from finishing this up....

Thanks,
Ryan

**Comment by lusareal** [comment]
We use this:

```
global $post;

$size = 'houzez-single-big-size';

$properties_images = rwmb_meta( 'fave_property_images', 'type=plupload_image&size='.$size, $post->ID );

$thumb_title = get_the_title();
                                        $ii = 1;
                                        foreach( $properties_images as $prop_image_id => $prop_image_meta ) {
                                            //my_debug ($prop_image_meta);
                                            echo '<div style="background-image: url('.esc_url( $prop_image_meta['url'] ).');'
                                                    . 'background-size:cover;background-position:center;">';
                                            echo '<a title="'.$thumb_title.' - '.$ii.'" class="popup-trigger banner-link" href="'.esc_url( $prop_image_meta['url'] ).'">';
                                            echo '</a>';
                                            echo '</div>';
                                            $ii++;
                                        }
```
