### ISSUE TITLE
Integrating with other plugins & themes

### ISSUE THREAD

**Issue by baden03** [wpmetabox/meta-box#483]
After thoroughly reading and testing the recommended method of including meta-box in other themes and plugins http://www.deluxeblogtips.com/meta-box/include-meta-box-plugin-in-themes/ and 
https://github.com/rilwis/meta-box/issues/169 it seems there is not really current best-practice for the current version of the plugin.

Keeping in mind that integrate this plugin as part of another plugin must be able to deal with a) WordPress installs that already have the meta-box stand-alone plugin installed b) Theme that already include meta-box and c) another plugin that is also including meta-box.  Finally, there is the issue of different themes/plugins loading in different versions of meta-box.  I brought this up here: https://github.com/rilwis/meta-box/issues/276 but ended up just modifying meta-box to use unique class names so there would be no conflict.

Example:  Two plugins that want to include meta-box
Step 1. check if it already has been loaded, and if not, include it.

``` php
if ( ! class_exists( 'RW_Meta_Box' ) )
    require_once 'inc/meta-box/meta-box.php';
```

Step 2. load in boxes

``` php
class WP_Test {
    function __construct() {
        add_action( 'admin_init', array( $this, 'admin_init' ) );
    }

    function admin_init() {
        $meta_boxes = array();
        if ( ! class_exists( 'My_Meta_Boxes' ) )
            include_once 'inc/meta-box/my_meta-boxes.php';
        My_Meta_Boxes::build( $meta_boxes, 'colomand_' );

        if ( class_exists( 'RW_Meta_Box' ) )
            foreach ( $meta_boxes as $meta_box )
            new RW_Meta_Box( $meta_box );
    }
}
$WP_Test = new WP_Test;
```

Step 3. define boxes

``` php
class My_Meta_Boxes{
    static function build( &$meta_boxes, $prefix ){
        $meta_boxes[] = array (
            'id' => 'cpt_settings',
            'title' => 'Custom Post Settings',
            'pages' => array (
                'post-type',
            ),

            'fields' => array (
                array(
                    'name' => __( 'Funky Images', 'my_text_domain' ),
                    'id'   => "{$prefix}img",
                    'type' => 'plupload_image',
                ),
            )
        );
    }
}
```

However, when more than one version of meta-box is being loaded up, the following warnings appear:

```
WARNING: wp-content/plugins/plugin1/inc/meta-box/inc/meta-box.php:388 - call_user_func() expects parameter 1 to be a valid callback, first array member is not a valid class name or object
require_once('wp-admin/admin.php'), do_action('admin_init'), call_user_func_array, WP_Plugin2->admin_init, RW_Meta_Box->__construct, RW_Meta_Box::normalize, RW_Meta_Box::normalize_fields, call_user_func
```

Any ideas on how to avoid conflicts without having to create custom versions of meta-box for each plugin that wishes to include it?

**Comment by rilwis** [comment]
@ThemePlugger I've just implemented autoload feature. Please try it and tell me if anything need to be improved :)

**Comment by chiqui3d** [comment]
Hi,
Sorry if this is not the right place for this question.

I'm developing a plugin and I am integrating Metabox, but has been test with several customers and already have the first mistakes with some themes as the7,

And I have many similar errors like this:
`Strict Standards: Declaration of RWMB_Image_Advanced_MK2_Field::html() should be compatible with RWMB_File_Field::html($meta, $field) in /homepages/35/directory/htdocs/directory/wp-content/themes/dt-the7/inc/extensions/custom-meta-boxes/metabox-fields.php on line 113
`

It is possible to fix it?

**Comment by rilwis** [comment]
HI @chiqui3d : As I see, the error says that the theme created a **new field** `image_advanced_mk2` which implements a function `html`. The problem is that function doesn't declare all params passed to it as in `RWMB_File_Field::html`. Just fix this and everything will be ok.

For more info, please check: https://metabox.io/docs/create-field-type/
