### ISSUE TITLE
Call_user_func() Warning

### ISSUE THREAD

**Issue by krishna19** [wpmetabox/meta-box#509]
Metabox Plugin show warning when DEBUG is True.

<pre>
Warning: call_user_func() expects parameter 1 to be a valid callback, first array member is not a valid class name or object in /Applications/MAMP/htdocs/themes/wp-content/plugins/meta-box/inc/meta-box.php on line 80<br/>
Warning: call_user_func() expects parameter 1 to be a valid callback, first array member is not a valid class name or object in /Applications/MAMP/htdocs/themes/wp-content/plugins/meta-box/inc/meta-box.php on line 389</pre>

**Comment by rolandinsh** [comment]
#564 same
