### ISSUE TITLE
Map won't show on post editing, am i missing something?

### ISSUE THREAD

**Issue by TioFelix** [wpmetabox/meta-box#518]
My code is the same as demo:

``` php
$meta_boxes[] = array(
    'title' => __( 'Google Map', 'meta-box' ),
    'fields' => array(
        array(
            'id' => 'address',
            'name' => __( 'Address', 'meta-box' ),
            'type' => 'text',
            'std' => __( 'Hanoi, Vietnam', 'meta-box' ),
        ),
        array(
            'id' => 'loc',
            'name' => __( 'Location', 'meta-box' ),
            'type' => 'map',
            'std' => '-6.233406,-35.049906,15', // 'latitude,longitude[,zoom]' (zoom is optional)
            'style' => 'width: 500px; height: 500px',
            'address_field' => 'address', // Name of text field where address is entered. Can be list of text fields, separated by commas (for ex. city, state)
        ),
    ),
);
```

But this is what i get:
![google_map_rilwis](https://cloud.githubusercontent.com/assets/1236543/5307400/f80e1386-7bf3-11e4-9774-004db770928e.png)

Things to consider:
- Tried using the "Find Address" button a couple of times, also after change the value, after saving the post... Nothing, nothing make it work.
- The "rwmb-map-canvas" div is there. as well as the hidden input with the latitude and longitude info, but the canvas is empty;
- The JS console won't shout any error or warning;
- I'm using WP 4.0.1;
- There are other "$meta_boxes[]" entries on the same array and same function, but the same seems to happen even if i isolate it;
- My server is using a cloudflare CDN cache, i can't disable it, neither i have another server without CDN i could test on. Not sure if this is any problem. But even purging the cache doesn't seem do to anything related to that.

Any guesses?

**Comment by dougcassidy** [comment]
Just fyi, the map example, in the /samples doesnt show the            
 'style' => 'width: 500px; height: 500px',
Which is apparently necessary for  the map to be shown in the backend.
however, there is 
https://metabox.io/docs/display-map-in-the-front-end/
which shows width and height fields... that dont do anything?
