### ISSUE TITLE
SVG Support

### ISSUE THREAD

**Issue by sbouafif** [wpmetabox/meta-box#593]
Hello,

First thanks for the plugin.

I would like to know if the support for svg can be considered in meta-box ?

I tried a few things but couldn't add svg support without another plugin (named Scalable Vector Graphics) on top of modifying meta-box source code.

**Comment by certainlyakey** [comment]
Same problem here. Even when uploading SVG globally is allowed, Meta Box doesn't allow to select SVGs when using `image_advanced` field.

**Comment by funkedgeek** [comment]
WordPress doesn't support SVG as images, hence why it isn't support yet
