### ISSUE TITLE
Thickbox image type with "From URL" upload does not load image

### ISSUE THREAD

**Issue by gurumark** [wpmetabox/meta-box#613]
If I tried to upload image from URL in the thickbox image, the image is not uploaded. See the screenshot:

![thickbox_image](https://cloud.githubusercontent.com/assets/1859151/7973286/dbedf2ae-0a21-11e5-8850-588ae9746878.png)

**Comment by thaoha** [comment]
Can you show me your code. I'll check it.

**Comment by gurumark** [comment]
I am using the demo.php in this repository.

**Comment by thaoha** [comment]
Thank @gurumark. I got the same problem. I'll fix it and reply to you as soon as possible.

**Comment by gurumark** [comment]
Hey @thaoha , is there any progress on this issue?

**Comment by Ninetheme** [comment]
Wordpress 4.5.3 Thickbox  image not working for metabox, please fix asap.

Best Regards

**Comment by d2roth** [comment]
What code are you using?

**Comment by Ninetheme** [comment]
default metabox.io demo.php codes.

**Comment by rilwis** [comment]
Let's close this issue. `thickbox_image` is deprecated in WordPress and should not be used.
