### ISSUE TITLE
Media Enhancements

### ISSUE THREAD

**Issue by funkedgeek** [wpmetabox/meta-box#692]
Basically stuff I want to work on in the future:
- Audio and Video fields
- A preview modal to show larger versions of images
- Drag and drop capability integrated in all the media/attachment fields, which will lead to the deprecation of the plupload field

**Comment by rilwis** [comment]
I would like to have the edit image in the modal window, so we can change the image title, caption, description, etc.

**Comment by rilwis** [comment]
I'll close this issue because:

- We have `video` field
- Preview of media modal is added
- Drag & drop capability is supported within `image_upload` / `file_upload` field.
