### ISSUE TITLE
Taxonomy Not Working

### ISSUE THREAD

**Issue by RickPrice62** [wpmetabox/meta-box#73]
There's a strange error with the taxonomy field (checkbox_list or select) the output is always empty, if i change the $prefix the selected values are still there only for that field, when i check another post or page that includes that option , a random checkbox is selected on each post or page even if the post was not saved with those options.

I'm using the default code (no changes) and the code is inside my plugins folder. i'm not sure if i'm doing something wrong.

**Comment by custard-apple** [comment]
when I'm typing `$result = wp_set_object_terms( $product_ID, 'variable', 'product_type' );`
getting this as output  
`WP_Error Object
(
    [errors] => Array
        (
            [invalid_taxonomy] => Array
                (
                    [0] => Invalid taxonomy
                )
        )
    [error_data] => Array
        (
        )

)`

**Comment by funkedgeek** [comment]
is `product_type` a valid taxonomy?  Can you post the code that initializes this taxonomy?
