### ISSUE TITLE
Use fields with custom table?

### ISSUE THREAD

**Issue by lazharichir** [wpmetabox/meta-box#946]
Hello,

I am coding a very specific plugin and I create my own "Add New" pages since I use my own custom tables for some parts. I want to output the HTML code cleanly using your library of HTML Fields but are they just usable within a post_type or metabox, or can I use them anywhere in WordPress?

Thank you.

L

**Comment by rilwis** [comment]
I'm thinking about doing that. We are working on a common way to store data between post types, terms and settings page. After that, the custom table will be the target.

**Comment by funkedgeek** [comment]
My idea is to separate the logic of saving and retrieving the meta data in a separate object.  then you can have 1 for meta data, one for settings, one for taxonomy terms and then eventually, custom ones for custom tables

**Comment by rilwis** [comment]
FYI, this feature has been done with [MB Custom Table](https://metabox.io/plugins/mb-custom-table/)
