### ISSUE TITLE
Error in Meta Box Plugin

### ISSUE THREAD

**Issue by kentchee** [wpmetabox/meta-box#952]
Hi all,

Anyone knows how to rectify this error?

Warning: call_user_func() expects parameter 1 to be a valid callback, class 'RWMB_Input_Field' does not have a method 'walk' in /home/mingoicecreamcom/public_html/wp-content/plugins/meta-box/inc/fields/object-choice.php on line 19

**Comment by funkedgeek** [comment]
Please show the code you are using so we track down what is going on.  I think you might have misspelled the type of field

**Comment by mattle1106** [comment]
Hello:
I having much same problem:

Problem happened when I activated Meta box BUT deactive it then is ok!

description problem:
dashboard--->pages---->new page: the text editor disappear with a message on:
""Fatal error: Uncaught Error: Call to undefined method RW_Meta_Box::get_class_name() in C:\xampp\htdocs\avaz\wp-content\themes\snsavaz\framework\sns-metabox.php:395 Stack trace: #0 C:\xampp\htdocs\avaz\wp-content\plugins\meta-box\inc\field.php(474): RWMB_Layouttype_Field::walk(Array, Array, Array, Array) #1 C:\xampp\htdocs\avaz\wp-content\plugins\meta-box\inc\fields\choice.php(35): RWMB_Field::call('walk', Array, Array, Array, Array) #2 C:\xampp\htdocs\avaz\wp-content\plugins\meta-box\inc\field.php(474): RWMB_Choice_Field::html(Array, Array) #3 C:\xampp\htdocs\avaz\wp-content\plugins\meta-box\inc\field.php(56): RWMB_Field::call(Array, 'html', 'm-r') #4 C:\xampp\htdocs\avaz\wp-content\plugins\meta-box\inc\field.php(474): RWMB_Field::show(Array, true) #5 C:\xampp\htdocs\avaz\wp-content\plugins\meta-box\inc\meta-box.php(178): RWMB_Field::call('show', Array, true) #6 C:\xampp\htdocs\avaz\wp-admin\includes\template.php(1045): RW_Meta_Box->show(Object(WP_Post), Array) #7 C:\xampp\htdocs\avaz\wp-admin\edit-form-advanced.php(693): in C:\xampp\htdocs\avaz\wp-content\themes\snsavaz\framework\sns-metabox.php on line 395""

My active theme is: themeforest-15175474-avaz-fashion-responsive-woocommerce-wordpress

Looking forwards to having your support

Thank you so much:

Matt
email: mattle.auto@gmail.com

**Comment by rilwis** [comment]
@matthewsimo Please send me the theme to check (email support@fitwp.com).

**Comment by mattle1106** [comment]
Hi Tuấn Anh:

Are you Vietnamese? my pleasure! I'm Vietnamese, too!

Please follow the link to the theme I am being used with error generated by
meta-box plugin
https://app.box.com/s/kbhreqrvrryddodw5nwg6rld6pfwa04w

when meta-box activated the problem happens in page editor... but
deactivate it the problem released!

please help me to check

Thanks,
Matt

**Comment by rilwis** [comment]
Just sent you the fix via email. The reason is the theme uses a custom field type which uses our old code (which is not published).

**Comment by mattle1106** [comment]
Thanks Tuan Anh
But I don't receive any attached file in the email? Please check!
Best,
Matt

**Comment by rilwis** [comment]
I sent from support@fitwp.com. But here is the file again. Please put it into `framework` folder.
[sns-metabox.zip](https://github.com/rilwis/meta-box/files/468721/sns-metabox.zip)

**Comment by 19thomas86** [comment]
Rilwis would you be able to help me with this issue?
Fatal error: Call to undefined method RW_Meta_Box::get_class_name() in /home2/thomas/public_html/wp-content/plugins/meta-box-group/class-rwmb-group-field.php on line 61

I have been reading it seems its a little bit of a common fault with the new update maybe but i do not have the experience.

Best Regards 
Tommy

**Comment by rilwis** [comment]
Please update the group extension. It's already fixed!

Best regards

**Comment by mattle1106** [comment]
Hi Tuấn Anh,
Không hiểu sao meta_box fixed vừa rồi ok nhưng lại tạo lỗi khác -> shop
page của woocommerce chỉ show 1 column trong khi setting là 3 column! Bạn
có thể fix giúp dc không? Theme hôm trước sent cho bạn đó! Mình rất thích
theme này...

Waiting...
Thanks with best regards,
Matt

**Comment by rilwis** [comment]
Đây là lỗi của theme thôi. Có thể là các template của theme ko tưowng thích với version mới của WooCommerce. Bạn có thể xem trong WooCommerce > Status.

Vấn đề này ko thuộc phạm vi của Meta Box nên bạn vui lòng liên hệ tác giả của theme để được fix nhé.

Best regards

**Comment by truyenmaaudio** [comment]
Chào bạn.

Warning: call_user_func_array() expects parameter 1 to be a valid callback, class ‘RWMB_Input_Field’ does not have a method ‘print_templates’ in /home/albaligh/public_html/wp-includes/plugin.php on line 524

Mình upload lên ver wp mới thì bị cái này.

**Comment by rilwis** [comment]
@truyenmaaudio: Bạn post code bạn dùng register meta boxes lên nhé.

**Comment by jamaicavb** [comment]
Hi everyone!, how are you doing?
 I'm having this problem, the Theme i'm using is Ottavio, when I go to persons section and edit one I receive 2 errors:

Warning: call_user_func_array() expects parameter 1 to be a valid callback, class 'RWMB_Group' does not have a method 'set_saved' in siteFolder/wp-includes/class-wp-hook.php on line 298
Photo

Fatal error: Call to undefined method RW_Meta_Box::get_class_name() in /SiteFolder/wp-content/plugins/meta-box-group/class-rwmb-group-field.php on line 41

Aand i can't edit fields, this is happening with lastest versions, if i Downgrade to version 4.8.5 i can see the fields, and I only receive this error:

Warning: call_user_func_array() expects parameter 1 to be a valid callback, class 'RWMB_Group' does not have a method 'set_saved' in siteFolder/wp-includes/class-wp-hook.php on line 298

**Comment by rilwis** [comment]
FYI, most of the errors come from outdated version of Meta Box or extensions. Updating them all will fix it.
