### ISSUE TITLE
File_advanced upload bug/issue

### ISSUE THREAD

**Issue by xxkiefxx** [wpmetabox/meta-box#966]
I’m having a problem uploading files using file_advanced.

Essentially, the file uploads but isn’t immediately visible or selectable – I can only see old media library content, not the new file I’ve just added.

To see it I actually have to change the filter (even if it’s already set on all media) after changing the filter the file is visible and selectable as normal

the mime type is set on

`mime_type' => 'application,audio,video`

This doesn’t append when I upload the files from wordpress media and neither when I upload images from upload_image_advanced.

I’ve seen that the problem was highlighted long ago in this post
[https://wordpress.org/support/topic/file_advanced-upload-bugissue-mime_type/]

but its for a older version. I’m using metabox 4.9 (same problem appened on 4.87, 4.86 and probably also in other). I think that this fix it should be already integrated in these versions but still it’s appening

Any new fix for this annoying bug?
thanks

**Comment by funkedgeek** [comment]
The bug is with WordPress itself.  The modal doesn't update correctly when you upload when you are trying to filter the files you are uploading
